### ISSUE TITLE
请教一下InternVL-Chat-V1.5如何进行lora微调呢

### ISSUE THREAD

**Issue by zhangfan-algo** [OpenGVLab/InternVL#104]

**Comment by zhangfan-algo** [comment]
急求 辛苦各位大佬帮忙看下

**Comment by 2132660698** [comment]
+1

**Comment by czczup** [comment]
感谢大佬们关注，我这两天会准备一个微调的示例脚本。

**Comment by hgfriver** [comment]
+1

**Comment by dandanW91** [comment]
+1

**Comment by MVP-D77** [comment]
> 感谢大佬们关注，我这两天会准备一个微调的示例脚本。

请问现在有可以用于微调1.5或者1.5-int8的脚本了嘛

**Comment by longgb246** [comment]
+1

**Comment by danxuan2022** [comment]
> 感谢大佬们关注，我这两天会准备一个微调的示例脚本。

微调脚本现在有了吗

**Comment by czczup** [comment]
现在可以按照这个文档进行InternVL 1.5的微调：https://internvl.readthedocs.io/en/latest/internvl1.5/finetune.html
