### ISSUE TITLE
where is internvl-chat-v1.5 technical report?

### ISSUE THREAD

**Issue by liuheng0111** [OpenGVLab/InternVL#107]
where can i find the internvl-chat-v1.5 technical report?
Is there a WeChat communication group?

**Comment by czczup** [comment]
Hello, thanks for your attention, our technical report has been released:

https://arxiv.org/abs/2404.16821

You can join our wechat group by scanning this QR code:

![image](https://github.com/OpenGVLab/InternVL/assets/23737120/982479fa-62b2-4d3d-b0f8-4d2899bad498)
