### ISSUE TITLE
OpenGVLab/InternViT-6B-448px-V1-5如何多卡运行

### ISSUE THREAD

**Issue by GITRMG** [OpenGVLab/InternVL#110]
单卡最大16g，示例代码跑不起来，使用了CUDA_VISIBLE_DEVICES=1,0或export CUDA_VISIBLE_DEVICES=0,1都还是默认单卡运行，请问16+12够运行吗，如何多卡运行呢

**Comment by lihan** [comment]
要A100 80GB 才可以单卡运行

**Comment by czczup** [comment]
感谢反馈，我们正在解决这个问题。

**Comment by GITRMG** [comment]
> 感谢反馈，我们正在解决这个问题。

您好，请问运行vit-6b最少需要多少显存呢，需要A100 80g才可以运行吗，想单独运行来做ocr

**Comment by czczup** [comment]
> > 感谢反馈，我们正在解决这个问题。
> 
> 您好，请问运行vit-6b最少需要多少显存呢，需要A100 80g才可以运行吗，想单独运行来做ocr

如果是bf16的话，需要16G+的显存，int8大概8G+；不过单独用vit还做不了ocr，需要额外接上ocr的识别头。
