### ISSUE TITLE
Do you plan on releasing the dataset used to train internVL 1.5 ?

### ISSUE THREAD

**Issue by Mohamed-Dhouib** [OpenGVLab/InternVL#111]
Hello,
As stated in the huggingface page of InternVL 1.5, a High-Quality Bilingual Dataset was used to train this model.
Do you plan to release this dataset in the future ?
Thanks !

**Comment by czczup** [comment]
Hi, we may release the annotation files in the JSONL format that we use. However, to make them usable for everyone, we will need to create a document detailing the placement of paths and the downloading of images. This will take some time.
