### ISSUE TITLE
InternVL Chat v1.5版本

### ISSUE THREAD

**Issue by KooSung** [OpenGVLab/InternVL#113]
请问InternVL Chat v1.5 Demo中v1.5和v1.5 backup有什么不同吗？测试发现两个回答不一致。
![image](https://github.com/OpenGVLab/InternVL/assets/34935911/ec1fb1f1-e4af-41fa-a2a0-0e29949767ed)

**Comment by 2132660698** [comment]
同问

**Comment by czczup** [comment]
这几个模型都是一样的，回答不一样是因为在参数里开了Temperature=0.8，所以输出会有比较大的随机性。

<img width="385" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/3b81be73-b4dc-464f-9b7c-c81af5f2dbca">
