### ISSUE TITLE
InternVL-Chat-V1.2的finetune耗时多久？

### ISSUE THREAD

**Issue by cyj95** [OpenGVLab/InternVL#114]
从issue中已经了解了硬件需求
![image](https://github.com/OpenGVLab/InternVL/assets/31176427/59ea78ef-0e2b-4b83-87da-788b7382f186)
![image](https://github.com/OpenGVLab/InternVL/assets/31176427/8f009c79-3d0f-4204-9b07-c1d7e15ffdc9)
还想了解一下finetune全部LLM和lora分别耗时多久？

**Comment by czczup** [comment]
您好，感谢您的关注。finetune 1.2现在看性价比没有很高了，因为那个模型有点太大了（40B），我这两天会准备一下1.5版本的finetune。

**Comment by SxJyJay** [comment]
> 您好，感谢您的关注。finetune 1.2现在看性价比没有很高了，因为那个模型有点太大了（40B），我这两天会准备一下1.5版本的finetune。

请问finetune 1.5大概需要的资源量消耗是多少呢

**Comment by sunzx8** [comment]
> 您好，感谢您的关注。finetune 1.2现在看性价比没有很高了，因为那个模型有点太大了（40B），我这两天会准备一下1.5版本的finetune。

您好，请问现在可以finetune 1.5了吗

**Comment by plmsmile** [comment]
> 您好，感谢您的关注。finetune 1.2现在看性价比没有很高了，因为那个模型有点太大了（40B），我这两天会准备一下1.5版本的finetune。

您好，请问现在可以finetune 1.5了吗

**Comment by Felix0805** [comment]
> 您好，感谢您的关注。finetune 1.2现在看性价比没有很高了，因为那个模型有点太大了（40B），我这两天会准备一下1.5版本的finetune。

您好，什么时候会放出1.5版本的finetune脚本呢
