### ISSUE TITLE
Contributing a dataset.

### ISSUE THREAD

**Issue by arthurwolf** [OpenGVLab/InternVL#117]
Hello.

If I created a dataset of (open-source/public domain) comic book images, and descriptions of them (in the same line as the datasets listed at https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#prepare-training-datasets ), would you then integrate that dataset into your training data so it then gets trained into future models?

If not, any recommendations on how I can help getting comic book data integrated into datasets so I can see future models get better at understanding comics (currently models like llava are not very good at it).

Thanks !

**Comment by czczup** [comment]
Hi, we greatly appreciate your willingness to contribute a dataset. We tested our current model using some comic images, but the results were somewhat average. If we could use your dataset to enhance our capabilities in this area, that would be truly wonderful.

Here is a sample of my test:
<img width="940" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/499bb3cb-7ed5-417d-9e49-7819f1a83823">
