### ISSUE TITLE
如何进行 v1.2/v1.2_plus的 Pretrain?

### ISSUE THREAD

**Issue by Pro-flynn** [OpenGVLab/InternVL#120]
请问如何进行v1.2_plus的Pretrain训练
1、看您发布的huggingface的说明，pretrain阶段只训练MLP，请问是否是这样
2、当前您发布的现有代码中没有pretrain的相关提示，请问如何进行pretrain的训练？
是否在https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/hermes2_yi34b/internvl_chat_v1_2_hermes2_yi34b_448_finetune.sh中把freeze_llm、freeze_backbone设置为True即可？
![image](https://github.com/OpenGVLab/InternVL/assets/25923129/0038a222-b4ab-4b21-a32d-556bd3f3dcfb)

**Comment by czczup** [comment]
是的，您可以设置`freeze_llm=True`和`freeze_backbone=True`，这样就只训练MLP。
