### ISSUE TITLE
Scripts to continue finetuning InternVL-chat-v1-5 on custom data

### ISSUE THREAD

**Issue by swz30** [OpenGVLab/InternVL#121]
Hi @czczup 

Could you please provide/update scripts to further [finetune InternVL-Chat v1.5 on custom data](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/CONTINUED_FINETUNE.md). 

Thank you.

**Comment by swz30** [comment]
Hi @whai362 @czczup @cg1177 

Could you please provide an update on your plans for releasing the finetuning scripts? Thank you.

**Comment by ParanoidW** [comment]
Same question. @whai362 @czczup @cg1177 Is there a plan about this? Thank you !

**Comment by cyj95** [comment]
also waiting for finetune scripts for v1-5 model

**Comment by brooks0519** [comment]
same question!

**Comment by tdye24** [comment]
Same!

**Comment by G-z-w** [comment]
Thanks for your attention, we have released our fine-tuning code [LINK](https://github.com/OpenGVLab/InternVL/blob/v2.0.0/document/How_to_finetune_mini_internvl_chat_v1_5_on_a_custom_dataset.md)
