### ISSUE TITLE
InternVL 1.5 Pretrain & Finetuning scripts

### ISSUE THREAD

**Issue by plmsmile** [OpenGVLab/InternVL#126]
Hi, thanks for the sharing of this great work.

Could you release InterVL1.5  pretrain&finetune code/scripts?

**Comment by G-z-w** [comment]
> Hi, thanks for the sharing of this great work.
> 
> Could you release InterVL1.5 pretrain&finetune code/scripts?

Thanks for your attention, we have released our pretrain&finetune code. See [LINK](https://github.com/OpenGVLab/InternVL/tree/v2.0.0/internvl_chat/shell/internlm2_1_8b_dynamic)
