### ISSUE TITLE
Unexpected err=TypeError("internvl_chat isn't supported yet")

### ISSUE THREAD

**Issue by thiner** [OpenGVLab/InternVL#130]
我尝试用LocalAI的AutoGPTQ backend 加载internvl-chat-v1.5-int8 量化模型，推理代码使用的是InternVL的ReadMe中提供的样例代码。在加载模型时报错：
```
could not load model (no success): Unexpected err=TypeError(\"internvl_chat isn't supported yet.\")
```
我查看了HF上的模型相关文件，`internvl_chat`似乎是在`config.json`中定义的。如下：
```
"model_type": "internvl_chat",
```

本地运行的pip依赖如下：

- transformers: 4.40.1
- torch: 2.1.2
- torchvision: 0.16.2

请问应该如何修复？

**Comment by thiner** [comment]
我尝试了`pip install internvl_chat===1.2.3`，安装不了，好像并没有发布到pip仓库。那这么说就必须从源代码安装了吗？

**Comment by G-z-w** [comment]
你好，请问现在问题修复了吗？internvl需要从从源代码安装，感谢关注，另外AutoGPTQ backend没有支持internvl 模型，建议您使用LMDeploy。See [LINK](https://github.com/InternLM/lmdeploy/blob/main/docs/en/inference/vl_pipeline.md)
