### ISSUE TITLE
[Suggestion]Add result to openclip benchmark

### ISSUE THREAD

**Issue by BIGBALLON** [OpenGVLab/InternVL#14]
Thank you for your amazing and effective work, the results of the experiment are outstanding and exciting.

Do you have any plans to update the results of the model to [open_clip ](https://github.com/mlfoundations/open_clip)benchmark?

- cls benchmark: https://github.com/mlfoundations/open_clip/blob/main/docs/openclip_results.csv
- retrieval benchmark: https://github.com/mlfoundations/open_clip/blob/main/docs/openclip_retrieval_results.csv

**Comment by czczup** [comment]
Thank you for your interest!
I have this plan, estimated in the next few days.
