### ISSUE TITLE
請問可以在MacBook M系列的電腦上跑嗎？

### ISSUE THREAD

**Issue by seasoncool** [OpenGVLab/InternVL#141]
如题。

**Comment by nigo81** [comment]
同问。因为macbook统一内存架构，相对来说放下这么大的模型，成本较低。

**Comment by czczup** [comment]
现在暂时还不支持，因为我的mac没这么大内存，还没法调试 😂

**Comment by seasoncool** [comment]
希望能支持一下mac。。。 或者出一个部署教程也好，不太知道需要哪些依赖要下载。。。感谢。

**Comment by mobguang** [comment]
@czczup 项目很有价值，也希望能支持Mac的M系列芯片，感谢。

**Comment by leechs** [comment]
希望能支持Mac，别的很多大模型都能跑的

**Comment by bigbigtooth** [comment]
@czczup 同求！希望能支持Mac，让我的M3 Max 64G不要荒废

**Comment by G-z-w** [comment]
> @czczup 同求！希望能支持Mac，让我的M3 Max 64G不要荒废

感谢关注，目前团队缺少设备和足够人手，未来随着mac工具链的发展，我们会加入todo，也欢迎开源社区的力量，为项目pr。
