### ISSUE TITLE
请问有在 V100-32G 的GPU上进行测试的finetune的脚本吗？

### ISSUE THREAD

**Issue by Qinger27** [OpenGVLab/InternVL#146]
V100 不支持 flash-attn，想问下有没有不通过 flash-attn的脚本呢？以及用 internvl-v1.5 进行测试时，使用8卡还是报错 OOM的问题，请问怎么解决？迫切期待您的回复～

**Comment by czczup** [comment]
您好，V100可以参考这个回答：https://github.com/OpenGVLab/InternVL/issues/144
