### ISSUE TITLE
Collaboration request to create an API for the InternVL-Chat-V1.5 model

### ISSUE THREAD

**Issue by JoshuaStudios** [OpenGVLab/InternVL#148]
Hi team,

I am working on a website for a project at my school for the entrepreneurship course and I need your help. I want to integrate OpenGVLab's InternVL-Chat-V1.5 model into my website to be able to answer visual questions about skin problems, but unfortunately I do not have access to the specialized hardware, such as an NVIDIA RTX 4090, that is required to implement this model efficiently.

Please could you help me by creating an API so that I can make requests to this wonderful model from my web page? I don't have advanced programming knowledge, so any help you can give me would be a great help.

I appreciate in advance any support you can give me!

![Captura de pantalla 2024-05-06 202949](https://github.com/OpenGVLab/InternVL/assets/140543415/7431593c-49c0-427b-acf3-53a10ebf280c)

**Comment by Adushar** [comment]
@JoshuaStudios I've made a "community-hosted version". It's hell as expensive to host but I need it for myself so I hope somebody else will join us and it starts to at least break even)

You can try it for free here
https://rapidapi.com/adushar1320/api/internvl-chat

**Comment by JoshuaStudios** [comment]
Thank you,

I need to implement a chat on my website to help users identify skin problems on their faces. The functionality should allow them to upload images directly from their devices, not just from URLs. Could you help me? I am a newbie programmer and I would greatly appreciate your guidance.

I am attaching an image showing what the chat structure should look like as a reference to chatgpt:
![Captura de pantalla 2024-05-29 160944](https://github.com/OpenGVLab/InternVL/assets/140543415/c5eee62c-c51d-46e6-8c9b-0be3182be97b)

**Comment by ElementTech** [comment]
I made it available on Replicate:

https://replicate.com/elementtech/internvl-chat-v1-5

I'm still trying to finding a cheaper way to host this

**Comment by G-z-w** [comment]
Hi, our API is now open for application.[LINK](https://docs.google.com/forms/d/e/1FAIpQLSfMCzhPr1OOEKau_6jwTU0EiZMSFckDo-HMlc_hUudhF_97rw/viewform?pli=1)
