### ISSUE TITLE
Any further plans on knowledge distillation?

### ISSUE THREAD

**Issue by lcxrocks** [OpenGVLab/InternVL#15]
ViT-22B conducted knowledge distillation experiments (refer to [Table 8](https://openreview.net/pdf?id=Lhyy8H75KA)), demonstrating that it is not only a large-scale model but also an excellent teacher. Has there been any consideration or experiments conducted on whether Intern-VL can be distilled into smaller models, given that it serves as the largest open-source vision/vision-language foundation model to date (and a good alternative to the ViT-22B)? Thank you in advance for your attention.

**Comment by czczup** [comment]
Hello, thank you for your question. We have considered distilling InternVL into smaller models. In the future, we plan to conduct relevant distillation experiments to explore its potential as a teacher for smaller models.

**Comment by lcxrocks** [comment]
Sounds promising. Hoping to see the potential of this vision-language model being applicable in many more situations.

**Comment by zoezhu** [comment]
> Hello, thank you for your question. We have considered distilling InternVL into smaller models. In the future, we plan to conduct relevant distillation experiments to explore its potential as a teacher for smaller models.

@czczup Hello, is there any tutorial about distilling internViT now? Looking forward to the guidence, since I am working on this part and wonder which loss should I use.
