### ISSUE TITLE
No such file(textvqa_val.jsonl) when evaluating textvqa

### ISSUE THREAD

**Issue by zhizhou57** [OpenGVLab/InternVL#151]
When I follow the method in "how_to_evaluate_internvl_chat_1_5.md" , I found that there is no such file in your repo data release.

404 page not found when run:
wget https://github.com/OpenGVLab/InternVL/releases/download/data/textvqa_val.jsonl

**Comment by czczup** [comment]
Sorry for giving the wrong link, now readme has corrected it, please download the following two files:

wget https://huggingface.co/OpenGVLab/InternVL/raw/main/textvqa_val.jsonl
wget https://huggingface.co/OpenGVLab/InternVL/raw/main/textvqa_val_llava.jsonl
