### ISSUE TITLE
InternVL−Chat−V1.5-Int8的耗时是InternVL−Chat−V1.5的三倍吗？

### ISSUE THREAD

**Issue by wtl0207** [OpenGVLab/InternVL#157]
InternVL−Chat−V1.5-Int8的耗时是InternVL−Chat−V1.5的三倍吗？我在A100上进行测试，同样的数据，InternVL−Chat−V1.5耗时550秒，InternVL−Chat−V1.5-Int8耗时1810秒

**Comment by czczup** [comment]
Int8虽然省显存了，但是推理会变慢

**Comment by xylovezxy** [comment]
请问模型效果会变差吗
