### ISSUE TITLE
very trival progress compare with llava1.5

### ISSUE THREAD

**Issue by lucasjinreal** [OpenGVLab/InternVL#16]
mostly are just boosted 0.x point, and TextVQA largely behind llava1.5, why?
How's the Chinese QA and Chinese characters indentification performance?

**Comment by czczup** [comment]
Thanks for your attention. The decrease in TextVQA performance might be due to our lower pre-training resolution. We plan to release weights for higher resolution pre-training in the near future, such as 336x336 and 448x448.

**Comment by whai362** [comment]
Hi lucasjinreal, thanks for your attention. We will keep updating our open-source model, including high-resolution version mentioned by czczup, and we will add more training data to further increase the domain generalization capability of our model.
