### ISSUE TITLE
InternVL-14B-224px，多gpu推理报错。使用device_map='auto'时，“RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!”

### ISSUE THREAD

**Issue by ChengLigen** [OpenGVLab/InternVL#161]
设备为8*V100，40G显存版本，使用device_map='auto'时，部署InternVL-14B-224px报错，错误如下。

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

**Comment by huu3301** [comment]
@ChengLigen 
想按照 #96 的方法修改 huggingface/transformers_modules/InternVL-Chat-V1-5/modeling_internlm2.py里面1066行为
logits = logits.float().to((inputs_embeds if inputs_embeds != None else input_ids).device)
但是每次启动，transformers都会自动复原那个文件导致无法修改。
请问是怎么解决的？谢谢。

**Comment by longgb246** [comment]
请问一下是怎么解决的呢？同样遇到这个问题了
