### ISSUE TITLE
Can swft fine-tuning be done in InternVL−Chat−V1.5-Int8 version?

### ISSUE THREAD

**Issue by wangdong1992** [OpenGVLab/InternVL#165]

**Comment by MVP-D77** [comment]
Have you had any success with this please? Following the tutorial it gives, I found that the 1.5 version can be fine-tuned, but the 1.5-int8 fine-tuning reports an error, seemingly because of a datatype issue

**Comment by czczup** [comment]
This issue has been inactive for two months, so I am closing it. If you have any further questions or encounter any problems, please feel free to reopen it. Thank you!
