### ISSUE TITLE
CUDA out of memory - minimum gpu size

### ISSUE THREAD

**Issue by yscoffee** [OpenGVLab/InternVL#167]
Thanks for the amazing work.
Could you please suggest the minimum GPU size for doing offline Inference?
I tried with 24GB 4090 but it turns out not enought for running the offline inference example.

**Comment by BIGBALLON** [comment]
@yscoffee The total number of model parameters is 25.5B, consisting of the architecture of InternViT-6B-448px-V1-5 + MLP + InternLM2-Chat-20B. 

- For bf16, at least 52GB of GPU memory is required. 
- For int8, at least 26GB of GPU memory is needed.  There is also some additional overhead. so 32GB memory is needed.

Examples, if you can understand Chinese, you can refer to this [article](https://zhuanlan.zhihu.com/p/697188143):

- 1 GPU for int8 model: ![image](https://github.com/OpenGVLab/InternVL/assets/7837172/a56430c3-c8f5-4a8d-a012-474dafefc5f1)
- 2 GPU for bf16 model: ![image](https://github.com/OpenGVLab/InternVL/assets/7837172/da5d199f-d52e-47ef-8880-9a0e5384997f)
- 4 GPU for bf16 model: ![image](https://github.com/OpenGVLab/InternVL/assets/7837172/d5217f94-6bfb-40c8-a9d6-f396e7df14d3)

**Comment by yscoffee** [comment]
thank you for the detail explanation!
