### ISSUE TITLE
ZeRO strategy script for Semantic Segmentation Training

### ISSUE THREAD

**Issue by wyyhit** [OpenGVLab/InternVL#17]
Thank you for open-sourcing this brilliant and outstanding project. However, with a model size of 6 billion parameters, it is still infeasible to train on consumer-grade graphics cards without using memory optimization tools like DeepSpeed. Could you provide a semantic segmentation training script based on mmsegmentation and the ZeRO strategy in the future? Looking forward to your reply.

**Comment by czczup** [comment]
Hello, we do indeed have an internal version of mmsegmentation that supports deepspeed (an older version of mmsegmentation, v0.25.0), but we have made significant changes to the mmcv code, which may be difficult to maintain in the future. We plan to investigate whether there is a more elegant way to support deepspeed, such as upgrading to the latest version of mmsegmentation (v1.x) and using mmgine.

**Comment by wyyhit** [comment]
> Hello, we do indeed have an internal version of mmsegmentation that supports deepspeed (an older version of mmsegmentation, v0.25.0), but we have made significant changes to the mmcv code, which may be difficult to maintain in the future. We plan to investigate whether there is a more elegant way to support deepspeed, such as upgrading to the latest version of mmsegmentation (v1.x) and using mmgine.

Thank you for your response. I was wondering if it might be possible for you to first open-source this part of the custom code so that we can explore training with DeepSpeed. We look forward to your more elegant usage method with mmsegmentation in the future. Thank you very much.

**Comment by czczup** [comment]
> > Hello, we do indeed have an internal version of mmsegmentation that supports deepspeed (an older version of mmsegmentation, v0.25.0), but we have made significant changes to the mmcv code, which may be difficult to maintain in the future. We plan to investigate whether there is a more elegant way to support deepspeed, such as upgrading to the latest version of mmsegmentation (v1.x) and using mmgine.
> 
> Thank you for your response. I was wondering if it might be possible for you to first open-source this part of the custom code so that we can explore training with DeepSpeed. We look forward to your more elegant usage method with mmsegmentation in the future. Thank you very much.

Of course, it's possible, but I need some time to organize the code. It's worth noting that there seems to be compatibility issues with PyTorch 2, so you'll need to set up an additional environment with PyTorch 1.12.

**Comment by wyyhit** [comment]
> > > Hello, we do indeed have an internal version of mmsegmentation that supports deepspeed (an older version of mmsegmentation, v0.25.0), but we have made significant changes to the mmcv code, which may be difficult to maintain in the future. We plan to investigate whether there is a more elegant way to support deepspeed, such as upgrading to the latest version of mmsegmentation (v1.x) and using mmgine.
> > 
> > 
> > Thank you for your response. I was wondering if it might be possible for you to first open-source this part of the custom code so that we can explore training with DeepSpeed. We look forward to your more elegant usage method with mmsegmentation in the future. Thank you very much.
> 
> Of course, it's possible, but I need some time to organize the code. It's worth noting that there seems to be compatibility issues with PyTorch 2, so you'll need to set up an additional environment with PyTorch 1.12.

That's great, thank you for your open-source spirit. I am really looking forward to the subsequent updates, and also, thank you for the reminder about the environment setup.

**Comment by czczup** [comment]
I open this issue as a todo to remind me not to forget about this.

**Comment by wyyhit** [comment]
> I open this issue as a todo to remind me not to forget about this.
Okay, I am very much looking forward to your update. Thank you once again!

**Comment by wyyhit** [comment]
May I ask if there has been any progress? Looking forward to your reply.

**Comment by czczup** [comment]
> May I ask if there has been any progress? Looking forward to your reply.

I'm sorry that I have a lot of trivial things to do recently. I will release this code as soon as possible, probably within this week.

**Comment by wyyhit** [comment]
> > May I ask if there has been any progress? Looking forward to your reply.
> 
> I'm sorry that I have a lot of trivial things to do recently. I will release this code as soon as possible, probably within this week.

Okay, I look forward to your update and express my highest respect.

**Comment by czczup** [comment]
Sorry to keep you waiting, I have posted the code at: https://github.com/OpenGVLab/InternVL-DeepSpeed. However, I haven't had time to write a README yet. I will update with the README tomorrow.

**Comment by wyyhit** [comment]
> Sorry to keep you waiting, I have posted the code at: https://github.com/OpenGVLab/InternVL-DeepSpeed. However, I haven't written a README for it yet. I will update with the README tomorrow.

Great! Thanks a lot!

**Comment by czczup** [comment]
@wyyhit README has been updated, if you encounter any problems in use, please feel free to contact me.

**Comment by wyyhit** [comment]
> @wyyhit README has been updated, if you encounter any problems in use, please feel free to contact me.

Sure, I am planning to try training in the next couple of days. I'll ask for your advice if needed.

**Comment by czczup** [comment]
I have decided to close this issue. If you encounter any problems, feel free to ask me in the [InternVL-MMDetSeg](https://github.com/OpenGVLab/InternVL-MMDetSeg) repository.
