### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 2390968687** [OpenGVLab/InternVL#174]
Help with this. Thank you
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

Python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'2.1.2+cu121'

**Comment by tdye24** [comment]
Same as yours, maybe too high cuda version.

**Comment by czczup** [comment]
Hi, has this problem been solved?
