### ISSUE TITLE
对身份证中住址等多行信息识别返回不准确

### ISSUE THREAD

**Issue by w7team** [OpenGVLab/InternVL#178]
如果最后一行为两个字或者很少的字，会被整理成分类名称，导致返回的json内容中地址信息缺少部分信息

这是提示词的问题，还是模型的问题，不知道如何优化，给指教指教

![image](https://github.com/OpenGVLab/InternVL/assets/74588507/e697b598-bd04-4931-8499-5f289408a9ca)

**Comment by czczup** [comment]
因为训练数据中很少有身份证的数据，所以处理的还不够好
