### ISSUE TITLE
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

### ISSUE THREAD

**Issue by zhishao** [OpenGVLab/InternVL#18]
I've tried install strictly according to the installation.md , but still got this error, 

my env : ubuntu20.04 , cuda11.8, torch2.1.1, python3.8, 2080ti x2

Detail:
FlashAttention is not installed.
Discovered apex.normalization.FusedRMSNorm - will use it instead of LlamaRMSNorm
FlashAttention is not installed.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Traceback (most recent call last):
  File "zz_demo.py", line 244, in <module>
    model = AutoModel.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 3462, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_internvl.py", line 188, in __init__
    self.vision_model = InternVisionModel(config.vision_config)  # frozen
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 288, in __init__
    self.encoder = InternVisionEncoder(config)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 228, in __init__
    self.layers = nn.ModuleList([
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 229, in <listcomp>
    InternVisionEncoderLayer(config, dpr[idx]) for idx in range(config.num_hidden_layers)])
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 188, in __init__
    self.attn = InternAttention(config)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 119, in __init__
    self.q_norm = InternRMSNorm(self.embed_dim, eps=config.layer_norm_eps)
  File "/usr/local/lib/python3.8/dist-packages/apex/normalization/fused_layer_norm.py", line 393, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

**Comment by czczup** [comment]
Thanks for your feedback. One of the fastest solutions is to please uninstall apex. This error appears to be due to apex's CUDA extensions not being installed successfully. See [this issue](https://github.com/NVIDIA/apex/issues/954) in apex.

**Comment by czczup** [comment]
If you want to use apex, you can add a few lines of code to `setup.py`, like this, and then recompile:

<img width="1142" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/d0607623-aa10-4ab9-9b50-64771538819a">

**Comment by zhishao** [comment]
@czczup Thx for your reply ! It works !
And Im testing 14B on V100 x1, could you tell me how to get the image embedding or the text embbeding , or cross-mode embedding ?

**Comment by zhishao** [comment]
@czczup Hello, could you tell me how to export onnx file of the image encoder and text encoder , thanks !

**Comment by czczup** [comment]
> @czczup Thx for your reply ! It works ! And Im testing 14B on V100 x1, could you tell me how to get the image embedding or the text embbeding , or cross-mode embedding ?

You can use this code to get image embedding and text embedding:
```python
import torch
from PIL import Image
from transformers import AutoModel, CLIPImageProcessor
from transformers import AutoTokenizer


model = AutoModel.from_pretrained(
    'OpenGVLab/InternVL-14B-224px',
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True).cuda().eval()

image_processor = CLIPImageProcessor.from_pretrained('OpenGVLab/InternVL-14B-224px')

tokenizer = AutoTokenizer.from_pretrained(
    'OpenGVLab/InternVL-14B-224px', use_fast=False, add_eos_token=True)
tokenizer.pad_token_id = 0  # set pad_token_id to 0

images = [
    Image.open('./examples/image1.jpg').convert('RGB'),
    Image.open('./examples/image2.jpg').convert('RGB'),
    Image.open('./examples/image3.jpg').convert('RGB')
]
prefix = 'summarize:'
texts = [
    prefix + 'a photo of a red panda',  # English
    prefix + '一张熊猫的照片',  # Chinese
    prefix + '二匹の猫の写真'  # Japanese
]

pixel_values = image_processor(images=images, return_tensors='pt').pixel_values
pixel_values = pixel_values.to(torch.bfloat16).cuda()
input_ids = tokenizer(texts, return_tensors='pt', max_length=80,
                      truncation=True, padding='max_length').input_ids.cuda()

# InternVL-C
logits_per_image, logits_per_text = model(
    image=pixel_values, text=input_ids, mode='InternVL-C')
probs = logits_per_image.softmax(dim=-1)
# tensor([[9.9609e-01, 5.2185e-03, 6.0070e-08],
#         [2.2949e-02, 9.7656e-01, 5.9903e-06],
#         [3.2932e-06, 7.4863e-05, 1.0000e+00]], device='cuda:0',
#        dtype=torch.bfloat16, grad_fn=<SoftmaxBackward0>)

# InternVL-G
logits_per_image, logits_per_text = model(
    image=pixel_values, text=input_ids, mode='InternVL-G')
probs = logits_per_image.softmax(dim=-1)
# tensor([[9.9609e-01, 3.1738e-03, 3.6322e-08],
#         [8.6060e-03, 9.9219e-01, 2.8759e-06],
#         [1.7583e-06, 3.1233e-05, 1.0000e+00]], device='cuda:0',
#        dtype=torch.bfloat16, grad_fn=<SoftmaxBackward0>)
```

**Comment by czczup** [comment]
I'm not very familiar with ONNX, but you can try converting it according to the Transformers' guide first: https://github.com/huggingface/transformers/blob/3cefac1d974db5e2825a0cb2b842883a628be7a0/docs/source/en/serialization.md.

**Comment by zhishao** [comment]
Thanks a lot! I export onnx on torch style, just use torch.onnx.export(). 
Wonderful work!

**Comment by scuizhibin** [comment]
> Thanks a lot! I export onnx on torch style, just use torch.onnx.export(). Wonderful work!
导出来的onnx文件精度差距过大，请问你遇到过吗？

**Comment by ChenJian7578** [comment]
Is there any other way to export the onnx model
