### ISSUE TITLE
1.5最大窗口长度只有2048吗？可不可以设置的更长比如4096

### ISSUE THREAD

**Issue by sunzx8** [OpenGVLab/InternVL#180]

**Comment by czczup** [comment]
训练的最大窗口是4096，推理时可以扩大到10k，测试过没问题。
如果是在demo上，可以通过调整Max output tokens来控制：
<img width="1394" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/b21d36c1-cc4f-44e8-bf5c-542154e60d26">

**Comment by sunzx8** [comment]
请问如果想把训练的长度扩的更大应该怎么办？比如我想扩到8192，应该从预训练开始重新做吗？

**Comment by czczup** [comment]
我觉得不需要重头预训练，4k训练的模型直接扩大到8k-10k没有大问题，如果想扩大到更大的长度，可能需要再用长数据做一下微调。

另外您可以试试我们最近发布的[Mini-InternVL-Chat-2B-V1-5](https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-2B-V1-5)和[Mini-InternVL-Chat-4B-V1-5](https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-4B-V1-5)，这两个模型都是在8k长度下做的SFT。

**Comment by sunzx8** [comment]
> 我觉得不需要重头预训练，4k训练的模型直接扩大到8k-10k没有大问题，如果想扩大到更大的长度，可能需要再用长数据做一下微调。
> 
> 另外您可以试试我们最近发布的[Mini-InternVL-Chat-2B-V1-5](https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-2B-V1-5)和[Mini-InternVL-Chat-4B-V1-5](https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-4B-V1-5)，这两个模型都是在8k长度下做的SFT。

谢谢，请问长度为4096做sft大约需要多少资源？不配置slurm集群可以用16*48G卡来做吗

**Comment by czczup** [comment]
4B的这个问题是Phi3语言模型本身的问题，因为Phi3的词表太小，对中文支持很烂。目前看下来完全没救，以后也会避免使用Phi3来训练模型
