### ISSUE TITLE
Support for Mac for internvl-chat-v1.5

### ISSUE THREAD

**Issue by gitrodg1** [OpenGVLab/InternVL#184]
I am very impressed with the great work you have done. I have a Mac M2 ultra so can't run the model locally because of the need to use cuda, instead of the apple gpu,mps. I have managed to the model loaded and generate the input ids tokenizer and pixel values as shown in the huggingface repository. Unfortunately lmdeploy and flash attention don't function on the Mac. If there is any possibility of adding support for apple silica many more people in the community would get to experience your great work. Thank you for creating the gradio demo. That way even though the model is inaccessible for local testing I can see what I'm missing.  Thanks again for all your efforts.

**Comment by wjn922** [comment]
Currently we do not hava the plan to support for Mac. 

We welcome and appreiate any PRs to help us add this support.
