### ISSUE TITLE
动态分patch

### ISSUE THREAD

**Issue by fasgsagsgageta** [OpenGVLab/InternVL#186]
新手想问一下动态分patch的代码在什么地方啊？找不到555

**Comment by czczup** [comment]
请参考这里的dynamic_preprocess函数：https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5#model-usage

在这个代码库里的话，是在：https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/dataset.py#L637
