### ISSUE TITLE
请问InternVL_1.5_26B的LoRA微调版本什么时候能出来？

### ISSUE THREAD

**Issue by McCarthyjfq** [OpenGVLab/InternVL#188]
目前有1.2版本的LoRA微调，但是我用到1.5版本的模型上显示了一些权重匹配上的问题，即某些权重层的key不一样。想问一下有什么解决方案，我现在的算力不支持我用full llm。1.5版本的LoRA微调什么时候可以release？

**Comment by zhangye0402** [comment]
同问一手，有没有发行计划呢？

**Comment by MVP-D77** [comment]
@czczup 同问一下，什么时候可以发布

**Comment by McCarthyjfq** [comment]
亲测1.2版本的lora微调可以用在1.5版本上，但需要做以下更改
![image](https://github.com/OpenGVLab/InternVL/assets/144629782/93c73fb3-3fd4-4e82-86f5-535efe96a639)

**Comment by McCarthyjfq** [comment]
> 亲测1.2版本的lora微调可以用在1.5版本上，但需要做以下更改 ![image](https://private-user-images.githubusercontent.com/144629782/333088717-93c73fb3-3fd4-4e82-86f5-535efe96a639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTA4MjUsIm5iZiI6MTcxNjQ1MDUyNSwicGF0aCI6Ii8xNDQ2Mjk3ODIvMzMzMDg4NzE3LTkzYzczZmIzLTNmZDQtNGU4Mi04NmY1LTUzNWVmZTk2YTYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwNzQ4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzE4NDJiNjdmZmUwZjUyNzUwNTc3ZWQ4ODBlYjRiOTdlMTZhZTFkMDMyZGUxYjcxYjJmNGZkNjlkMTBmODM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W5fkZlGHGPTP6vOTpYacFPHC2xJ9s9hytZFVONf0vjU)

同时merge lora的权重时可以借鉴swift库

**Comment by BlueBlueFF** [comment]
> > 亲测1.2版本的lora微调可以用在1.5版本上，但需要做以下更改 ![image](https://private-user-images.githubusercontent.com/144629782/333088717-93c73fb3-3fd4-4e82-86f5-535efe96a639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTA4MjUsIm5iZiI6MTcxNjQ1MDUyNSwicGF0aCI6Ii8xNDQ2Mjk3ODIvMzMzMDg4NzE3LTkzYzczZmIzLTNmZDQtNGU4Mi04NmY1LTUzNWVmZTk2YTYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwNzQ4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzE4NDJiNjdmZmUwZjUyNzUwNTc3ZWQ4ODBlYjRiOTdlMTZhZTFkMDMyZGUxYjcxYjJmNGZkNjlkMTBmODM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W5fkZlGHGPTP6vOTpYacFPHC2xJ9s9hytZFVONf0vjU)
> 
> 同时merge lora的权重时可以借鉴swift库

merge lora这里有更具体一些的代码吗 swift封装太深 没太看明白。。
