### ISSUE TITLE
2B模型微调

### ISSUE THREAD

**Issue by LCY5600** [OpenGVLab/InternVL#189]
请问可以基于Mini-InternVL−Chat−2B-V1.5模型进行微调吗

**Comment by Xiyu-AI** [comment]
> 请问可以基于Mini-InternVL−Chat−2B-V1.5模型进行微调吗

您好，请问您在2B的模型上进行微调了吗

**Comment by Felix0805** [comment]
2b模型微调好像会有loss=0的问题

**Comment by czczup** [comment]
您好，您可以更新到最新的代码，然后按照这个文档对2B模型进行微调：https://internvl.readthedocs.io/en/latest/internvl1.5/finetune.html

**Comment by awakenlee180** [comment]
> 2b模型微调好像会有loss=0的问题

我用1b 也是loss=0（2.0版本

**Comment by josephzpng** [comment]
> > 2b模型要求会有loss=0的问题
> 
> 我用1b也是loss=0（2.0版本

I encountered the same problem

**Comment by awakenlee180** [comment]
是没有合并权重

**Comment by josephzpng** [comment]
> 是没有合并权重

hello 具体怎么理解呢？我是用了internvl2-1b模型加了一些小修改，训到一半时 grad_norm为nan，loss为0

**Comment by awakenlee180** [comment]
>

> > 是没有合并权重
> 
> hello 具体怎么理解呢？我是用了internvl2-1b模型加了一些小修改，训到一半时 grad_norm为nan，loss为0

哦你是在训练的过程中loss=0，那我理解错了 你这个应该是看下warning 里面。大概是长度不匹配
