### ISSUE TITLE
A model similar to Coca but with larger vision backbone and language backbone?

### ISSUE THREAD

**Issue by mu-cai** [OpenGVLab/InternVL#19]
Is my understanding correct?

**Comment by czczup** [comment]
Thanks for your question. 
Our architecture is different from CoCa. For example, CoCa applies contrastive Loss on the Unimodal Text Decoder and then uses an additional Multimodal Text Decoder to calculate the captioning loss. It uses different model components to receive different supervisory signals.
<img width="294" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/f7d87f74-5066-4dea-81bc-3a71842147bd">
Differently, our QLLaMA can be used as both a text encoder for contrastive learning and a text decoder for generative learning. We switch between these two modes by controlling the attention mask,  using the same model weights.
