### ISSUE TITLE
本地推理和用提供的demo推理结果不一致

### ISSUE THREAD

**Issue by linsiwei123** [OpenGVLab/InternVL#190]
本地推理和提供的demo结果不一致是为什么呢，请问demo具体的参数设置是什么呢

**Comment by xiaomuv58q666** [comment]
本地效果怎么演示？

**Comment by linsiwei123** [comment]
我采用huggingface上提供的加载模型推理的方式，然后传入图片得到结果，和提供的chatdemo结果相差比较大
<img width="590" alt="1716280288465" src="https://github.com/OpenGVLab/InternVL/assets/146950608/0c33e6ad-9ec7-4753-b022-38e0dba0ad9b">

**Comment by czczup** [comment]
应该是因为推理的超参数设置不一样
<img width="373" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/adf5fb9d-9250-4f2b-836e-0d0c1ecb6f1f">

**Comment by fourierer** [comment]
> 应该是因为推理的超参数设置不一样 <img alt="image" width="373" src="https://private-user-images.githubusercontent.com/23737120/332409443-adf5fb9d-9250-4f2b-836e-0d0c1ecb6f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjcxODQsIm5iZiI6MTcxNjM2Njg4NCwicGF0aCI6Ii8yMzczNzEyMC8zMzI0MDk0NDMtYWRmNWZiOWQtOTI1MC00ZjJiLTgzNmUtMGQwYzFlY2I2ZjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA4MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NzM5NmQzOGQ1MGIyOWVjYjBhYjExMTIyMzQ1YTE3OGM0MjljOGRlNzNiYzhhZTg0MjAzNGQyZGNmNTJiYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M1zsgNdjywNYj7FRX9wh9_ejtZAmfxSi9Ws5kqMXtII">

请问如何在hugging face给的代码示例中指定和demo一样的超参数呢，我这里尝试了demo和hugging face代码示例，结果差异也很大
![image](https://github.com/OpenGVLab/InternVL/assets/55837279/dc789bea-b91d-4111-b326-ad36534e84e4)
![image](https://github.com/OpenGVLab/InternVL/assets/55837279/9e6e8a7b-cecd-47f0-a0b0-2ebd0f46b939)

**Comment by Qinger27** [comment]
> 我采用huggingface上提供的加载模型推理的方式，然后传入图片得到结果，和提供的chatdemo结果相差比较大 <img alt="1716280288465" width="590" src="https://private-user-images.githubusercontent.com/146950608/332346798-0c33e6ad-9ec7-4753-b022-38e0dba0ad9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTg5MTksIm5iZiI6MTcxNzA1ODYxOSwicGF0aCI6Ii8xNDY5NTA2MDgvMzMyMzQ2Nzk4LTBjMzNlNmFkLTllYzctNDc1My1iMDIyLTM4ZTBkYmEwYWQ5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwODQzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTg4NzE0YzNiMWFhZDRiOTBhM2Y4MDlkYjgzNjI5NWU4YzAzMTlkYzY3MzNhODQxNmQyMzI1NWIyNDc3NGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZAg_BzJ74cB1AZ185FCEZBcGPDu3p65SBpqfLIyr5MY">

请问您使用的gpu是多大的显存？我用了两张32g的卡，模型加载时设置device_map="auto"进行推理, 但是报错RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!，请问可以帮忙看一下吗？感谢～

**Comment by czczup** [comment]
> found at least two devices

这个bug很多人都遇到了，我暂时没想到比较好的方法能够适配所有情况，有个方案可以解决，需要手工为模型分配设备。

比如这个模型总共26B，2张卡最理想的情况是每张卡13B。因此，除去ViT的6B以外，卡0还需要放7B，也就是20B的LLM有1/3在卡0，有2/3在卡1。

写成代码就是：

```python
device_map = {
    'vision_model': 0,
    'mlp1': 0,
    'language_model.model.tok_embeddings': 0,
    'language_model.model.norm': 1,
    'language_model.output.weight': 1
}
for i in range(16):
    device_map[f'language_model.model.layers.{i}'] = 0
for i in range(16, 48):
    device_map[f'language_model.model.layers.{i}'] = 1
print(device_map)
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map=device_map
).eval()
```
