### ISSUE TITLE
使用internvl1.5对视频进行进行问答

### ISSUE THREAD

**Issue by aabbc-cell** [OpenGVLab/InternVL#191]
我希望能使用internvl1.5对视频进行问答，可以采取什么方式？
我已尝试过对视频抽帧，并将抽出的多张图像cat在一起作为输入，但过多的图像cat在一起显然会大幅增加我的输入长度，从而在inference的时候显存爆炸。据此，有什么方式能较好使用internvl1.5的对视频输入进行问答吗？

**Comment by Xiyu-AI** [comment]
> 我希望能使用internvl1.5对视频进行问答，可以采取什么方式？ 我已尝试过对视频抽帧，并将抽出的多张图像cat在一起作为输入，但过多的图像cat在一起显然会大幅增加我的输入长度，从而在inference的时候显存爆炸。据此，有什么方式能较好使用internvl1.5的对视频输入进行问答吗？

您好，可以加下微信好友吗？？我最近也在看这个

**Comment by czczup** [comment]
如果视频的每一帧都作为一张高分辨率的图片处理，会导致显存吃不消，我推荐是在使用[这个代码](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5#model-usage)进行处理的时候，设置max_num=1，然后每一帧都会被resize到448x448。之后把所有帧的图片拼接起来。如果有80G的显卡，应该最多可以处理到40帧每个视频。

**Comment by Xiyu-AI** [comment]
请问18帧的话，需要多少现存，一个24g够用吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhe Chen ***@***.***&gt;
发送时间: 2024年5月30日 20:55
收件人: OpenGVLab/InternVL ***@***.***&gt;
抄送: 习泽宇 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [OpenGVLab/InternVL] 使用internvl1.5对视频进行进行问答 (Issue #191)





 
如果视频的每一帧都作为一张高分辨率的图片处理，会导致显存吃不消，我推荐是在使用这个代码进行处理的时候，设置max_num=1，然后每一帧都会被resize到448x448。之后把所有帧的图片拼接起来。如果有80G的显卡，应该最多可以处理到40帧每个视频。

**Comment by Xiyu-AI** [comment]
谢谢您



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhe Chen ***@***.***&gt;
发送时间: 2024年5月30日 21:04
收件人: OpenGVLab/InternVL ***@***.***&gt;
抄送: 习泽宇 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [OpenGVLab/InternVL] 使用internvl1.5对视频进行进行问答 (Issue #191)





 
可以试试4B参数的这个模型，对这个模型24G肯定很够：https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-4B-V1-5
 如果是26B的那个大模型的话，24G可能勉强够，得用4bit量化。

**Comment by mi4da** [comment]
> 可以试试4B参数的这个模型，对这个模型24G肯定很够：https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-4B-V1-5 如果是26B的那个大模型的话，24G可能勉强够，得用4bit量化。 4bit量化可以参考这个：https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ

您好请问您知道如何端到端微调这个2B的VLM模型吗，有什么可以用来参考，我想用来finetune我的OCR数据集，做VQA，有偿+V: joseph2jonathen.

**Comment by wuntunfisher** [comment]
> 如果视频的每一帧都作为一张高分辨率的图片处理，会导致显存吃不消，我推荐是在使用[这个代码](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5#model-usage)进行处理的时候，设置max_num=1，然后每一帧都会被resize到448x448。之后把所有帧的图片拼接起来。如果有80G的显卡，应该最多可以处理到40帧每个视频。
> 
> <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/23737120/335186915-eb0fdafa-c27e-4c5d-990b-6c6c83c2e2e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjYxNjMsIm5iZiI6MTcyMDQyNTg2MywicGF0aCI6Ii8yMzczNzEyMC8zMzUxODY5MTUtZWIwZmRhZmEtYzI3ZS00YzVkLTk5MGItNmM2YzgzYzJlMmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4MDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YTQ3YzQzZGNlM2U3YjVmYjExZmI5YmM5NjY1Mzg5ZDVjNGE4ZGI4NWNkODY2Y2JkMzA0MTNhZjIzMTAyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_I0VL46g0fM9IgZ0YyJszWWmfEXZ5hzufVAxa_2-4Q">

这个可以多卡进行吗，比方说我有八张卡，我想要把每帧都作为高分辨率的图片处理

**Comment by czczup** [comment]
> > 可以试试4B参数的这个模型，对这个模型24G肯定很够：https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-4B-V1-5 如果是26B的那个大模型的话，24G可能勉强够，得用4bit量化。 4bit量化可以参考这个：https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ
> 
> 您好请问您知道如何端到端微调这个2B的VLM模型吗，有什么可以用来参考，我想用来finetune我的OCR数据集，做VQA，有偿+V: joseph2jonathen.

可以按这个文档进行微调：https://internvl.readthedocs.io/en/latest/internvl1.5/finetune.html

**Comment by czczup** [comment]
> > 如果视频的每一帧都作为一张高分辨率的图片处理，会导致显存吃不消，我推荐是在使用[这个代码](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5#model-usage)进行处理的时候，设置max_num=1，然后每一帧都会被resize到448x448。之后把所有帧的图片拼接起来。如果有80G的显卡，应该最多可以处理到40帧每个视频。
> > <img alt="image" width="680" src="https://private-user-images.githubusercontent.com/23737120/335186915-eb0fdafa-c27e-4c5d-990b-6c6c83c2e2e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjYxNjMsIm5iZiI6MTcyMDQyNTg2MywicGF0aCI6Ii8yMzczNzEyMC8zMzUxODY5MTUtZWIwZmRhZmEtYzI3ZS00YzVkLTk5MGItNmM2YzgzYzJlMmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA4MDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YTQ3YzQzZGNlM2U3YjVmYjExZmI5YmM5NjY1Mzg5ZDVjNGE4ZGI4NWNkODY2Y2JkMzA0MTNhZjIzMTAyODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_I0VL46g0fM9IgZ0YyJszWWmfEXZ5hzufVAxa_2-4Q">
> 
> 这个可以多卡进行吗，比方说我有八张卡，我想要把每帧都作为高分辨率的图片处理

多卡推理可以试试这个代码：https://internvl.readthedocs.io/en/latest/internvl1.5/quick_start.html#multiple-gpus
