### ISSUE TITLE
InternViT−6B−448px−V1.5怎么进行TP拆分

### ISSUE THREAD

**Issue by yjzhong89** [OpenGVLab/InternVL#192]
请问一下，我在使用megatron对InternViT进行TP拆分时，发现num_attention_heads=25，这个数值无法被2的倍数整除，这个数值当初在设计时是怎么考虑的呢？是否可以替换成其他数值，比如24？

**Comment by czczup** [comment]
在我们最初选定ViT的参数的时候，由于经验不足，没有考虑到要将num_attention_heads设置成2的倍数。因此现在在将模型迁移到megatron的时候，我们只给LLM开TP，会给性能带来一点损失。

**Comment by Weiyun1025** [comment]
如果一定要ViT部分开TP的话，可以尝试对维度做zero padding到2的倍数

**Comment by FUJIsyu0515** [comment]
@czczup 请问可以提供一份模型迁移到megatron的代码参考吗？
