### ISSUE TITLE
请问internvl-chat1.5-26B模型什么时候支持 AWQ和 kv-cache int8量化呢？

### ISSUE THREAD

**Issue by YangYangTx** [OpenGVLab/InternVL#194]

**Comment by irexyc** [comment]
已经支持了

https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ
https://mp.weixin.qq.com/s/3kB-cjIc9Tz23HiBfj1Xpg

**Comment by czczup** [comment]
是的，感谢lmdeploy团队提供的支持。

**Comment by EasonGZY** [comment]
> 已经支持了
> 
> https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ https://mp.weixin.qq.com/s/3kB-cjIc9Tz23HiBfj1Xpg
请问什么时候可以支持智谱团队的CogVLM2?期待！

**Comment by janelu9** [comment]
如何量化到awq的，量化教程有吗？自己微调了原模型
