### ISSUE TITLE
demo页面和本地模型调用推理结果很难保持一致，请问本地推理的参数如何设置

### ISSUE THREAD

**Issue by fourierer** [OpenGVLab/InternVL#195]
应该是因为推理的超参数设置不一样
<img width="373" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/adf5fb9d-9250-4f2b-836e-0d0c1ecb6f1f">

_Originally posted by @czczup in https://github.com/OpenGVLab/InternVL/issues/190#issuecomment-2122435799_
            
我在本地是这样设置的参数，但是结果没有网页上的理想，请问完成的参数设置是什么样子的呢
generation_config = dict(
    num_beams=1,
    max_new_tokens=512,
    do_sample=True,
    top_p=0.7,
    temperature=0.8
)

**Comment by czczup** [comment]
你在本地跑的transformers版本是什么？还要图片的分辨率也对齐一下，demo上是12个块，hf的代码里默认是6个块

**Comment by czczup** [comment]
ok, 找到原因了，请升级transformers到4.37.2
