### ISSUE TITLE
windows ：ImportError: flash_attn is not installed

### ISSUE THREAD

**Issue by yunzhichen** [OpenGVLab/InternVL#197]
windows 下使用demo程序，本地加载模型库，运行一直报错：
    raise ImportError('flash_attn is not installed.')
ImportError: flash_attn is not installed.
通过 pip install flash_attn  一直无法安装成功
请问如何解决？

**Comment by htian01** [comment]
For flash attention in windows, please follow the Instruction in https://github.com/Dao-AILab/flash-attention. 
It might be tough to run with flash attention in windows.

**Comment by czczup** [comment]
可以不使用flash attention来运行模型，如果是InternVL-Chat-V1-5这个模型的话，在下载下来的模型文件里，把config.json中的"attn_implementation": "flash_attention_2"改成"eager"，就可以关掉flash attention。

<img width="766" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/7091a12b-1192-4785-97ce-afbf2c004bbf">

**Comment by humphreyde** [comment]
> 可以不使用flash attention来运行模型，如果是InternVL-Chat-V1-5这个模型的话，在下载下来的模型文件里，把config.json中的"attn_implementation": "flash_attention_2"改成"eager"，就可以关掉flash attention。
> 
> <img alt="image" width="766" src="https://private-user-images.githubusercontent.com/23737120/335210228-7091a12b-1192-4785-97ce-afbf2c004bbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTE1MTMsIm5iZiI6MTcyMjkxMTIxMywicGF0aCI6Ii8yMzczNzEyMC8zMzUyMTAyMjgtNzA5MWExMmItMTE5Mi00Nzg1LTk3Y2UtYWZiZjJjMDA0YmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAyMjY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDBlZjBjNmI2ZWZkNmRmYTJkZjZkYTIwMmFiY2ExZTc5MDEwOTRiMDRlNzdiOGQ4NWJmYmQzYjM5YmRlYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8z62EF7ZSSrsRJQrx-W572CXzJxZGdwvJott4dzVHWE">

你好，如果是internvl2-8b呢，改了这个好像没有用
