### ISSUE TITLE
AttributeError: 'InternVLChatModel' object has no attribute 'batch_chat'

### ISSUE THREAD

**Issue by longgb246** [OpenGVLab/InternVL#200]
```
      3 prompts = ['帮我提取图中的信息，以json的格式直接返回内容'] * len(image_counts)
      4 responses = model.batch_chat(tokenizer, pixel_values,
      5                              image_counts=image_counts,
      6                              questions=prompts,
      7                              generation_config=generation_config)
```

File /usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py:1688, in Module.__getattr__(self, name)
   1686     if name in modules:
   1687         return modules[name]
-> 1688 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'InternVLChatModel' object has no attribute 'batch_chat'

你好，请问一下，使用官网给的例子报错了，没有 batch_chat 这个是什么原因呢？

**Comment by czczup** [comment]
请问您加载的是`OpenGVLab/InternVL-Chat-V1-5`这个模型吗，现在这个模型里面是有batch_chat这个接口的，见这里：
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5/blob/main/modeling_internvl_chat.py#L232
