### ISSUE TITLE
Infer InternVL 1.5 without Image not work.

### ISSUE THREAD

**Issue by Liac-li** [OpenGVLab/InternVL#202]
我用了 Hugging Face 中提供的代码实例
```
# single-round single-image conversation
question = "请详细描述图片" # Please describe the picture in detail
response = model.chat(tokenizer, pixel_values, question, generation_config)
print(question, response)
```
并且尝试把其中的 `pixel_values 赋值为 None。类似 llava 一样进行无图推理，但是不能运行。请问有别的方法让 InternVL1.5 进行无图推理吗？

----------------------------
I try to use InternVL1.5 to do inference without Image, like llava model. I copy the demo code from the HuggingFace Repository:
```
# single-round single-image conversation
question = "请详细描述图片" # Please describe the picture in detail
response = model.chat(tokenizer, pixel_values, question, generation_config)
print(question, response)`
并且尝试把其中的 `pixel_values
```
And try to give None to pixel_values, but the model is not support it. Is there any other method to make InternVL1.5 do inference without Image?

**Comment by HuangZhen02** [comment]
same issue~

**Comment by czczup** [comment]
您好，现在纯文本对话已经支持了，您可以看这里：https://internvl.readthedocs.io/en/latest/internvl2.0/quick_start.html#inference-with-transformers

里面的# pure-text conversation (纯文本对话) 部分：

<img width="866" alt="image" src="https://github.com/user-attachments/assets/af4765dc-365a-475d-bc4b-caae163c7c8e">
