### ISSUE TITLE
how many gpus and how long time does it cost for V1-5 model finetuning?

### ISSUE THREAD

**Issue by cyj95** [OpenGVLab/InternVL#205]
internvl_chat/shell/internlm2_20b_dynamic/internvl_chat_v1_5_internlm2_20b_dynamic_res_finetune.sh

how many gpus are need for finetuning?

I noticed that for 1-2 version:
Note: fine-tune the full LLM needs 16 A100 80G GPUs, and fine-tune the LoRA needs 2 A100 80G GPUs.

how about  V1-5 model finetuning ?
and how long time will it spend?

**Comment by Felix0805** [comment]
I finetune V1.5 model with 16 A100 80G GPUs and get an out-of-memory error.

**Comment by njzfw1024** [comment]
> internvl_chat/shell/internlm2_20b_dynamic/internvl_chat_v1_5_internlm2_20b_dynamic_res_finetune.sh
> 
> how many gpus are need for finetuning?
> 
> I noticed that for 1-2 version: Note: fine-tune the full LLM needs 16 A100 80G GPUs, and fine-tune the LoRA needs 2 A100 80G GPUs.
> 
> how about V1-5 model finetuning ? and how long time will it spend?

depend on yours config, if you use 2*a100-80g, one epoch, and other configs are default, maybe cost few hours

**Comment by Weiyun1025** [comment]
The GPU requirements for fine-tuning the V1-5 model are similar to those for the V1-2 model. Additionally, training with 1 million samples takes about 10 hours.
