### ISSUE TITLE
多图推理的最大分辨率问题

### ISSUE THREAD

**Issue by zhangye0402** [OpenGVLab/InternVL#206]
在官方给出的demo中，使用了example文件夹下的image1以及image2，可以顺利进行multi-image conversation
但如果简单将image1、2换成image4、5，模型就只能识别到其中的一张图片，查看分辨率发现image4的分辨率达到了1920x1200,而image2的1000x1000分辨率就不会出现问题。
<img width="683" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/103350812/ae2fc93e-3711-41c0-9b41-67356d5432a4">
想请问下进行multi-image conversation的话，单张图像的分辨率上限是多少呢？同时模型最多可以支持多少张图像的输入呢？
@czczup 谢谢！^_^

**Comment by czczup** [comment]
图像分辨率的上限具体还是看显存的大小，通常来说保证总分辨率小于4K就行了，所有图加在一起不超过800万像素（这里指的是load_image函数处理之后的分辨率，不是图像的原始分辨率），也就是说处理完之后的dynamic ViT batch size不超过40。

**Comment by WangJianQ-cmd** [comment]
我用的是lmdeploy api的形式，先把图片转换成base64格式，请问这样的话，多图的大小该如何确定呀。

**Comment by kar9999** [comment]
> 我用的是lmdeploy api的形式，先把图片转换成base64格式，请问这样的话，多图的大小该如何确定呀。
想请问下lmdeploy api怎么设置多图的openai的对话格式啊，网上只给出了单图的

**Comment by Zhongyihhh** [comment]
请问下想减少显存压力的话，是先把多图图片分辨率调低，还是直接调整max_num好一些？
