### ISSUE TITLE
4090无法运行Int8版本，可以出个Int4量化版本吗？谢谢。

### ISSUE THREAD

**Issue by ysyx2008** [OpenGVLab/InternVL#209]
如题。

研究了两天本地运行Int8版本，但是lmdeploy似乎不支持双卡运行，总是运行在第一张卡上，导致显存溢出报错。

**Comment by ysyx2008** [comment]
也尝试了用lmdeploy自行做int4量化，会出现报错：
![图片](https://github.com/OpenGVLab/InternVL/assets/11251894/81b00584-f04f-4012-a281-335226c34cbc)

**Comment by BIGBALLON** [comment]
@ysyx2008 这个等这几天0.4.2发布了应该就ok了，或者现在拿最新的源码编译

**Comment by ysyx2008** [comment]
> @ysyx2008 这个等这几天0.4.2发布了应该就ok了，或者现在拿最新的源码编译

正在尝试用源码编译，感谢回复！

**Comment by BIGBALLON** [comment]
@ysyx2008 顺便问一句，量化后的模型 相比 量化前，是否推理正常(图+prompt)，是否有精度损失

**Comment by ysyx2008** [comment]
> @ysyx2008 顺便问一句，量化后的模型 相比 量化前，是否推理正常(图+prompt)，是否有精度损失

还没搞成功。。。T_T

精度一定有损失的，不过从经验来看我感觉还是要比用同等体积的小尺寸模型效果要好。

**Comment by rTrQqgH74lc2PT5k** [comment]
@lvhan028 @whai362 @irexyc @czczup
官方是否可以结合最新的lmdeploy，发布一个官方的量化4bit版本模型，供大家下载使用，这样就不用每个人都去走量化流程了。

**Comment by czczup** [comment]
lmdeploy的同学已经准备的差不多了，估计快发布了

**Comment by czczup** [comment]
在这：https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ

**Comment by BIGBALLON** [comment]
@czczup @irexyc 方便问下这个模型支持V100推理吗

> 在这：https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ

**Comment by lvhan028** [comment]
> @czczup @irexyc 方便问下这个模型支持V100推理吗
> 
> > 在这：https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5-AWQ

不行。V100下的tensor core和T4、A100比起来，太特殊了，不好支持。LMDeploy 就没有在这个平台下支持 4bit 推理了
