### ISSUE TITLE
依赖包

### ISSUE THREAD

**Issue by sxlyiyiyi** [OpenGVLab/InternVL#213]
请问petrel_client如何安装

**Comment by czczup** [comment]
这个是我们在集群上训练使用的读取数据的包，您在自己的设备上训练的话不需要安装这个。

请问是遇到petrel_client相关的报错了吗

**Comment by KellyZhang2020** [comment]
我也遇到了这个报错，这个报错如何解决呢 @czczup

**Comment by Weiyun1025** [comment]
这个是用来从ceph上读取数据的，如果你们不需要从ceph读数据，只从本地磁盘的话就直接忽略掉这个包就行了
