### ISSUE TITLE
full- parameters fine tune 1-5用4096的max_length显存大概要多少？

### ISSUE THREAD

**Issue by sunzx8** [OpenGVLab/InternVL#214]
想问一下max_length对显存的影响有换算标准吗？

**Comment by Weiyun1025** [comment]
您好，InternVL-1-5是26B的模型，模型参数部分在BF16的情况下显存消耗约50G，考虑到训练时的额外开销，应该需要100～150G，训练时可以通过开启DeepSpeed Zero的方式在不同显卡上分摊这些开销。
