### ISSUE TITLE
在低分辨率图像密集的数据上，动态分辨率策略会带来比较显著的收益吗

### ISSUE THREAD

**Issue by ghntd** [OpenGVLab/InternVL#215]
我现在在一个绝大部分图像数据分辨率都比较低的数据集上进行微调，我发现动态分辨率的训练成本实在是太高了。因此我比较好奇我在低分辨率图像数据上使用动态分辨率策略是否值得。想问一下你们有没有这一方面的试验结论。

**Comment by puffy310** [comment]
Try it and let me know how it goes. :)

**Comment by czczup** [comment]
如果任务本身对分辨率的要求不高，并且图片的原始分辨率也不高，那么用固定的448x448分辨率训练就可以。可以在shell脚本中做以下修改来关闭动态分辨率：
```
--dynamic_image_size False \
--use_thumbnail False \
```

If the task itself does not have high requirements for resolution and the original resolution of the images is also not high, then training with a fixed resolution of 448x448 will suffice. You can make the following modifications in the shell script to disable dynamic resolution:
```
--dynamic_image_size False \
--use_thumbnail False \
```
