### ISSUE TITLE
finetune的时候不加入图片，只训练纯文本对话

### ISSUE THREAD

**Issue by njzfw1024** [OpenGVLab/InternVL#220]
请问有这种的训练集demo样例嘛

**Comment by czczup** [comment]
纯文本数据只需将数据中的'image'字段去掉就好了，或者是image字段为空字符串‘’

可以参考dataloader中的这段处理代码：

<img width="613" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/4a1499bd-219e-4336-a6da-fd4e2ff4ebfb">

**Comment by njzfw1024** [comment]
> 纯文本数据只需将数据中的'image'字段去掉就好了，或者是image字段为空字符串‘’
> 
> 可以参考dataloader中的这段处理代码：
> 
> <img alt="image" width="613" src="https://private-user-images.githubusercontent.com/23737120/335198413-4a1499bd-219e-4336-a6da-fd4e2ff4ebfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzMwMzIsIm5iZiI6MTcxNzEzMjczMiwicGF0aCI6Ii8yMzczNzEyMC8zMzUxOTg0MTMtNGExNDk5YmQtMjE5ZS00MzM2LWE2ZGEtZmQ0ZTJmZjRlYmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA1MTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNDI5ZGM0OTYzYjdlNDNmZDE0ZmQxNTkyMmIzOTMzODU5NTM3MTM1YjNkZTExNmYxZjljMmI1ODQ0MmM0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9KoE8QyVrFk1itYKRxOKsG7Nws2u2pvMM-BrGN4orXE">

感谢，已经解决
