### ISSUE TITLE
模型不支持多(>2)图推理？

### ISSUE THREAD

**Issue by zhangye0402** [OpenGVLab/InternVL#223]
在图像数量超过两张后，模型好像会把所有的输入当作一张图像，从代码看的话，模型似乎把所有分块一起输入给了模型，并没有对不同的图像进行区分，即使使用lmdeploy还是有相同的问题。
想请问下，模型是否能在超过两张图像的情况下进行推理呢，比如让模型分别对六张图像进行描述(448x448)分辨率。

**Comment by czczup** [comment]
现在的模型多图推理效果不稳定，有时候能区分，因为训练的时候没有使用多图的数据；我们计划6月再开源一个加上多图数据进行训练的模型

**Comment by czczup** [comment]
现在的V1.5模型没有用这样的(交错)数据训练，改一下推理接口可以支持，不过效果不稳定；

6月版本会加上多图交错训练，应该会有所改善，代码也到时候一并支持。

**Comment by dacian7** [comment]
> 现在的模型多图推理效果不稳定，有时候能区分，因为训练的时候没有使用多图的数据；我们计划6月再开源一个加上多图数据进行训练的模型

@czczup 谢谢回复！请问大概什么时候能上线呢，谢谢！

**Comment by liming-ai** [comment]
> > 现在的模型多图推理效果不稳定，有时候能区分，因为训练的时候没有使用多图的数据；我们计划6月再开源一个加上多图数据进行训练的模型
> 
> @czczup 谢谢回复！请问大概什么时候能上线呢，谢谢！

Sme question here. Do you have a specific time to open source the multi-image trained weights?

**Comment by SeanWu999** [comment]
> 现在的模型多图推理效果不稳定，有时候能区分，因为训练的时候没有使用多图的数据；我们计划6月再开源一个加上多图数据进行训练的模型

大佬，多图数据训练的模型搞出来了吗

**Comment by zhangye0402** [comment]
请问新的internVL2是否已经增加了多图的训练数据呢？

**Comment by zhangye0402** [comment]
请问新的internVL2是否已经增加了多图的训练数据呢？ @czczup

**Comment by ret-1** [comment]
@zhangye0402 根据[huggingface](https://huggingface.co/OpenGVLab/InternVL2-26B)上的说明，InternVL已经增加了多图的训练数据。

> InternVL 2.0 is trained with an 8k context window and utilizes training data consisting of long texts, multiple images, and videos, significantly improving its ability to handle these types of inputs compared to InternVL 1.5.

**Comment by czczup** [comment]
> > @zhangye0402 根据[huggingface](https://huggingface.co/OpenGVLab/InternVL2-26B)上的说明，InternVL已经增加了多图的训练数据。
> > > InternVL 2.0 is trained with an 8k context window and utilizes training data consisting of long texts, multiple images, and videos, significantly improving its ability to handle these types of inputs compared to InternVL 1.5.
> 
> 视频是怎么处理的 公开代码了吗 求指路

视频数据的格式见这个文档：https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#video-data

视频处理的代码在：https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L423
