### ISSUE TITLE
Mini-InternVL-Chat-4B-V1-5 没法正常结束

### ISSUE THREAD

**Issue by ljch2018** [OpenGVLab/InternVL#224]
![image](https://github.com/OpenGVLab/InternVL/assets/22562546/51512b0c-c2bc-40a6-bcb2-a92c60f9066e)

测试了多个Case，都有类似的问题。

**Comment by czczup** [comment]
现在在线demo应该好了？我测了一下没遇到这个问题，昨天下午的时候刚部署上，一开始有点bug

**Comment by Mabroukiimen** [comment]
hey, how did you solve this ?
