### ISSUE TITLE
Mini-InternVL-Chat-4B-V1-5 部署失败

### ISSUE THREAD

**Issue by ljch2018** [OpenGVLab/InternVL#225]
python -m internvl.serve.model_worker  --host 0.0.0.0 --controller http://localhost:10000 --port 40001 --worker http://localhost:40001 --model-path ./llm_models/Mini-InternVL-Chat-4B-V1-5

![image](https://github.com/OpenGVLab/InternVL/assets/22562546/10fd1924-aec3-42d3-9cb0-0ed83f8afdf9)
一旦请求，就会出错。

**Comment by MarStarck** [comment]
哎，我也想问这个部署的事，为啥搞得有点复杂，不是一个gradio网页就行了吗

**Comment by czczup** [comment]
> 哎，我也想问这个部署的事，为啥搞得有点复杂，不是一个gradio网页就行了吗

确实是这样，这里偷懒直接用了LLaVA的demo所以比较复杂😂

**Comment by czczup** [comment]
> python -m internvl.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40001 --worker http://localhost:40001 --model-path ./llm_models/Mini-InternVL-Chat-4B-V1-5
> 
> ![image](https://private-user-images.githubusercontent.com/22562546/334777656-10fd1924-aec3-42d3-9cb0-0ed83f8afdf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzU3MjQsIm5iZiI6MTcxNzA3NTQyNCwicGF0aCI6Ii8yMjU2MjU0Ni8zMzQ3Nzc2NTYtMTBmZDE5MjQtYWVjMy00MmQzLTljYjAtMGVkODNmOGFmZGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEzMjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Zjc0MTY4ODZhYWUwMTRmZmZhMTQxMWQ0YWVhYjRlYWU3MjU5ZTdjNjNlMjZhNjQzYzk2NmM4ODM4MzVkODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LS-n39HywsziBKXeB6WE7nYCB92u-PLPAx4In0dilOY) 一旦请求，就会出错。

想问一下这里用的git branch是哪个，可以试试pull到最新的代码

**Comment by sss008800** [comment]
跟其他开源模型比较，这个部署没讲清楚，更不谈一个web_demo就能搞定

**Comment by mi4da** [comment]
我成功了：
# 1.run the command in the `internvl_chat_llava` folder
python -m llava.serve.controller --host 0.0.0.0 --port 10000
# 2.run the command in the `internvl_chat_llava` folder
python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload
# 3.run the command in the `internvl_chat` folder
python -m internvl.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40005 --worker http://localhost:40005 --model-path {原生模型地址或者ft后的}

**Comment by sss008800** [comment]
@mi4da 有发现推理很慢么？给够了显存依然很慢，需要几十秒甚至失败。
