### ISSUE TITLE
prompt格式

### ISSUE THREAD

**Issue by sxlyiyiyi** [OpenGVLab/InternVL#227]
你好，请问在internvl-vl-1.5中，对于bbox的处理格式是怎样的，和1.2的相同吗

**Comment by czczup** [comment]
是的，和1.2相同

**Comment by sxlyiyiyi** [comment]
非常感谢，具体是这种格式吗
`{
  "id": 0,
  "image": "images/5.png",
  "conversations": [
    {
      "from": "human",
      "value": "<image>\nPlease provide the bounding box coordinate of the region this sentence describes: <ref>XXX</ref>"
    },
    {
      "from": "gpt",
      "value": "<ref>XXX</ref><box>[[253, 231, 733, 787]]</box>"
    }
}`

**Comment by czczup** [comment]
是的，是这个格式

**Comment by MVP-D77** [comment]
> 非常感谢，具体是这种格式吗 `{ "id": 0, "image": "images/5.png", "conversations": [ { "from": "human", "value": "<image>\nPlease provide the bounding box coordinate of the region this sentence describes: <ref>XXX</ref>" }, { "from": "gpt", "value": "<ref>XXX</ref><box>[[253, 231, 733, 787]]</box>" } }`

@czczup 想问一下这里面<box>[[253, 231, 733, 787]]</box> 关于box框，里面的数字是否需要进行标准化，因为图片有resize的过程，坐标位置是否需要跟随进行变化，以及如果单一图片动态切成多图输入的话，那这时，box框需要进行操作和处理么，在mini1.5-4b的微调里面没有找到这部分有关的代码，希望得到您的回复，谢谢！

**Comment by liuheng0111** [comment]
> 非常感谢，具体是这种格式吗 `{ "id": 0, "image": "images/5.png", "conversations": [ { "from": "human", "value": "<image>\nPlease provide the bounding box coordinate of the region this sentence describes: <ref>XXX</ref>" }, { "from": "gpt", "value": "<ref>XXX</ref><box>[[253, 231, 733, 787]]</box>" } }`

这种格式253, 231, 733, 787 分别指什么，x1, y1, x2, y2么？是原始图片的坐标框，还是resize之后的坐标框？坐标框是怎么来的

**Comment by lucasjinreal** [comment]
别试了，效果很差，不确定是不是使用不当

**Comment by czczup** [comment]
> > 非常感谢，具体是这种格式吗 `{ "id": 0, "image": "images/5.png", "conversations": [ { "from": "human", "value": "<image>\nPlease provide the bounding box coordinate of the region this sentence describes: <ref>XXX</ref>" }, { "from": "gpt", "value": "<ref>XXX</ref><box>[[253, 231, 733, 787]]</box>" } }`
> 
> 这种格式253, 231, 733, 787 分别指什么，x1, y1, x2, y2么？是原始图片的坐标框，还是resize之后的坐标框？坐标框是怎么来的

是归一化的坐标框，详细说明在这里：https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#grounding-detection-data

**Comment by czczup** [comment]
> 别试了，效果很差，不确定是不是使用不当

请问是什么效果很差呢

**Comment by lucasjinreal** [comment]
输入给定box ，5个人以上就好像不太行

**Comment by czczup** [comment]
> 输入给定box ，3个人以上就好像不太行

建议在做Region-level的QA任务时，还是把框直接画在图上，而不是作为字符串输入

**Comment by lucasjinreal** [comment]
画框的话，画什么颜色，多粗，标什么字，有什么讲究么，人密集的话或者overlap的话，不太确定和直接给box哪个好一点

**Comment by corkiyao** [comment]
> 画框的话，画什么颜色，多粗，标什么字，有什么讲究么，人密集的话或者overlap的话，不太确定和直接给box哪个好一点

请问，后面是过画框了吗？之后效果怎么样？

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
> Hello, what is the format for bbox processing in internvl-vl-1.5? Is it the same as 1.2?

Hi Sir, Is internvl2 chat-40B model giving bounding box for extracted results, How to get this from model. Please share some idea on this. I am using the model for key value pair extraction.
