### ISSUE TITLE
Mini−InternVL−Chat−4B−V1−5推理速度慢

### ISSUE THREAD

**Issue by isongxw** [OpenGVLab/InternVL#235]
我尝试使用Mini−InternVL−Chat−4B−V1−5进行推理，发现单图推理时长是InternVL−Chat−V1−5 25.5B模型的3倍，请问是合理情况吗？
在推理Mini−InternVL−Chat−4B−V1−5时会warning如下，而InternVL−Chat−V1−5则不会warning，是不是因为Mini−InternVL−Chat−4B−V1−5不能有效使用flash-attention的原因？

```
UserWarning: In ps_version 'v1', the height and width have not been swapped back, which results in a transposed image.
  warnings.warn("In ps_version 'v1', the height and width have not been swapped back, "
You are not running the flash-attention implementation, expect numerical differences.
```

**Comment by wuyanzhang** [comment]
> 我尝试使用Mini−InternVL−Chat−4B−V1−5进行推理，发现单图推理时长是InternVL−Chat−V1−5 25.5B模型的3倍，请问是合理情况吗？ 在推理Mini−InternVL−Chat−4B−V1−5时会warning如下，而InternVL−Chat−V1−5则不会warning，是不是因为Mini−InternVL−Chat−4B−V1−5不能有效使用flash-attention的原因？
> 
> ```
> UserWarning: In ps_version 'v1', the height and width have not been swapped back, which results in a transposed image.
>   warnings.warn("In ps_version 'v1', the height and width have not been swapped back, "
> You are not running the flash-attention implementation, expect numerical differences.
> ```

我也遇到这个问题，请问你解决了吗

**Comment by isongxw** [comment]
> > 我尝试使用Mini−InternVL−Chat−4B−V1−5进行推理，发现单图推理时长是InternVL−Chat−V1−5 25.5B模型的3倍，请问是合理情况吗？ 在推理Mini−InternVL−Chat−4B−V1−5时会warning如下，而InternVL−Chat−V1−5则不会warning，是不是因为Mini−InternVL−Chat−4B−V1−5不能有效使用flash-attention的原因？
> > ```
> > UserWarning: In ps_version 'v1', the height and width have not been swapped back, which results in a transposed image.
> >   warnings.warn("In ps_version 'v1', the height and width have not been swapped back, "
> > You are not running the flash-attention implementation, expect numerical differences.
> > ```
> 
> 我也遇到这个问题，请问你解决了吗

没有，通过在配置文件里手动添加配置的方式可以不报这个warning，但是推理速度还是很慢

**Comment by rokopi-byte** [comment]
same here, despite having  ` "use_flash_attn": true`  in ` config.json` , using ` Mini−InternVL−Chat−4B−V1−5`  I have this:

` You are not running the flash-attention implementation, expect numerical differences.`

**Comment by Weiyun1025** [comment]
您好，这个ps_version的warning是可以忽略的，这个是早期迭代时遗留下来的一个小问题，您这边用的时候可以忽略。另外FlashAttn对推理速度和显存占用的影响确实很大，可以尝试把config里的`"attn_implementation": "flash_attention_2"`，改成`"_attn_implementation": "flash_attention_2"`试一下。

**Comment by czczup** [comment]
如果你是在用Mini−InternVL−Chat−4B−V1−5输出中文，速度很慢是正常的，因为这个语言模型是Phi3，它的词表很小，中文的表示效率很低
