### ISSUE TITLE
v1-5 连续推理问题

### ISSUE THREAD

**Issue by xuxiaoxxxx** [OpenGVLab/InternVL#236]
请问一下v1-5假如做连续vqa多模态问答，是不是会出现效果退化问题？

**Comment by Weiyun1025** [comment]
您好，我们做benchmark评测的时候都在单轮对话的setting下测试的，由于现有benchmark普遍专注于单轮对话setting，我们对多轮对话的性能还局限在定性分析。按照我们的定性结果来看，可能会出现轻微退化（例如轮数极多的情况下可能从前几轮里抽答案），但不会很明显。

**Comment by xuxiaoxxxx** [comment]
好的谢谢
