### ISSUE TITLE
请问微调可以支持输入多张图片吗？

### ISSUE THREAD

**Issue by Luccadoremi** [OpenGVLab/InternVL#238]

**Comment by GuanyaZhou1** [comment]
可以自己加，在dataset下的multi_modal_get_item func下改一下就好了

**Comment by czczup** [comment]
现在已经支持啦，您可以按照下面的文档去准备数据并微调：

多图数据格式：https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#multi-image-data
微调指南：https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html

**Comment by Luccadoremi** [comment]
> 现在已经支持啦，您可以按照下面的文档去准备数据并微调：
> 
> 多图数据格式：https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#multi-image-data 微调指南：https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html

纯文本指令数据 和 图片指令数据 可以混合在一起训练吗？
