### ISSUE TITLE
文本检测

### ISSUE THREAD

**Issue by HaoRenkk123** [OpenGVLab/InternVL#239]
您好，很棒的分享，我想测试以下InterVL在ocr方面的能力，请问InternVL-Chat-V1-5是强支持ocr的模型对吧，那测试在文本数据上的文本检测和文本识别能力，有特别的prompt吗

**Comment by mi4da** [comment]
我更想知道如何端到端训练2B的那个vlm

**Comment by Weiyun1025** [comment]
你好，我们训练的时候为了保证模型对不同指令的跟随能力，没有使用固定的prompt，您可以用“请识别图中所有文字，并输出坐标框”或者“请识别图中所有文字，并输出对应的坐标框”来测试

**Comment by sxlyiyiyi** [comment]
> 你好，我们训练的时候为了保证模型对不同指令的后续能力，没有使用固定的提示，您可以用“请识别所有文字，并输出坐标框”或者“请识别所有文字，并输出”对应的坐标框”来测试

模型在训练OCR数据时也添加了坐标框吗

**Comment by Weiyun1025** [comment]
是的，一部分OCR训练数据是带框的

**Comment by sxlyiyiyi** [comment]
> 是的，一部分OCR训练数据是带框的

请问是什么格式呢，也是<bbox>[[x0,y0,x1,x2]]<bbox>这样的格式吗，文本后面直接跟着框吗

**Comment by Weiyun1025** [comment]
类似`<ref>{文字内容}</ref><box>[[x1, y1, x2, y2]]</box>`这样的格式

**Comment by sxlyiyiyi** [comment]
> <

文字内容的中括号是没有的吧，是这样的吗`<ref>文本1</ref><box>[[x1, y1, x2, y2]]</box>\n<ref>文本2</ref><box>[[x1, y1, x2, y2]]</box>...`，和检测的数据格式是一样的吗

**Comment by sxlyiyiyi** [comment]
> 类似`<ref>{文字内容}</ref><box>[[x1, y1, x2, y2]]</box>`这样的格式

文字内容的中括号是没有的吧，是这样的吗：`<ref>文本1</ref><box>[[x1, y1, x2, y2]]</box>\n<ref>文本2</ref><box>[[x1, y1, x2, y2]]</box>...`，和检测的数据格式是一样的吗

**Comment by Weiyun1025** [comment]
是的，是这个格式

> > 类似`<ref>{文字内容}</ref><box>[[x1, y1, x2, y2]]</box>`这样的格式
> 
> 文字内容的中括号是没有的吧，是这样的吗：`<ref>文本1</ref><box>[[x1, y1, x2, y2]]</box>\n<ref>文本2</ref><box>[[x1, y1, x2, y2]]</box>...`，和检测的数据格式是一样的吗

**Comment by xylcbd** [comment]
> 是的，是这个格式
> 
> > > 类似`<ref>{文字内容}</ref><box>[[x1, y1, x2, y2]]</box>`这样的格式
> > 
> > 
> > 文字内容的中括号是没有的吧，是这样的吗：`<ref>文本1</ref><box>[[x1, y1, x2, y2]]</box>\n<ref>文本2</ref><box>[[x1, y1, x2, y2]]</box>...`，和检测的数据格式是一样的吗

我测试了一下，坐标框很不准确，偏差很大，有什么建议吗？
