### ISSUE TITLE
flash-attn install problems

### ISSUE THREAD

**Issue by ZQSIAT** [OpenGVLab/InternVL#24]
1. GCC>=6.0
2. Without module dropout_layer_norm, see URL:  https://github.com/Dao-AILab/flash-attention/issues/587#issuecomment-1773565555

**Comment by ZQSIAT** [comment]
3. 'NoneType' FusedMLP, see $"cd flash-attention/csrc/fused_dense_lib && TORCH_CUDA_ARCH_LIST="3.7;5.0;6.0;7.0;7.5;8.0;8.6+PTX" python -m pip install ."

**Comment by czczup** [comment]
Hi, are you having trouble installing flash attention?

**Comment by ZQSIAT** [comment]
This issue can be closed. @czczup

**Comment by czczup** [comment]
Ok, thanks for your advice!
