### ISSUE TITLE
关于预训练数据的处理问题

### ISSUE THREAD

**Issue by GYxiaOH** [OpenGVLab/InternVL#241]
你好，上次跟您交流UHD之后我们尝试在llava 1.5中加入切片的想法，发现基本对比原始效果提升不明显。感觉和数据处理有关系，想了解下，你们预训练数据如何处理的。
1. 小于448的图片是否直接不要了？
2. 论文中所示的数据集没有标识数据量，大概用了多少？ 比如coyo有700m是都用了吗？ 还是用clip清洗了下？
3. OCR数据是怎么处理的，类似于图片-》”这张图片的文字内容有“”“类似于这样吗

**Comment by Weiyun1025** [comment]
感谢您对我们工作的关注

1. 我们没有针对图像分辨率进行额外过滤
2. 我们实际用的数据大概在200M左右，并没有完整过完一个epoch
3. OCR数据我们会整理成多轮对话格式，而不是续写格式

**Comment by xiaohuicomeon** [comment]
> 感谢您对我们工作的关注
> 
> 1. 我们没有针对图像分辨率进行额外过滤
> 2. 我们实际用的数据大概在200M左右，并没有完整过完一个epoch
> 3. OCR数据我们会整理成多轮对话格式，而不是续写格式

我理解多轮对话应该会涉及到文本框坐标，这样额外引入grounding之后最终效果会比完整续写的效果会更好一些么？想请问下OCR数据多轮对话和续写的差异大概会有多少哇？

**Comment by czczup** [comment]
数据格式的文档准备好了，包括纯文本、单图（包括检测/grounding）、多图（交错）、视频数据的格式：https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#grounding-detection-data
