### ISSUE TITLE
如何Merge lora微调后的权重？

### ISSUE THREAD

**Issue by McCarthyjfq** [OpenGVLab/InternVL#242]
我使用了swift库但是merge之后的结果好像是原模型的权重，没有把lora merge进去，请问有没有大佬有什么办法，谢谢！

**Comment by McCarthyjfq** [comment]
希望可以出一个全套的1.5版本lora微调和merge的教程，will be very helpful， 感谢你们的贡献！

**Comment by njzfw1024** [comment]
有同样的问题，希望有大佬能够指导一下

**Comment by SeanWu999** [comment]
> 我使用了swift库但是merge之后的结果好像是原模型的权重，没有把lora merge进去，请问有没有大佬有什么办法，谢谢！

请问swift库是怎么merge的，老是报错误

**Comment by njzfw1024** [comment]
> > 我使用了swift库但是merge之后的结果好像是原模型的权重，没有把lora merge进去，请问有没有大佬有什么办法，谢谢！
> 
> 请问swift库是怎么merge的，老是报错误

我测了是，lora微调后，不需要merge，直接使用就行。

**Comment by sxlyiyiyi** [comment]
> 我使用了swift库但是merge之后的结果好像是原模型的权重，没有把lora merge进去，请问有没有大佬有什么办法，谢谢！

大佬可以merge了吗

**Comment by McCarthyjfq** [comment]
我已经用swift库merge成功了，如果要用swift的话必须从头到尾都用swift，从微调到merge都用swift（推理可以用官方文件），具体就看swift的description就行，数据集可能要根据swift的要求做一点小修改
