### ISSUE TITLE
Is the larger VFM really necessary？For example 『1B VFM + 11B LLM』vs 『6B VFM + 6B LLM』，which is better for training？

### ISSUE THREAD

**Issue by guangdongliang** [OpenGVLab/InternVL#245]

**Comment by Weiyun1025** [comment]
We argue that a larger VFM is necessary. According to our experimental results, a larger VFM represents stronger visual perception and OCR capabilities. For example, in OCRBench, our InternVL2 is the first model to break the 800-point mark, which is a benefit of the larger VFM.

It is worth noting that for models with 12 billion parameters, we recommend using a 1B+11B configuration to ensure balanced GPU load during training. However, for models with 40 billion or more parameters, we suggest using a 6B VFM, as this configuration achieves better performance while maintaining balanced GPU load.
