### ISSUE TITLE
AttributeError: model'transformers_modules. configuration_internvl_chat 'has no attribute' InternVLChatConfiguration '

### ISSUE THREAD

**Issue by xylovezxy** [OpenGVLab/InternVL#247]
Hello, I ran the inference demo of the int8 version model on an A100 and encountered the following error. How should I solve it? AttributeError: model'transformers_modules. configuration_internvl_chat 'has no attribute' InternVLChatConfiguration '

**Comment by czczup** [comment]
Has this issue been resolved?
