### ISSUE TITLE
InternVL1.5 finetune

### ISSUE THREAD

**Issue by cyj95** [OpenGVLab/InternVL#251]
InternVL/internvl_chat/shell/internlm2_20b_dynamic
/internvl_chat_v1_5_internlm2_20b_dynamic_res_finetune.sh

有没有不用srun跑的版本？不是root用户无法安装srun相关的slurm-client

**Comment by cyj95** [comment]
or is there any guide on how to install and use"srun"? which version?

**Comment by njzfw1024** [comment]
请问目前有合适的解决方法了嘛

**Comment by tdye24** [comment]
> 请问目前有合适的解决方法了嘛

同问

**Comment by tdye24** [comment]
Is it right?
```sh
set -x

GPUS=${GPUS:-2}
BATCH_SIZE=${BATCH_SIZE:-16}
PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-4}
GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))


export PYTHONPATH="${PYTHONPATH}:$(pwd)"
export MASTER_PORT=34229
export TF_CPP_MIN_LOG_LEVEL=3
export LAUNCHER=pytorch


OUTPUT_DIR='work_dirs/ours_new'

if [ ! -d "$OUTPUT_DIR" ]; then
 mkdir -p "$OUTPUT_DIR"
fi

# number of gpus: 2
# batch size per gpu: 4
# gradient accumulation steps: 2
# total batch size: 16
# epoch: 1
torchrun \
 --nnodes=1 \
 --node_rank=0 \
 --master_addr=127.0.0.1 \
 --nproc_per_node=${GPUS} \
 --master_port=${MASTER_PORT} \
 ${SRUN_ARGS} \
 internvl/train/internvl_chat_finetune.py \
 --model_name_or_path "pretrained/Mini-InternVL-Chat-4B-V1-5" \
 --conv_style "phi3-chat" \
 --output_dir ${OUTPUT_DIR} \
 --meta_path "shell/data/ours.json" \
 --overwrite_output_dir True \
 --force_image_size 448 \
 --max_dynamic_patch 12 \
 --down_sample_ratio 0.5 \
 --drop_path_rate 0.1 \
 --pad2square False \
 --freeze_llm False \
 --freeze_mlp False \
 --freeze_backbone False \
 --vision_select_layer -1 \
 --use_data_resampling False \
 --dataloader_num_workers 4 \
 --bf16 True \
 --num_train_epochs 1 \
 --per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
 --gradient_accumulation_steps ${GRADIENT_ACC} \
 --evaluation_strategy "no" \
 --save_strategy "steps" \
 --save_steps 200 \
 --save_total_limit 3 \
 --learning_rate 4e-5 \
 --weight_decay 0.05 \
 --warmup_ratio 0.03 \
 --lr_scheduler_type "cosine" \
 --logging_steps 1 \
 --max_seq_length 8192 \
 --do_train True \
 --grad_checkpoint True \
 --group_by_length True \
 --dynamic_image_size True \
 --use_thumbnail True \
 --deepspeed "zero_stage1_config.json" \
 --report_to "tensorboard" \
 2>&1 | tee -a "${OUTPUT_DIR}/training_log.txt"
```

**Comment by HaoRenkk123** [comment]
请问这个finetune脚本只适用于Mini版吗，适用于InternVL-Chat-V1-5版不

**Comment by njzfw1024** [comment]
> 请问这个finetune脚本只适用于Mini版吗，适用于InternVL-Chat-V1-5版不

  8*80G 显存不够，chat1-5得最起码得16*80g吧

**Comment by HaoRenkk123** [comment]
微调Mini-InternVL-Chat-4B-V1-5模型出现大量warning: tokenization mismatch:
<img width="812" alt="企业微信截图_17206082127421" src="https://github.com/OpenGVLab/InternVL/assets/33349843/c51413e7-4283-4931-9d1a-d3ecf9e67cae">

**Comment by HaoRenkk123** [comment]
请问conv_style要设置为phi3-chat吗，我微调的模型为Mini-InternVL-Chat-4B-V1-5，但是设置的conv_style是internlm2-chat，不清楚是不是这个原因导致大量的mismatch警告

**Comment by czczup** [comment]
InternVL 1.5和InternVL 2.0的微调脚本和文档都已经release了，大家可以试试看～

InternVL 1.5 微调文档：https://internvl.readthedocs.io/en/latest/internvl1.5/finetune.html
InternVL 1.5 微调脚本：https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/shell/internvl1.5/2nd_finetune

InternVL 2.0 微调文档：https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html
InternVL 2.0 微调脚本：https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/shell/internvl2.0/2nd_finetune

**Comment by Purshow** [comment]
> 微调Mini-InternVL-Chat-4B-V1-5模型出现大量warning: tokenization mismatch: <img alt="企业微信截图_17206082127421" width="812" src="https://private-user-images.githubusercontent.com/33349843/347369303-c51413e7-4283-4931-9d1a-d3ecf9e67cae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDA4MTcsIm5iZiI6MTcyOTQ0MDUxNywicGF0aCI6Ii8zMzM0OTg0My8zNDczNjkzMDMtYzUxNDEzZTctNDI4My00OTMxLTlkMWEtZDNlY2Y5ZTY3Y2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE2MDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NTUwMTZiNDEzNzNlOGRiNTUzOGQyZTUyMDA0YTViYjhhZGQ3OWViMGMzN2UyOTQyZDcyOWU1ZmM4OWEyNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GsQm34_ArocUvtCg9HUz9tSRZ9RUeV2BXROytwkVCUY">

您好，请问您解决了吗？
