### ISSUE TITLE
lora微调

### ISSUE THREAD

**Issue by sxlyiyiyi** [OpenGVLab/InternVL#258]
请问，对internVL 1.5进行lora微调后，如何加载微调的参数进行推理

**Comment by zhouxiqin2017** [comment]
想问一下您这边是修改了源码吗，源码好像没有lora微调

**Comment by feihuamantian** [comment]
> 请问，对internVL 1.5进行lora微调后，如何加载微调的参数进行推理

有找到方法吗

**Comment by czczup** [comment]
现在可以按照这个文档进行lora微调：https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html
