### ISSUE TITLE
请问OpenGVLab/InternVL-Chat-V1-5的最大上下文窗口是多少？

### ISSUE THREAD

**Issue by ryangsun** [OpenGVLab/InternVL#259]
找了很多资料，没有找到OpenGVLab/InternVL-Chat-V1-5上下文窗口的官方说明。

**Comment by czczup** [comment]
我们训练时用的上下文窗口是4K，使用的InternLM2-Chat-20B是支持200k上下文窗口的。虽然我们训练多模态只用了4K的上下文窗口，可能是因为语言基座原本的200k上下文，我们测试过在多模态测试时拓展到更长的上下文窗口效果也是不错的。

您可以参考我们在[MM-NIAH](https://github.com/OpenGVLab/MM-NIAH)这个工作中的一些大海捞针的测试结果。

**Comment by Weiyun1025** [comment]
对于一些比较简单的任务，我们的模型是可以泛化到48～64K这个上下文长度的。

具体结果可以参考[MM-NIAH](https://mm-niah.github.io/)里的这个[leaderboard](https://mm-niah.github.io/#retrieval_text_test_leaderboard)。
我们的模型在检索任务里，对于32K以内的context是可以保证90%以上准确率的，48～64K范围内可以保持80%以上。

**Comment by ArtificialZeng** [comment]
> 我们训练时用的上下文窗口是4K，使用的InternLM2-Chat-20B是支持200k上下文窗口的。虽然我们训练多模态只用了4K的上下文窗口，可能是因为语言基座原本的200k上下文，我们测试过在多模态测试时拓展到更长的上下文窗口效果也是不错的。
> 
> 您可以参考我们在[MM-NIAH](https://github.com/OpenGVLab/MM-NIAH)这个工作中的一些大海捞针的测试结果。

请教下自己微调或做训练，图片大小弄到多少乘以多少合适，谢谢！

**Comment by ArtificialZeng** [comment]
> 请教下自己微调或做训练，图片大小弄到多少乘以多少合适，谢谢！

请教下自己微调或做训练，图片大小弄到多少乘以多少合适，谢谢！

> 对于一些比较简单的任务，我们的模型是可以泛化到48～64K这个上下文长度的。
> 
> 具体结果可以参考[MM-NIAH](https://mm-niah.github.io/)里的这个[leaderboard](https://mm-niah.github.io/#retrieval_text_test_leaderboard)。 我们的模型在检索任务里，对于32K以内的context是可以保证90%以上准确率的，48～64K范围内可以保持80%以上。

请教下自己微调或做训练，图片像素大小弄到多少乘以多少合适，谢谢！

**Comment by czczup** [comment]
训练最大到12个块就差不多了，如果显存有限的话6个块也可以，6个块相当于896x1344的分辨率
