### ISSUE TITLE
dynamic_image_size训练的话，finetune模型能够有visual grounding能力吗

### ISSUE THREAD

**Issue by caidou05** [OpenGVLab/InternVL#262]

**Comment by czczup** [comment]
可以有的，您可以参考我们在RefCOCO上的结果：

https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-evaluation

<img width="839" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/4d3f92d4-80ad-40cc-8d31-2d220a3c9941">

**Comment by 77h2l** [comment]
@czczup 您好，从结果来看InternVL在visual Grounding 任务上的表现很不错，请问如果想要在垂类数据上微调Phrase Grounding的效果，该如何快速高效的产出自定义数据呢，人工给每张图caption的话，太非标准，而且代价也太大了。谢谢！

**Comment by daihuidai** [comment]
@czczup 你好，我想请问下一些问题。按照文档训练了1B的视觉模型，有定位能力，但是模型只能提问<ref>xxx</ref>，当给正常没有目标的图片时提问训练的一些检测目标问题，他同样会给出一些框位置，请问这个模型在问定位问题时能否解决正常图片不输出框位置呢

**Comment by daihuidai** [comment]
@czczup 还想请问下，关于正常图片怎么训练呢？是不是随便一张图提问坐标，模型都会返回一个坐标，不存在没有框的回答。正常图片应该不输出任何定位框坐标，这时应该怎么提问呢？
