### ISSUE TITLE
给出的sft数据中英文的占比很大，是否会导致中文能力的下降？

### ISSUE THREAD

**Issue by rsqai** [OpenGVLab/InternVL#263]
如题，给出的sft图文对数据中英文的占比很大，是否会导致中文能力下降？当需要模型主要处理中文时，是否需要将这些sft图文对转成中文格式，能不能提升中文表现呢？

**Comment by czczup** [comment]
从我个人经验来看，学术VQA数据集不需要翻译，只要有部分的long caption数据有双语版本就可以了。比如我们用了ShareGPT4V / ALLaVA的中文+英文的双语版本。如果继续去翻译，我感觉收益会比较小。

**Comment by ksnzh** [comment]
> 从我个人经验来看，学术VQA数据集不需要翻译，只要有部分的long caption数据有双语版本就可以了。比如我们用了ShareGPT4V / ALLaVA的中文+英文的双语版本。如果继续去翻译，我感觉收益会比较小。

ShareGPT4V中文版本是不是都是各家自己做的啊？我在网上好像没直接搜到有中文版的。
