### ISSUE TITLE
怎么批量识别图片的内容呢

### ISSUE THREAD

**Issue by 15151833668** [OpenGVLab/InternVL#264]
![image](https://github.com/OpenGVLab/InternVL/assets/55008342/194de327-e30b-4211-9445-257e84737311)
我的image标签也给了2个
worker 报错
![image](https://github.com/OpenGVLab/InternVL/assets/55008342/fbc2039a-2d8d-4fe6-9d99-64a7e401dab8)
请问怎么解决

**Comment by mi4da** [comment]
啊？直接用base64作为图像信息token输入？？？不用VFM? 这总token得有多长啊

**Comment by njzfw1024** [comment]
> 啊？直接用base64作为图像信息token输入？？？不用VFM? 这总token得有多长啊

你好，可以给一个VFM的使用样例嘛
