### ISSUE TITLE
Strange image code in image captioning

### ISSUE THREAD

**Issue by MinliangLin** [OpenGVLab/InternVL#265]
Hi,

Thanks for your great work.

I found that InternVL1.5 model sometime output strange code like **sa_1655** when it is asked to describe the image. Do you have any clue how to avoid this?

Here is one example to reproduce the issue. The code I used:

```py
model.chat(
    tokenizer,
    img,
    "Describe the image in details.",
    dict(
        num_beams=1, max_new_tokens=1024, do_sample=False
    ),
)
```

And the pretrained model is downloaded from https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5

The result would be like (Notice the image code **sa_1655**):

```
The image captures a breathtaking aerial view of the San Francisco Bay Area. The vantage point is from the window of an airplane, with the airplane\'s wing visible in the foreground, addin
g a sense of depth and perspective to the scene. The city of San Francisco, with its iconic landmarks, stretches out in the background, nestled between the deep blue waters of the bay and the verda
nt green hills. The sky above is a clear blue, with a few wispy clouds scattered across it, adding to the overall serene atmosphere of the image. The image code "sa_1655" doesn\'t provide additiona
l information about the landmark.
```

The image I used is as below, and it is downloaded from [this website](https://google.github.io/docci/).

![aar_test_04609](https://github.com/OpenGVLab/InternVL/assets/62332477/81397bf7-b4bb-454c-9ba7-3fed9345070c)

**Comment by czczup** [comment]
Hi, thank you very much for your feedback! I will search `sa_1655` in the training dataset and filter out all abnormal data.
