### ISSUE TITLE
demo网站挂了吗？

### ISSUE THREAD

**Issue by ljch2018** [OpenGVLab/InternVL#268]
![image](https://github.com/OpenGVLab/InternVL/assets/22562546/4b55bffe-3838-4ddb-9545-1de9da162484)
![image](https://github.com/OpenGVLab/InternVL/assets/22562546/cfcd818d-bac8-42ec-822c-9ae2cf4d4a83)

**Comment by czczup** [comment]
感谢反馈，demo网站已经修复
