### ISSUE TITLE
为什么不能复现4B参数模型在MathVista数据集上的结果呢？

### ISSUE THREAD

**Issue by shannany0606** [OpenGVLab/InternVL#269]
这是我输入的命令
`nohup torchrun --nproc-per-node=1 run.py --data MathVista_MINI --model Mini-InternVL-Chat-4B-V1-5 --verbose >>output.txt 2>&1 &`
这是我得到的结果
![89a1dfbe-b5d9-40fd-87a5-2acc7e96e445](https://github.com/OpenGVLab/InternVL/assets/73532944/042b20c9-e7b7-4d90-8688-0a98c698fa9e)
为什么会比官方测试结果差15个点呢？

**Comment by HAWLYQ** [comment]
@shannany0606 hello, 请问你复现结果成功了吗，我尝试复现InternVL-Chat-1.5在DocVQA上的结果，也差很多。。。

**Comment by shannany0606** [comment]
> @shannany0606 hello, 请问你复现结果成功了吗，我尝试复现InternVL-Chat-1.5在DocVQA上的结果，也差很多。。。

没有诶

**Comment by czczup** [comment]
需要设置OpenAI的key，使用ChatGPT来抽取答案，你这个点数看着没有使用ChatGPT抽取答案。

可以参考文档的这一部分：https://internvl.readthedocs.io/en/latest/internvl1.2/evaluation.html#mathvista

或者使用VLMEvalKit进行评测（也需要OpenAI的key）:https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html#mathvista

**Comment by luyao-cv** [comment]
你好，请问你这个run.py文件是在哪里呀，我跑的时候会报错找不到run.py文件

**Comment by luyao-cv** [comment]
> 你好，请问你这个run.py文件是在哪里呀，我跑的时候会报错找不到run.py文件
