### ISSUE TITLE
Cannot Input Image When Using lmdeploy API

### ISSUE THREAD

**Issue by jdy18** [OpenGVLab/InternVL#274]
I have the following test code:

```
from lmdeploy.serve.openai.api_client import APIClient

api_client = APIClient('http://127.0.0.1:23333')
model_name = api_client.available_models[0]
messages = [{
    'role': 'user',
    'content': [{
        'type': 'text',
        'text': 'Describe the image please',
    }, 
    {
        'type': 'image_url',
        'image_url': {
            'url': 'https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg',
        },
    }]
}]

for item in api_client.chat_completions_v1(model=model_name, messages=messages):
    print(item)


```

When I include an image in the messages, the model server does not respond. However, it works perfectly when only text input is provided. Could you help me understand why this is happening and how to resolve it?

**Comment by ErfeiCui** [comment]
If you encounter any issues or need advanced usage with lmdeploy, we recommend reading the lmdeploy documentation (https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html).
