### ISSUE TITLE
Why eval() for llm?

### ISSUE THREAD

**Issue by geweihgg** [OpenGVLab/InternVL#277]
code：https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_pretrain.py#L597

snapshot：
![image](https://github.com/OpenGVLab/InternVL/assets/18585014/2ef58fb9-5c4d-4027-aa9b-52978f97c9bd)

question:
why using eval() for llm? and not for vit? If I don't use eval() method for both model, will I get a more worse result?

**Comment by czczup** [comment]
This is a little trick during training. Overfitting can be mitigated by using the drop path inside the ViT even when the ViT is frozen.

**Comment by czczup** [comment]
If the ViT is not opened for training during the fine-tuning stage, it is still beneficial to set a non-zero drop path. In our experiments, this approach performed better than setting the drop path to zero. Naturally, opening the ViT and using the drop path yields the best results.
