### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by hjklearn** [OpenGVLab/InternVL#278]
When I run 'Model Usage (Image Embeddings) ':

import torch
from PIL import Image
from transformers import AutoModel, CLIPImageProcessor
model = AutoModel.from_pretrained(
    'OpenGVLab/InternViT-300M-448px',
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True).cuda().eval()
image = Image.open('./examples/image1.jpg').convert('RGB')
image_processor = CLIPImageProcessor.from_pretrained('OpenGVLab/InternViT-300M-448px')
pixel_values = image_processor(images=image, return_tensors='pt').pixel_values
pixel_values = pixel_values.to(torch.bfloat16).cuda()
outputs = model(pixel_values)

 it generates the following error: Floating point exception (core dumped)

**Comment by josephzpng** [comment]
hello! I also have the same problem, have you solved it?

**Comment by h66840** [comment]
It may be that your cuda version is too old, my cuda version 11.1 also had this error, replaced by 11.8 to solve the problem

**Comment by czczup** [comment]
> It may be that your cuda version is too old, my cuda version 11.1 also had this error, replaced by 11.8 to solve the problem

That might be the reason. My CUDA version is 11.8.

**Comment by Leo-Lsc** [comment]
为什么我的CUDA版本是12.5也会出现这个问题？只能CUDA11.8吗？

**Comment by happyday-lkj** [comment]
ubuntu22.04, cuda12.1 以及cuda11.8都出现一样的问题，请问有人知道怎么解决吗

**Comment by zhangjiannan1** [comment]
Does anyone fix this problem?
