### ISSUE TITLE
why only train mlp in 4B pretraining stage?

### ISSUE THREAD

**Issue by geweihgg** [OpenGVLab/InternVL#279]
reference code：https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/phi3_3_8b_dynamic/internvl_chat_v1_5_phi3_3_8b_dynamic_res_pretrain.sh#L53

We note that when training 1.8B model, vit and mlp are unfreezed, but for 4B model, only mlp is unfreezed in pretraining stage. Is there any consideration?

**Comment by czczup** [comment]
Hi, thank you for your attention. When training the 4B model, we reused the ViT pretrained on the 2B model, which can reduce the training resource overhead.
