### ISSUE TITLE
InternVL-Chat-V1-5微调bounding box框处理方式

### ISSUE THREAD

**Issue by againcui** [OpenGVLab/InternVL#285]
请教各位老师：
InternVL-Chat-V1-5在微调指示问答操作时候，标注的数据边界框是需要归一化操作么，是需要将标注后的图片归一化成1000*1000的值么

**Comment by czczup** [comment]
是的，框要这样归一化。对于COCO原本的[x, y, w, h]格式的数据，我们会做如下的转换：

```python
x, y, w, h = bbox
x1, y1, x2, y2 = x, y, x+w, y+h
x1 = int(x1 / width * 1000)
y1 = int(y1 / height * 1000)
x2 = int(x2 / width * 1000)
y2 = int(y2 / height * 1000)
bbox = [x1, y1, x2, y2]
```

**Comment by againcui** [comment]
> 是的，框要这样归一化。对于COCO原本的[x, y, w, h]格式的数据，我们会做如下的转换：
> 
> ```python
> x, y, w, h = bbox
> x1, y1, x2, y2 = x, y, x+w, y+h
> x1 = int(x1 / width * 1000)
> y1 = int(y1 / height * 1000)
> x2 = int(x2 / width * 1000)
> y2 = int(y2 / height * 1000)
> bbox = [x1, y1, x2, y2]
> ```

收到，非常感谢您
