### ISSUE TITLE
InternVL-Chat-V1-5微调复读机情况

### ISSUE THREAD

**Issue by againcui** [OpenGVLab/InternVL#286]
请教各位老师：
       我采用swift微调后会出现严重的复读机情况，InternVL-Chat-V1-5模型的截止词是采用的</s>么，看swift给的是<|img_end|>，会是这个造成的么

**Comment by situguaiwu** [comment]
请问，你在微调的时候用了几张卡，都是什么型号的呀，运行到train的时候遇到过卡住崩溃的问题吗

**Comment by againcui** [comment]
> 请问，你在微调的时候用了几张卡，都是什么型号的呀，运行到train的时候遇到过卡住崩溃的问题吗

8卡的A100，不会卡住的

**Comment by czczup** [comment]
InternLM2-Chat-20B的截止词是<|im_end|>

**Comment by againcui** [comment]
> InternLM2-Chat-20B的截止词是<|im_end|>

不好意思老师，是我打错了，我用的是<|im_end|>，一微调后这个截止词就不起作用了，后面就会生成好多个<|im_end|>，类似的效果就是这样<|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|><|im_end|>... ...好多个

**Comment by tukixian** [comment]
您好，请问您微调InternVL-Chat-V1-5是不是Mini版本，我看目前V1-5只提供了[Mini-InternVL-Chat-2B-V1-5]和[Mini-InternVL-Chat-4B-V1-5]在定制数据集上的微调方法呀。
<img width="1017" alt="internvl-chat" src="https://github.com/OpenGVLab/InternVL/assets/160988874/3176c3b7-c3c0-416a-af61-c5e5a180d726">

**Comment by againcui** [comment]
> 您好，请问您微调InternVL-Chat-V1-5是不是Mini版本，我看目前V1-5只提供了[Mini-InternVL-Chat-2B-V1-5]和[Mini-InternVL-Chat-4B-V1-5]在定制数据集上的微调方法呀。 <img alt="internvl-chat" width="1017" src="https://private-user-images.githubusercontent.com/160988874/341323705-3176c3b7-c3c0-416a-af61-c5e5a180d726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzE4NTksIm5iZiI6MTcxODg3MTU1OSwicGF0aCI6Ii8xNjA5ODg4NzQvMzQxMzIzNzA1LTMxNzZjM2I3LWMzYzAtNDE2YS1hZjYxLWM1ZTVhMTgwZDcyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwODE5MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmRkOGZmZTFlNGU2MTkwYzJmODE1Y2E0OWFmZGI0YWFhZGJkZDNhNTRkNTNhYWMzMDUxOTUyMTQ3Nzg1MDkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G2RzqdNDRNC5KwjoNgj0DRLAGJrKS_kV5TgJQ7B_oWQ">

没有用Mini版本，用的https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5这个

**Comment by againcui** [comment]
> 您好，请问您微调InternVL-Chat-V1-5是不是Mini版本，我看目前V1-5只提供了[Mini-InternVL-Chat-2B-V1-5]和[Mini-InternVL-Chat-4B-V1-5]在定制数据集上的微调方法呀。 <img alt="internvl-chat" width="1017" src="https://private-user-images.githubusercontent.com/160988874/341323705-3176c3b7-c3c0-416a-af61-c5e5a180d726.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzMyMDAsIm5iZiI6MTcxODg3MjkwMCwicGF0aCI6Ii8xNjA5ODg4NzQvMzQxMzIzNzA1LTMxNzZjM2I3LWMzYzAtNDE2YS1hZjYxLWM1ZTVhMTgwZDcyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQwODQxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjA3ZmFkZDNmOTIzYjcyMDRmMDk2NDM4NDU4YzA1M2M4MDczN2EzZDUyNWU4ZjExMjhjMWY4NTkxZmYwYzQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WmIleGvrpqSh06AosMo1Lxxlu4MFPqShcuR_B6XLzjk">

用swift架构调的

**Comment by brooks0519** [comment]
同样的问题，@againcui 大佬解决了吗？

**Comment by dacian7** [comment]
> 同样的问题，@againcui 大佬解决了吗？

@brooks0519 你现在解决了吗？

**Comment by czczup** [comment]
目前新的文档已经准备好了：

InternVL 1.5的微调指南：https://internvl.readthedocs.io/en/latest/internvl1.5/finetune.html
InternVL 2.0的微调指南：https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html
