### ISSUE TITLE
输出结果出现[UNUSED_TOKEN_145]然后开始胡言乱语

### ISSUE THREAD

**Issue by Qinger27** [OpenGVLab/InternVL#289]
<img width="1162" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/73786265/431152d7-8bc3-4bd5-a9b3-cbc0e11d53ba">
请问有办法解决这个问题吗？

**Comment by czczup** [comment]
您好，这个问题是因为transformers的版本旧了一点，请使用transformers==4.37.2
