### ISSUE TITLE
eval resullts on video benchmarks

### ISSUE THREAD

**Issue by Quan-Sun** [OpenGVLab/InternVL#29]
Hi there,

Congratulations on your impressive work! I have a question regarding the evaluation results on video benchmarks. I performed zero-shot evaluations on Kinetics-400/600/700 using the middle frame, following [vissl](https://github.com/facebookresearch/vissl/blob/main/extra_scripts/datasets/create_k700_data_files.py). However, I noticed differences between my results and those reported in the paper, particularly the average accuracy of 71.0, 71.3, and 65.7 for  Kinetics-400/600/700.

<img width="478" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/34995468/0f6d4566-abf9-491c-8d14-96faa9d16774">

**Comment by czczup** [comment]
Hello, it might be because the codebase used for testing is different from EVA, and some settings are not aligned. I will check it and then correct these results.

**Comment by czczup** [comment]
We have replaced the results in the images in all the README, and the results in the paper will be corrected in the next update. Thanks again for your feedback.
