### ISSUE TITLE
识别图片出现 输出结果 乱码问题

### ISSUE THREAD

**Issue by xiaotaozi121096** [OpenGVLab/InternVL#290]
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5
下载上述文件，按照要求，下载transformers==4.37.2的版本，运行Model Usage中的代码，输出结果乱码

**Comment by Weiyun1025** [comment]
你好，是否可以提供更多信息（例如输出了什么乱码、你实际运行的代码以及使用的环境），来让我们复现这个问题？

**Comment by xiaotaozi121096** [comment]
<img width="730" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/51726643/92d7f898-6aa2-4198-9848-486e8521bde0">
只是修改了模型路径和图片路径，没有做其他修改

**Comment by xiaotaozi121096** [comment]
你好，我只是修改了模型路径和图片路径，然后python .py 启动，没有做其他修改




周高峰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenGVLab/InternVL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月30日(星期天) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenGVLab/InternVL] 识别图片出现 输出结果 乱码问题 (Issue #290)





 
你好，是否可以提供更多信息（例如输出了什么乱码、你实际运行的代码以及使用的环境），来让我们复现这个问题？

**Comment by czczup** [comment]
您好，能否提供一下您的测试图片以及发送给模型的提问
