### ISSUE TITLE
 InternVL-Chat-V1-5  部署 InternVL-Chat-V1-5大概需要多少资源？

### ISSUE THREAD

**Issue by yangtao-git** [OpenGVLab/InternVL#295]
How many resources do I need to deploy InternVL-Chat-V1-5?

**Comment by neverCase** [comment]
just an A800 80G

**Comment by xings19** [comment]
Please refer to: https://internvl.readthedocs.io/en/latest/internvl1.5/deployment.html#memory-usage-testing
