### ISSUE TITLE
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

### ISSUE THREAD

**Issue by NamHuynh1308** [OpenGVLab/InternVL#297]
Hi,

I got this error on running this LLM on Google Colab.
I successfully ran all commands of the controller, model worker, and gradio web server
![448465168_838473454283178_1672246174105765540_n](https://github.com/OpenGVLab/InternVL/assets/89420792/d4bea0b2-b5a1-4c07-9a6b-da599c086463)
![448383226_767870548558052_8850584851673207714_n](https://github.com/OpenGVLab/InternVL/assets/89420792/96a0260e-d9a3-483c-93ca-e6781424ff33)
![448554544_457987363629627_8739025785155437003_n](https://github.com/OpenGVLab/InternVL/assets/89420792/3d6c9d5b-34fc-466a-95b5-cbe0ff675277)

The model successfully pop up on the web server but when I tried to use I still got the error
![448653258_3397016300607933_3338415826527971578_n](https://github.com/OpenGVLab/InternVL/assets/89420792/76798977-e920-43a2-917d-2956de1a7627)

How can I fix this? Thank you!

**Comment by Arthurwyf** [comment]
I have the same problem. Anyone can help?

**Comment by ErfeiCui** [comment]
please refer the latest document:https://internvl.readthedocs.io/en/latest/get_started/local_chat_demo.html
