### ISSUE TITLE
SentencePieceProcessor_LoadFromFile

### ISSUE THREAD

**Issue by hwang136** [OpenGVLab/InternVL#298]
When I tried to execute 
`tokenizer = AutoTokenizer.from_pretrained("/root/app/CustomLLM/InternVL-Chat-V1-5/", trust_remote_code=True)`
it said

> File "/usr/local/python38/lib/python3.8/site-packages/sentencepiece/__init__.py", line 316, in LoadFromFile
>     return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
> RuntimeError: Internal: could not parse ModelProto from /root/app/CustomLLM/InternVL-Chat-V1-5/tokenizer.model

my directory "/root/app/CustomLLM/InternVL-Chat-V1-5/" contains everything except those safetensor files and run directory
![image](https://github.com/OpenGVLab/InternVL/assets/44818410/c5a249c9-e131-4ed2-8ba9-6323f3b3a244)

here is my requirement.txt 
```
fastapi==0.85.1
uvicorn==0.30.1
uvloop==0.19.0
pydantic==1.10.16
gradio==3.41.2
openai
urllib3==1.26.6
langchain==0.2.5
langchain-community==0.2.5
langchain-core==0.2.7
transformers==4.41.2
pie-client-python==1.1.2
torch==2.3.1
pathlib==1.0.1
tenacity
sentencepiece==0.2.0
timm==1.0.3
fastapi-swagger2==0.0.3
opencv-python-headless==4.10.0.82
```
has anyone come across similar issues?

**Comment by czczup** [comment]
Hi, could you try:

tokenizer = AutoTokenizer.from_pretrained("OpenGVLab/InternVL-Chat-V1-5", trust_remote_code=True)

**Comment by czczup** [comment]
Due to the inactivity over the past two weeks, this issue might have already been resolved, so I will close it. If you have any further questions, please feel free to reopen it.
