### ISSUE TITLE
Zeroshot classification results for InternVL-G

### ISSUE THREAD

**Issue by BIGBALLON** [OpenGVLab/InternVL#30]
Hi, Are there any Zeroshot classification (ImageNet) evaluation results for **InternVL-G**?

**Comment by czczup** [comment]
Hello, I can list the results here if you want, but the classification performance of InternVL-G is not improved compared to InternVL-C.

**Comment by BIGBALLON** [comment]
Yes, I'm interested in how it performs on downstream Zeroshot classification tasks.

**Comment by czczup** [comment]
@BIGBALLON This is the result.

| model name | IN-1K | IN-A | IN-R | IN-V2 | IN-Sketch | ObjectNet |  ∆  | average |
| :--------: | :---: | :--: | :--: | :---: | :-------: | :-------: | :-: | :-----: |
| InternVL-C | 83.2  | 83.8 | 95.5 | 77.3  |   73.9    |   80.6    | 0.8 |  82.4   |
| InternVL-G | 82.9 | 82.4 | 95.5 | 77.1  |   73.3    |  79.3    | 1.1 |  81.8   |

**Comment by BIGBALLON** [comment]
@czczup  thanks !!!

**Comment by BIGBALLON** [comment]
> I can list the results here if you want, but the classification performance of InternVL-G is not improved compared to InternVL-C. The main improvement of InternVL-G is retrieval capability.

Hi, @czczup, can you explain why  InternVL-G improved retrieval capability?
