### ISSUE TITLE
在V100微调InternVL-1.5报错RuntimeError: FlashAttention only supports Ampere GPUs or newer.

### ISSUE THREAD

**Issue by Qinger27** [OpenGVLab/InternVL#303]
<img width="1169" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/73786265/2254106e-fd93-4d18-be54-c0a136b72ad1">

想问下怎么在微调时关掉FlashAttention，在模型加载的config.json文件中已经关了"use_flash_attn": false 和"attn_implementation": "eager", 请问微调怎么关掉？

**Comment by Weiyun1025** [comment]
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L492
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L492

代码的这几个位置会在训练时强制开启FlashAttention，可以把这些代码注释掉

**Comment by zhou888888** [comment]
> https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L492 https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L492
> 
> 代码的这几个位置会在训练时强制开启FlashAttention，可以把这些代码注释掉

还是没效果呢

**Comment by jwh97nn** [comment]
pip uninstall flash-attn
