### ISSUE TITLE
推理结果不一致

### ISSUE THREAD

**Issue by lsl0901** [OpenGVLab/InternVL#304]
为什么网页demo演示和本地部署运行的结果性能相差很大，有什么思路吗？

**Comment by sky-fly97** [comment]
有后续解决思路么

**Comment by lsl0901** [comment]
> 有后续解决思路么

在load_image里，我设置了max_num=1, 在调到12后，结果与网页演示相差不多。

**Comment by sky-fly97** [comment]
> > 有后续解决思路么
> 
> 在load_image里，我设置了max_num=1, 在调到12后，结果与网页演示相差不多。



> > 有后续解决思路么
> 
> 在load_image里，我设置了max_num=1, 在调到12后，结果与网页演示相差不多。

感谢~
