### ISSUE TITLE
where is tensorboard log dir

### ISSUE THREAD

**Issue by ff151** [OpenGVLab/InternVL#307]
Where is the log directory in tensorboard after fine tuning internvl-chat?  Can not find the log directory to view training logs in tensorboard. Thanks!

**Comment by Weiyun1025** [comment]
You can find it in the `./work_dirs/${project_name}`

For example, if you run [this script](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/phi3_3_8b_dynamic/internvl_chat_v1_5_phi3_3_8b_dynamic_res_finetune.sh#L19) to finetune our model, you can find the tensorboard log in the `./work_dirs/internvl_chat_v1_5_phi3_3_8b_dynamic_res_finetune`

**Comment by czczup** [comment]
This issue has been inactive for two months, so I am closing it. If you have any further questions or encounter any problems, please feel free to reopen it. Thank you!
