### ISSUE TITLE
 Mini-InternVL-Chat-2B-V1-5和Mini-InternVL-Chat-4B-V1-5有支持端侧部署的计划吗

### ISSUE THREAD

**Issue by Yangfan-96** [OpenGVLab/InternVL#308]
想问下 Mini-InternVL-Chat-2B-V1-5和Mini-InternVL-Chat-4B-V1-5有支持端侧部署的计划吗，例如llama.cpp、mlc-llm这些项目。

**Comment by Single430** [comment]
我看llama.cpp官方项目说正在适配，但具体时间未知

**Comment by czczup** [comment]
有这个适配计划，但由于人手不足，目前还不确定什么时候可以做完
