### ISSUE TITLE
使用 internvl-1.5 微调后的模型文件特别大，请问是正常的吗？

### ISSUE THREAD

**Issue by Qinger27** [OpenGVLab/InternVL#309]
晕，用 internvl-1.5 做 lora 微调，发现存了一个微调后模型就 96G 了，请问这是正常的吗？
为什么比pretrained的模型（69G）还大了一半呀？
如果只保存 lora 部分的参数，应该不会占这么大空间吧？请问有人可以帮忙解答一下吗？

**Comment by dacian7** [comment]
> 晕，用 internvl-1.5 做 lora 微调，发现存了一个微调后模型就 96G 了，请问这是正常的吗？ 为什么比pretrained的模型（69G）还大了一半呀？ 如果只保存 lora 部分的参数，应该不会占这么大空间吧？请问有人可以帮忙解答一下吗？

@Qinger27 应该是把 vision encoder 的参数也保存了？你看下保存了什么

**Comment by Qinger27** [comment]
请问在哪里设置要保存的内容呀？

**Comment by czczup** [comment]
现在代码是把所有参数都保存了一份，包含了原始的权重以及lora的权重，所以比较大
