### ISSUE TITLE
请问怎样使用基于internvl-v1.5 之后的模型文件？

### ISSUE THREAD

**Issue by Qinger27** [OpenGVLab/InternVL#310]
总算使用 internvl- v1.5 做完微调了，非常感谢你们的工作！现在想问下怎么使用微调后的模型呀？使用 transformers 的 AutoModel.from_pretrained 函数加载时报错缺少很多配置文件，我要从 internvl-1.5 那里复制过来吗？怎么确认自己是否使用的是微调后的模型参数呀？

期待好心人的解答～

**Comment by njzfw1024** [comment]
> 总算使用 internvl- v1.5 做完微调了，非常感谢你们的工作！现在想问下怎么使用微调后的模型呀？使用 transformers 的 AutoModel.from_pretrained 函数加载时报错缺少很多配置文件，我要从 internvl-1.5 那里复制过来吗？怎么确认自己是否使用的是微调后的模型参数呀？
> 
> 期待好心人的解答～

从预训练文件中复制过来就行

**Comment by Weiyun1025** [comment]
如果您希望用我们的代码训练完后得到的权重也能通过`AutoModel.from_pretrained`加载的话需要做如下操作：

1. 将[该目录](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/internvl/model/internvl_chat)下的模型结构代码全部复制到ckpt的目录下
2. 将关于internvl的import改成相对路径的import，例如`from internvl.model.internlm2.modeling_internlm2 import InternLM2ForCausalLM`修改为`from .internlm2.modeling_internlm2 import InternLM2ForCausalLM`
3. 在config中添加如下内容：
```ptyhon
  "architectures": [
    "InternVLChatModel"
  ],
  ### 添加以下内容 ###
  "auto_map": {
    "AutoConfig": "configuration_internvl_chat.InternVLChatConfig",
    "AutoModel": "modeling_internvl_chat.InternVLChatModel",
    "AutoModelForCausalLM": "modeling_internvl_chat.InternVLChatModel"
  },
  ### 添加以上内容 ###
  "downsample_ratio": 0.5,
```
4. 将`modeling_intern_vit.py`替换成我们发布出的[`modeling_intern_vit.py`](https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5/blob/main/modeling_intern_vit.py)，否则ViT部分的FlashAttention会存在ImportError

**Comment by czczup** [comment]
> > 总算使用 internvl- v1.5 做完微调了，非常感谢你们的工作！现在想问下怎么使用微调后的模型呀？使用 transformers 的 AutoModel.from_pretrained 函数加载时报错缺少很多配置文件，我要从 internvl-1.5 那里复制过来吗？怎么确认自己是否使用的是微调后的模型参数呀？
> > 期待好心人的解答～
> 
> 从预训练文件中复制过来就行

是的，复制过来就好了
