### ISSUE TITLE
How to evaluate  InternVL-Chat-V1-5 on video benchmark

### ISSUE THREAD

**Issue by royzhang12** [OpenGVLab/InternVL#312]
Hi @czczup,

Thanks for open-sourcing such a wonderful job. The amazing performance on video task is surprising.   Just a quesiton about how to evaluate the intervl-chat-v1-5 on video benchmark such as MVBench, Seed-Video. As I can not find scripts of video evaluation in the repo, would you mind to provide a script or give me some hint, such as how many patch one frame you used for evaluation and how to combine multi-frames(for instance, seperate each frame with <im_strat><im_end> or not ) ?

**Comment by czczup** [comment]
Hello! I recommend using [vlmevalkit](https://github.com/open-compass/VLMEvalKit) for testing video datasets, as it has already integrated InternVL series models and supports Video-MME and MMBench-Video.
