### ISSUE TITLE
Do OpenGVLab have a Dense Video Captioning Model?

### ISSUE THREAD

**Issue by radna0** [OpenGVLab/InternVL#314]
I'm trying to create a dense video captioned dataset with specific character detection, I have seen recently that there were ShareGPT4Video, Vid2Seq from other research institutes. Are there any models OpenGVLab have developed to combat this? I only see that you have developed ShareGPT-4o Dataset.

**Comment by czczup** [comment]
Hello, thank you for your interest in our OpenGVLab. Our recently open-sourced InternVL2 series models support video captioning. You can test them to see if their capabilities meet your requirements.
