### ISSUE TITLE
微调Mini-InternVL-Chat-2B-V1-5需要多少显存？

### ISSUE THREAD

**Issue by Single430** [OpenGVLab/InternVL#317]
你好，目前使用脚本`./shell/internlm2_1_8b_dynamic/internvl_chat_v1_5_internlm2_1_8b_dynamic_res_finetune.sh`进行微调遇到**OOM**问题

配置是 **2 x 4090** 
即使修改**BATCH_SIZE**，**PER_DEVICE_BATCH_SIZE**依旧会**OOM**
所以，请问微调**Mini-InternVL-Chat-2B-V1-5**需要多少显存？ （按照你们文档细节 16 GPUs，不会是需要 16 x A100(80G)吧？）

**Comment by 1SingleFeng** [comment]
> 你好，目前使用脚本`./shell/internlm2_1_8b_dynamic/internvl_chat_v1_5_internlm2_1_8b_dynamic_res_finetune.sh`进行微调遇到**OOM**问题
> 
> 配置是 **2 x 4090** 即使修改**BATCH_SIZE**，**PER_DEVICE_BATCH_SIZE**依旧会**OOM** 所以，请问微调**Mini-InternVL-Chat-2B-V1-5**需要多少显存？ （按照你们文档细节 16 GPUs，不会是需要 16 x A100(80G)吧？）

据我了解，微调8B的模型，全参数微调最少需要8张v100（32GB），lora微调最少需要2张v100（32GB）

**Comment by Single430** [comment]
> > 你好，目前使用脚本`./shell/internlm2_1_8b_dynamic/internvl_chat_v1_5_internlm2_1_8b_dynamic_res_finetune.sh`进行微调遇到**OOM**问题
> 
> > 
> 
> > 配置是 **2 x 4090** 即使修改**BATCH_SIZE**，**PER_DEVICE_BATCH_SIZE**依旧会**OOM** 所以，请问微调**Mini-InternVL-Chat-2B-V1-5**需要多少显存？ （按照你们文档细节 16 GPUs，不会是需要 16 x A100(80G)吧？）
> 
> 
> 
> 据我了解，微调8B的模型，全参数微调最少需要8张v100（32GB），lora微调最少需要2张v100（32GB）

收到，非常感谢。
