### ISSUE TITLE
求助：使用Lmdeploy推理Lora后的InternVL-chat-1-5

### ISSUE THREAD

**Issue by njzfw1024** [OpenGVLab/InternVL#318]
<img width="817" alt="微信图片_20240702111013" src="https://github.com/OpenGVLab/InternVL/assets/130643833/887bcd8a-95bc-4a5a-8a31-85696a476543">

`UnboundLocalError: local variable 'head_num' referenced before assignment`

**Comment by feihuamantian** [comment]
我这边也遇到同样的问题，采用Lora微调Internvl2-26b模型后，报以下错误：
![image](https://github.com/OpenGVLab/InternVL/assets/28010145/c1b12186-9db5-4066-a773-05a1733c9ba4)

**Comment by feihuamantian** [comment]
> <img alt="微信图片_20240702111013" width="817" src="https://private-user-images.githubusercontent.com/130643833/344862565-887bcd8a-95bc-4a5a-8a31-85696a476543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDk2NDYsIm5iZiI6MTcyMDc0OTM0NiwicGF0aCI6Ii8xMzA2NDM4MzMvMzQ0ODYyNTY1LTg4N2JjZDhhLTk1YmMtNGE1YS04YTMxLTg1Njk2YTQ3NjU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwMTU1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2QxZGVhNzFiYzE2NzQ4NTE5MDhmNWQ2ZmZjMjNlMjRkNjc5ZDFlNGM5Njc3NGRiOTUzZTZhZmYyZTI4YWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WtckI2vZ_c0ExucH4S5kL9xI9p2HLvqrgSKgW2dXeL4">
> `UnboundLocalError: local variable 'head_num' referenced before assignment`

问题已经解决了吗

**Comment by shiva-vardhineedi** [comment]
upload it to huggingface hub and try to use lmdeploy on that uploaded model... then the error goes away but the text generation is not happening.

**Comment by czczup** [comment]
您好，如果需要用lmdeploy部署lora微调后的模型，您首先需要合并lora的权重，然后把模型封装成AutoModel。

您可以按照以下教程进行操作：
https://internvl.readthedocs.io/en/latest/tutorials/coco_caption_finetune.html#merging-lora-weights

**Comment by czczup** [comment]
Hello! If you need to deploy a LoRA fine-tuned model using lmdeploy, you'll first have to merge the LoRA weights and package the model as an AutoModel. 

Follow the tutorial at this link: https://internvl.readthedocs.io/en/latest/tutorials/coco_caption_finetune.html#merging-lora-weights
