### ISSUE TITLE
Convert to Gguf format to work with Llama.cpp?

### ISSUE THREAD

**Issue by chigkim** [OpenGVLab/InternVL#32]
Llava has various quantized models in gguf format, so it can be used with Llama.cpp.
https://github.com/ggerganov/llama.cpp/pull/3436
Is this possible?

**Comment by czczup** [comment]
Hi, thank you for your suggestion. I will add compatibility with community tools to my to-do list.

**Comment by leeaction** [comment]
gguf format is good for ollama users, Any Update?

**Comment by GHOST1834** [comment]
It will be nice to have this model in gguf format in ollama.

**Comment by nischalj10** [comment]
any updates on this? the 4b intern model is killer for its size! would love to see it supported with llama.cpp

**Comment by KOG-Nisse** [comment]
Would love internvl-chat-v1-5 in a gguf format!
https://internvl.opengvlab.com/

**Comment by thomas-rooty** [comment]
I second this

**Comment by orabazes** [comment]
@ErfeiCui why did you close this as completed?

**Comment by chigkim** [comment]
Any update on this? InternVL2-Llama3-76B on Ollama/llama.cpp would be amazing!

**Comment by chigkim** [comment]
It's more involved. you have to implement the model architecture and image preprocessing logic to llama.cpp which uses C++.
