### ISSUE TITLE
xformers attention implementation

### ISSUE THREAD

**Issue by bayley** [OpenGVLab/InternVL#321]
I'm working on an attention backend based on `xformers` to improve performance on V100; is there anything I need to be aware of when doing so or should it be straightforward?

**Comment by htian01** [comment]
The most straightforward way might be repalce the implemention of FlashAttention by xformers' attention and remove the flash attention dependency if necessary. 
May check these two classes:
https://huggingface.co/OpenGVLab/InternVL2-26B/blob/a515152d7186e32fc7d562d3ccc086c423b7728d/modeling_intern_vit.py#L40

https://huggingface.co/OpenGVLab/InternVL2-26B/blob/a515152d7186e32fc7d562d3ccc086c423b7728d/modeling_internlm2.py#L430

Don't forget to run unit test to verify the output of replaced attention are all close (torch.all_close)
