### ISSUE TITLE
Questions about your model in video-mme

### ISSUE THREAD

**Issue by zmj1203** [OpenGVLab/InternVL#322]
I noticed your latest good results on video-mme (https://video-mme.github.io/home_page.html#leaderboard), ranking 9th, the parameter size is 20B, the number of image frames is 10 frames, you also announced this good result on the github homepage, I am curious:
1. How did you test your model? The model you have open-sourced seems to be a single-frame model? How to expand it to 10 frames of images?
2. Which model is your 20B model? Is it released open-source?
Thank you!
<img width="869" alt="捕获" src="https://github.com/OpenGVLab/InternVL/assets/40570900/9805484b-7cc1-4a5d-af29-d908ee3eb4ff">

**Comment by czczup** [comment]
Hello, this result was tested by the author of Video-MME. I am not clear about some of the details, but I can reproduce this result recently when I tested the InternVL-Chat-V1-5 model using the Video-MME dataset integrated in VLMEvalKit. Maybe even a little higher. You can look at VLMEvalKit
