### ISSUE TITLE
pretrain脚本中meta_path问题

### ISSUE THREAD

**Issue by yeegnauh** [OpenGVLab/InternVL#323]
https://github.com/OpenGVLab/InternVL/blob/764fdc9f3ee102bc6c2def02c2d0ca1e94336d06/internvl_chat/shell/internlm2_20b_dynamic/internvl_chat_v1_5_internlm2_20b_dynamic_res_pretrain.sh#L44

这里的 --meta_path "path/to/pretrain/data.json" 是什么？ 可以提供下吗？

**Comment by czczup** [comment]
我们暂时没有开源pretrain data的计划，您可以自己准备好pretrain data之后填在这个位置。
