### ISSUE TITLE
How to quant InternVL2 to AWQ?

### ISSUE THREAD

**Issue by janelu9** [OpenGVLab/InternVL#324]
Can you official provide a quantization demo？

**Comment by czczup** [comment]
Hi, our AWQ 4bit version was generated using lmdeploy. You can follow the instructions in [lmdeploy's documentation](https://lmdeploy.readthedocs.io/en/latest/quantization/w4a16.html). If you encounter any issues, feel free to ask in the lmdeploy issue tracker.

**Comment by janelu9** [comment]
> Hi, our AWQ 4bit version was generated using lmdeploy. You can follow the instructions in [lmdeploy's documentation](https://lmdeploy.readthedocs.io/en/latest/quantization/w4a16.html). If you encounter any issues, feel free to ask in the lmdeploy issue tracker.

quant failed:
auto_awq.py line 45, in save_vl_model:
cannot access free variable 'state_dict'
