### ISSUE TITLE
TypeError: chat() got an unexpected keyword argument 'num_patches_list' 

### ISSUE THREAD

**Issue by liuao743** [OpenGVLab/InternVL#326]
When I use the script in huggingface https://huggingface.co/OpenGVLab/InternVL2-26B to test video data, It give me the error:
TypeError: chat() got an unexpected keyword argument 'num_patches_list'

**Comment by lijingcheng2021** [comment]
我也遇到了同样的问题

**Comment by lijingcheng2021** [comment]
请问有人解决了吗

**Comment by lijingcheng2021** [comment]
好像可以直接把 num_patches_list 这个去了

**Comment by czczup** [comment]
您好，感谢您的反馈。能否提供更详细的报错信息？因为chat函数中是有num_patches_list这个参数的，我运行hf readme中的示例代码是可以正常运行的。

https://huggingface.co/OpenGVLab/InternVL2-26B/blob/main/modeling_internvl_chat.py#L248

<img width="1267" alt="image" src="https://github.com/user-attachments/assets/76bf8515-c552-4b41-a904-b195b56028a8">
