### ISSUE TITLE
想问下支持中文图文对话吗

### ISSUE THREAD

**Issue by zhangfan-algo** [OpenGVLab/InternVL#33]

**Comment by czczup** [comment]
近期将release一个中文模型，敬请期待

**Comment by czczup** [comment]
您好，中文模型InternVL-Chat-Chinese-V1.1已经开源；
代码：https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-evaluation-chinese-models
模型权重：https://huggingface.co/OpenGVLab/InternVL-Chat-Chinese-V1.1/tree/main
在线demo： https://internvl.opengvlab.com/

**Comment by zhangfan-algo** [comment]
感谢 感谢 想问下中文OCR能力如何呀

**Comment by czczup** [comment]
目前这版只能算是粗略的支持了中文OCR，还是会有不少错误。计划2月会更新一个中文OCR更好的模型

**Comment by zhangfan-algo** [comment]
嗯呢好的 十分期待 ! 希望对中文手写体识别也能同步支持一下！
________________________________
发件人: Zhe Chen ***@***.***>
发送时间: 2024年1月25日 21:30
收件人: OpenGVLab/InternVL ***@***.***>
抄送: zhangfan-algo ***@***.***>; Author ***@***.***>
主题: Re: [OpenGVLab/InternVL] 想问下支持中文图文对话吗 (Issue #33)


目前这版只能算是粗略的支持了中文OCR，还是会有不少错误。计划2月会更新一个中文OCR更好的模型

―

**Comment by czczup** [comment]
目前还没有发布的一个权重大概是这么一个效果：
<img width="335" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/57c67c8d-3a9c-40d1-93a4-53c4eb6d854b">
<img width="355" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/990071ad-8718-4029-8ea3-2a3a8386d9b4">
