### ISSUE TITLE
How InternVL2-26Bwas evaluated?

### ISSUE THREAD

**Issue by Iven2132** [OpenGVLab/InternVL#330]
Hi, I'm confused I did some visual answering with the InternVL2-26B model and it performs very badly in that. The only model that passes that question are Gemini 1.5 pro/flash, gpt4-o, and Claude.

Then how InternVL2-26B was evaluated? That it outperforms gpt4-v, Gemini 1.5?

**Comment by ErfeiCui** [comment]
You can refer to our documentation for model evaluation: https://github.com/OpenGVLab/InternVL/blob/main/README.md#documents. Also, if possible, could you provide some examples of errors?

**Comment by noahdasanaike** [comment]
Also getting poor performance here. As an example, when prompted,

`Analyze the voting results table image and return a JSON object with this structure: {\"candidates\": [{\"name\": \"Candidate Name\", \"votes\": [{\"polling_station\": number, \"votes\": number}, ...]},...]} Extract votes for each polling station for all candidates. Ignore total votes, rejected votes, NOTA (none of the above), or other non-candidate/party columns. The table may be rotated; use the polling station numbers to determine the correct order of votes.`

on the following image,

<img width="1069" alt="test" src="https://github.com/OpenGVLab/InternVL/assets/23142832/0fc4af2f-11c9-4d0d-b4d9-9f767a44d49d">

it returns made-up numbers and candidate names.

**Comment by whai362** [comment]
InternVL's support for OCR in languages ​​other than English and Chinese is not very good. It requires additional SFT data.
