### ISSUE TITLE
Memory not increasing linearly for Multi-Image Inference

### ISSUE THREAD

**Issue by rokopi-byte** [OpenGVLab/InternVL#338]
I'm conducting experiments using Mini‑InternVL‑Chat‑4B‑V1‑5 with Multi-Image Inference. Specifically, I'm utilizing the code provided [here](https://github.com/OpenGVLab/InternVL?tab=readme-ov-file#quick-start-with-huggingface) for multi-round multi-image conversation, but with a single round (a single prompt with multiple images).

In my experiments, I am incrementally increasing the number of images one by one to estimate the GPU memory peak. However, I've noticed that the memory peak does not increase linearly with the number or size of the images used.

It is my understanding that models in version 1.5 have not been explicitly trained on multiple images. Despite this, I'm curious as to why increasing the number of images results in seemingly random increases in memory usage rather than a linear progression.

Experiments on a single A6000 (48Gb) GPU. After 5 images it goes OOM.

| Image                                                       | Size (Kb) | Peak (Mb) |
|-------------------------------------------------------------|-----------|-----------|
| ./imagenet_sample/172005241_e3a4af537e.jpg                  | 41        | 11522     |
| ./imagenet_sample/3949472_7f4ce9a39a.jpg                    | 50        | 16952     |
| ./imagenet_sample/235866094_577a8a0a6e.jpg                  | 44        | 27134     |
| ./imagenet_sample/1299591_20e445f79a.jpg                    | 27        | 34840     |
| ./imagenet_sample/76727094_f20d363734.jpg                   | 38        | 44878     |

[imagenet_sample.zip](https://github.com/user-attachments/files/16132792/imagenet_sample.zip)

**Comment by whai362** [comment]
This is reasonable. The memory usage of each image fluctuates within a reasonable range. The theoretical and actual GPU usage values differ due to the operator's implementation and the specific scenario during model inference.
