### ISSUE TITLE
When release high-resolution models?

### ISSUE THREAD

**Issue by buptweixin** [OpenGVLab/InternVL#34]
Thank you for your great work! We would like to try out the high-resolution(336+px), when will it be released?

**Comment by czczup** [comment]
Hello, the high-resolution model is mostly done, but we still need to perform some additional testing before the release. We apologize for keeping you waiting.

**Comment by czczup** [comment]
The high-resolution models have been released, including [InternViT-6B-448px](https://huggingface.co/OpenGVLab/InternViT-6B-448px) and [InternVL-Chat-V1.1](https://huggingface.co/OpenGVLab/InternVL-Chat-Chinese-V1-1), both of which use 448x448 images as input.
