### ISSUE TITLE
InternVL2 的视频微调、多图微调

### ISSUE THREAD

**Issue by aabbc-cell** [OpenGVLab/InternVL#341]
请问我想使用视频来微调 InternVL2，我是否是应该从视频中抽帧得到的多图序列，然后类比超分辨率的操作将多帧图像在第0个维度cat在一起作为输入？
此外，作者在训练 InternVL2 的时候，对于视频数据集，是否也是通过和提供在hugging face的inference的代码（video multi-round conversation (视频多轮对话)）一致的方法来做预训练的呢？

**Comment by whai362** [comment]
是的
