### ISSUE TITLE
请问Internvl-chat 2.0支持将多图放在多轮对话中的任意位置吗？

### ISSUE THREAD

**Issue by nth2000** [OpenGVLab/InternVL#343]
请问Internvl-chat 2.0支持将多图放在多轮对话中的任意位置吗？如果支持，请问如果使用lm-deploy的话如何实现，这样做的话一般会有性能损失吗？

**Comment by whai362** [comment]
支持将多图放在多轮对话中的任意位置，lmdeploy实现可能要联系lmdeploy组（我们是不同的组，lmdeploy偏重部署）。在测试上会有一些性能抖动
