### ISSUE TITLE
关于Mini-InternVL-Chat系列模型微调数据集的问题

### ISSUE THREAD

**Issue by Zhouziyi828** [OpenGVLab/InternVL#344]
您好,您在https://browser.mybank-corp.cn/ 中提到,要先准备开源数据集,再将自己的数据集添加进去,即"建议将您的数据与我们的[internvl_1_2_finetune](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/data/internvl_1_2_finetune.json)数据合并".请问这些开源数据集不是已经用于Mini-InternVL-Chat-2B-V1-5 和Mini-InternVL-Chat-4B-V1-5的训练了么,还需要把这些数据集再放进去一起微调么?
感谢您的回复

**Comment by whai362** [comment]
这些数据用于保持模型多模态对话的能力，不至于在finetune时发生能力跑偏
