### ISSUE TITLE
srun -p ${PARTITION}是指什么，假设2个GPU的情况下应该如何设置PARTITION?

### ISSUE THREAD

**Issue by 1SingleFeng** [OpenGVLab/InternVL#345]
我没使用过srun，想请问一下运行脚本里的PARTITION='your partition'，这个应该怎么填，假设有2个GPU的机器上

**Comment by YuanEric88** [comment]
> 这个是slurm的参数，如果您没有用slurm起实验的话可以直接用torchrun或者accelerate或者deepspeed

@Weiyun1025 可以提供一个直接基于torchrun的多机多卡训练启动脚本么？
