### ISSUE TITLE
Supporting for batch inference (multi-image per sample)？

### ISSUE THREAD

**Issue by joeyz0z** [OpenGVLab/InternVL#349]
我需要做图像变换检测描述，官方给的demo里面只有**batch inference (single image per sample)** 我想知道 InternVL支持 **batch inference (multi-image per sample)**吗？

**Comment by joeyz0z** [comment]
或者支持video的batch_inference吗？

**Comment by sankalpsinha-cmos** [comment]
Any solution for this?
