### ISSUE TITLE
flickr30k-CN图文检索的指标，我用clip_benchmark验证出来的和论文有些差异？

### ISSUE THREAD

**Issue by yanz2024** [OpenGVLab/InternVL#35]
https://huggingface.co/OpenGVLab/InternVL-14B-224px/tree/main 上释放的权重中文图文检索的指标
{
"dataset": "flickr30k", 
"model": "internvl_c_retrieval_hf", 
"pretrained": "./huggingface/hub/models--OpenGVLab--InternVL-14B-224px/snapshots/6d492b53f8adbbe9d577db3645d893057e3ffc59/", 
"task": "zeroshot_retrieval", 
"metrics": {
  
    "image_retrieval_recall@1": 0.7148000001907349, 
    "text_retrieval_recall@1": 0.8970000147819519, 
    "image_retrieval_recall@5": 0.9179999828338623, 
    "text_retrieval_recall@5": 0.9909999966621399, 
    "image_retrieval_recall@10": 0.9559999704360962, 
    "text_retrieval_recall@10": 0.996999979019165}, 
    "language": "cn"
    
}
论文中的指标：InternVL-C (ours) ✓ 90.3 98.8 99.7 75.1 92.9 96.4
看起来有点差异，请问一下是不是我测的哪有问题？
用的下边这个脚本测的
CUDA_VISIBLE_DEVICES=0 python3 clip_benchmark/cli.py eval --model_type internvl --language "cn" --task "zeroshot_retrieval" \
     --dataset "flickr30k" --dataset_root ./data/flickr30k --model internvl_c_retrieval_hf \
     --pretrained  ./huggingface/hub/models--OpenGVLab--InternVL-14B-224px/snapshots/6d492b53f8adbbe9d577db3645d893057e3ffc59/ --output result_ft.json

**Comment by czczup** [comment]
您好，请问测试flickr30k用的标注文件是自带的这个吗：
https://github.com/OpenGVLab/InternVL/blob/main/clip_benchmark/data/flickr30k/flickr30k_cn_test.txt

**Comment by yanz2024** [comment]
是的，用的这个，远程下载下来的。

**Comment by yanz2024** [comment]
找到原因了，我用的flickr30k的Images可能和kaggle datasets download -d adityajn105/flickr30k 这里的有些差异，我重新下载了一下，测的结果一致了，感谢解答~~
{
"dataset": "flickr30k", "model": "internvl_c_retrieval_hf", 
"pretrained": "/root/.cache/huggingface/hub/models--OpenGVLab--InternVL-14B-224px/snapshots/6d492b53f8adbbe9d577db3645d893057e3ffc59/", "task": "zeroshot_retrieval", 
"metrics": {
    "image_retrieval_recall@1": 0.7505999803543091, 
    "text_retrieval_recall@1": 0.902999997138977, 
    "image_retrieval_recall@5": 0.9287999868392944, 
    "text_retrieval_recall@5": 0.9879999756813049, 
    "image_retrieval_recall@10": 0.9639999866485596, 
    "text_retrieval_recall@10": 0.996999979019165
    
    }, "language": "cn"
}

**Comment by czczup** [comment]
> 找到原因了，我用的flickr30k的Images可能和kaggle datasets download -d adityajn105/flickr30k 这里的有些差异，我重新下载了一下，测的结果一致了，感谢解答~~ { "dataset": "flickr30k", "model": "internvl_c_retrieval_hf", "pretrained": "/root/.cache/huggingface/hub/models--OpenGVLab--InternVL-14B-224px/snapshots/6d492b53f8adbbe9d577db3645d893057e3ffc59/", "task": "zeroshot_retrieval", "metrics": { "image_retrieval_recall@1": 0.7505999803543091, "text_retrieval_recall@1": 0.902999997138977, "image_retrieval_recall@5": 0.9287999868392944, "text_retrieval_recall@5": 0.9879999756813049, "image_retrieval_recall@10": 0.9639999866485596, "text_retrieval_recall@10": 0.996999979019165
> 
> ```
> }, "language": "cn"
> ```
> 
> }

感谢您的反馈！
