### ISSUE TITLE
InternVL2-26B模型微调后，报UnboundLocalError: local variable 'head_num' referenced before assignment错误

### ISSUE THREAD

**Issue by feihuamantian** [OpenGVLab/InternVL#350]
![image](https://github.com/OpenGVLab/InternVL/assets/28010145/cb079bbf-151f-4f00-84c2-d3065425c1ff)
InternVL2-26B模型微调后，报UnboundLocalError: local variable 'head_num' referenced before assignment错误

**Comment by tdye24** [comment]
我也在全量微调InternVL2-26B，没有出现上述问题。

**Comment by feihuamantian** [comment]
> [tdye24](/tdye24)

我这边采用LORA微调的方法，按照官网上LORA微调的脚本，直接保存的微调之后的模型参数，将原有模型的一些处理文件复制到微调后的模型里面，加载模型推理的时候就报这个错误

**Comment by shiva-vardhineedi** [comment]
same here. I also finetuned [mini-internVL](https://huggingface.co/shivavardhineedi/mini_internVL_eval) (Lora Finetuning). Facing the same error.. can someone help?

**Comment by feihuamantian** [comment]
> 我也在全量微调InternVL2-26B，没有出现上述问题。
其它人也遇到了这个问题：
https://github.com/OpenGVLab/InternVL/issues/318

**Comment by feihuamantian** [comment]
> 我也在全量微调InternVL2-26B，没有出现上述问题。
@tdye 这个网友也遇到同样问题，麻烦帮忙看一下
LORA微调训练是ok的，训练好的模型是整体保存的，推理训练好的模型就遇到这个错误了

https://github.com/OpenGVLab/InternVL/issues/318

**Comment by EthanLeo-LYX** [comment]
> 我也在全量微调InternVL2-26B，没有出现上述问题。

想请教一下，有没有InternVL2-26B全量微调的参考呀？

**Comment by wangyang1923** [comment]
请教一下 有4张3090的卡  为啥这个26B模型只能在一张卡上跑

**Comment by G-z-w** [comment]
> > 我也在全量微调InternVL2-26B，没有出现上述问题。
> 
> 想请教一下，有没有InternVL2-26B全量微调的参考呀？

请参考：https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html#start-2nd-fine-tuning

**Comment by G-z-w** [comment]
> 请教一下 有4张3090的卡 为啥这个26B模型只能在一张卡上跑

请问您用的是什么框架

**Comment by G-z-w** [comment]
> same here. I also finetuned [mini-internVL](https://huggingface.co/shivavardhineedi/mini_internVL_eval) (Lora Finetuning). Facing the same error.. can someone help?

Our new code has been released, please refer to https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html#start-2nd-fine-tuning.
