### ISSUE TITLE
Internvl技术交流群，方便Internvl实战交流

### ISSUE THREAD

**Issue by feihuamantian** [OpenGVLab/InternVL#351]
![20240711-113525](https://github.com/OpenGVLab/InternVL/assets/28010145/4068d819-b68c-467f-a904-f285eaf548fe)
如果二维码失效，可以加微信：yx116169

**Comment by smurf-1119** [comment]
二维码过期了，还有新的吗

**Comment by stomachacheGE** [comment]
> 二维码过期了，还有新的吗

同问

**Comment by xiezheng-cs** [comment]
同问

**Comment by sp1cae** [comment]
需要更新

**Comment by whai362** [comment]
进群可以
