### ISSUE TITLE
书生-万象https://internvl.intern-ai.org.cn/使用中经常出现“我还没学习到关于这个话题的内容，新开会话换个话题继续聊吧”，然后把我的会话就关掉了

### ISSUE THREAD

**Issue by Git-TengSun** [OpenGVLab/InternVL#353]
![image](https://github.com/OpenGVLab/InternVL/assets/53203204/a37a4fa7-ed7d-4953-b4f5-d969d5357d5a)

**Comment by whai362** [comment]
是过度安全加固导致的，我们最近会持续优化这个问题
