### ISSUE TITLE
internvl2 相关问题

### ISSUE THREAD

**Issue by sporterman** [OpenGVLab/InternVL#354]
请问internvl2如何进行目标检测并得到精确的目标框，目前简单的调用好像无法得到宣传中的效果
![微信图片_20240711151140](https://github.com/OpenGVLab/InternVL/assets/13059352/d6409171-dafc-493d-b81d-381bec3f66b6)

**Comment by sporterman** [comment]
应该怎么使用才能达到上面这张图片的效果

**Comment by sporterman** [comment]
@lvhan028

**Comment by lvhan028** [comment]
烦请提供下复现路径，以及对照组（上图）reference demo code

**Comment by whai362** [comment]
是基于visionllm v2做的，我们最近会上线这个功能
