### ISSUE TITLE
如何使用v100微调Mini-InternVL-Chat-2B-V1-5，v100不支持bfloat16

### ISSUE THREAD

**Issue by 1SingleFeng** [OpenGVLab/InternVL#355]
我想使用v100微调Mini-InternVL-Chat-2B-V1-5，但是v100不支持vfloat16，请问应该如何修改代码和模型使其能够完成训练

**Comment by whai362** [comment]
可以试试看正常的float16，或者等我们后续官方支持float16，在那之前如果你试work了，欢迎给我们提pr

**Comment by feihuamantian** [comment]
https://github.com/OpenGVLab/InternVL/issues/351

**Comment by PoTsui99** [comment]
基本上就是两个改动:
1. 注意力机制从fast_attn改为eager
2. 模型改为float16
![屏幕截图 2024-07-16 163130](https://github.com/user-attachments/assets/353b52ca-d140-4ce7-878c-a5c97b24a908)
![屏幕截图 2024-07-16 170936](https://github.com/user-attachments/assets/33e1464b-07ee-4a4e-83cb-eef22cb63199)
PS: 我是llm和visual encoder分别加载的, 所以需要单独将mlp projector也转为float16...

**Comment by LaurenceSu1037** [comment]
> 2\. 模型改为float16

你好，想问一下这个地方除了只有这vision_model和llm需要将torch.type改为torch.float16吗？图1中出现的model=InternVLChatModel.from_pretrained()这里不用改吗？仍然保持torch.dtype=torch.bfloat16?
