### ISSUE TITLE
自定义数据集支持多轮对话吗

### ISSUE THREAD

**Issue by 1SingleFeng** [OpenGVLab/InternVL#356]
目前在官方给的自定义数据集格式里看起来只支持单轮对话，请问多轮对话的数据集格式应该怎么写？
https://github.com/OpenGVLab/InternVL/blob/main/document/How_to_finetune_mini_internvl_chat_v1_5_on_a_custom_dataset.md#2-prepare-datasets
{"id": 0, "image": "image path relative to dataset path", "conversations": [{"from": "human", "value": "<image>\nyour question"}, {"from": "gpt", "value": "response"}]}

**Comment by tdye24** [comment]
就是这个格式吧

**Comment by 1SingleFeng** [comment]
> 就是这个格式吧

多轮对话我是接着往下写吗，如下所示
{"id": 0, "image": "image path relative to dataset path", "conversations": [{"from": "human", "value": "\nyour question"}, {"from": "gpt", "value": "response"}, {"from": "human", "value": "\nyour question2"}, {"from": "gpt", "value": "response2"}]}

**Comment by maysonma** [comment]
> > 就是这个格式吧
> 
> 多轮对话我是接着往下写吗，如下所示 {"id": 0, "image": "image path relative to dataset path", "conversations": [{"from": "human", "value": "\nyour question"}, {"from": "gpt", "value": "response"}, {"from": "human", "value": "\nyour question2"}, {"from": "gpt", "value": "response2"}]}

对的 我试过可以work，'\n' 不需要加。

**Comment by czczup** [comment]
可以按照这个文档准备数据：https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html
