### ISSUE TITLE
有测评opencompass的计划么？好像上面还是1.5的版本

### ISSUE THREAD

**Issue by moyans** [OpenGVLab/InternVL#358]

**Comment by whai362** [comment]
开源模型已经在上面更新，40B模型排第二，距离GPT-4o只差0.2；8B模型接近Gemini-1.5-Pro，只差0.3；其实我们的pro模型能第一英文各种原因还没得分放出来。
https://rank.opencompass.org.cn/leaderboard-multimodal/?m=REALTIME
