### ISSUE TITLE
请问internvl2用来做目标检测有相关性能指标吗

### ISSUE THREAD

**Issue by Halflifefa** [OpenGVLab/InternVL#359]
看demo中有用internvl2做目标检测的案例，请问这类问题有测试过相关性能指标吗？

**Comment by whai362** [comment]
目前模型可以做grounding任务，具体点数可以看链接https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-evaluation，看Visual Grounding部分。至于更常用的目标检测和开放世界检测，我们最近会上线这块能力，到时模型可以在COCO，LVIS等benchmark上取得很好的效果，欢迎关注。

**Comment by qyc-98** [comment]
想问问这个大概什么时候会上线呀

**Comment by 77h2l** [comment]
@whai362 请问一下，假设我们现在想通过InternVL2来做Grounding和region-referring任务，（i.e. 输入文本prompt，输出图中对应的bbox位置信息，输入一个bbox信息，返回对应的region的caption）输入的prompt该如何设计，才能有比较好的效果呢，试了下Release的模型和api似乎效果都不理想。

**Comment by tgyy1995** [comment]
@77h2l 请教下internvl2的referring能力有多差？你知道其他具备referring能力的小MLLM吗

**Comment by zodiacg** [comment]
目前看到evaluation部分都是V1系列的模型，没有V2版本的。自己尝试了一下也没能使用<ref>标签成功触发模型输出<box>标签。目前InternVL2是否尚未有相关的训练支持？

**Comment by czczup** [comment]
> 目前看到evaluation部分都是V1系列的模型，没有V2版本的。自己尝试了一下也没能使用标签成功触发模型输出标签。目前InternVL2是否尚未有相关的训练支持？

InternVL2的evluation部分在这：https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html

**Comment by czczup** [comment]
InternVL系列模型在RefCOCO上的grounding评测见下表：

|             Model              | avg. | RefCOCO<br>(val) | RefCOCO<br>(testA) | RefCOCO<br>(testB) | RefCOCO+<br>(val) | RefCOCO+<br>(testA) | RefCOCO+<br>(testB) | RefCOCO‑g<br>(val) | RefCOCO‑g<br>(test) |
| :----------------------------: | :--: | :--------------: | :----------------: | :----------------: | :---------------: | :-----------------: | :-----------------: | :----------------: | :-----------------: |
| UNINEXT-H<br>(Specialist SOTA) | 88.9 |       92.6       |        94.3        |        91.5        |       85.2        |        89.6         |        79.8         |        88.7        |        89.4         |
|                                |      |                  |                    |                    |                   |                     |                     |                    |                     |
| Mini-InternVL-<br>Chat-2B-V1-5 | 75.8 |       80.7       |        86.7        |        72.9        |       72.5        |        82.3         |        60.8         |        75.6        |        74.9         |
| Mini-InternVL-<br>Chat-4B-V1-5 | 84.4 |       88.0       |        91.4        |        83.5        |       81.5        |        87.4         |        73.8         |        84.7        |        84.6         |
|       InternVL‑Chat‑V1‑5       | 88.8 |       91.4       |        93.7        |        87.1        |       87.0        |        92.3         |        80.9         |        88.5        |        89.3         |
|                                |      |                  |                    |                    |                   |                     |                     |                    |                     |
|          InternVL2‑1B          | 79.9 |       83.6       |        88.7        |        79.8        |       76.0        |        83.6         |        67.7         |        80.2        |        79.9         |
|          InternVL2‑2B          | 77.7 |       82.3       |        88.2        |        75.9        |       73.5        |        82.8         |        63.3         |        77.6        |        78.3         |
|          InternVL2‑4B          | 84.4 |       88.5       |        91.2        |        83.9        |       81.2        |        87.2         |        73.8         |        84.6        |        84.6         |
|          InternVL2‑8B          | 82.9 |       87.1       |        91.1        |        80.7        |       79.8        |        87.9         |        71.4         |        82.7        |        82.7         |
|         InternVL2‑26B          | 88.5 |       91.2       |        93.3        |        87.4        |       86.8        |        91.0         |        81.2         |        88.5        |        88.6         |
|         InternVL2‑40B          | 90.3 |       93.0       |        94.7        |        89.2        |       88.5        |        92.8         |        83.6         |        90.3        |        90.6         |
|    InternVL2-<br>Llama3‑76B    | 90.0 |       92.2       |        94.8        |        88.4        |       88.8        |        93.1         |        82.8         |        89.5        |        90.3         |

- We use the following prompt to evaluate InternVL's grounding ability: `Please provide the bounding box coordinates of the region this sentence describes: <ref>{}</ref>`

**Comment by PredyDaddy** [comment]
> 目前模型可以做grounding任务，具体点数可以看链接[https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-evaluation，看Visual](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-evaluation%EF%BC%8C%E7%9C%8BVisual) Grounding部分。至于更常用的目标检测和开放世界检测，我们最近会上线这块能力，到时模型可以在COCO，LVIS等benchmark上取得很好的效果，欢迎关注。

请问现在internVL可以做grounding了吗？提示词模版是什么可以问一下吗？

**Comment by czczup** [comment]
> > 目前模型可以做grounding任务，具体点数可以看链接[https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-evaluation，看Visual](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-evaluation%EF%BC%8C%E7%9C%8BVisual) Grounding部分。至于更常用的目标检测和开放世界检测，我们最近会上线这块能力，到时模型可以在COCO，LVIS等benchmark上取得很好的效果，欢迎关注。
> 
> 请问现在internVL可以做grounding了吗？提示词模版是什么可以问一下吗？

Please provide the bounding box coordinate of the region this sentence describes: <ref>XXX</ref>

**Comment by Dineshkumar-Anandan-ZS0367** [comment]
Are you got bounding box from internvl-chat-8b model

**Comment by SuryaThiru** [comment]
https://github.com/OpenGVLab/InternVL/blob/c62fa4f7c850165d7386bdc48ac6bc5a6fab0864/internvl_chat/eval/refcoco/evaluate_grounding.py#L199-L200

I see that some scaling is done on the output bounding boxes. However, when I try the provided prompt the output boxes doesn't quite fit my custom image examples (but the ratio looks right) and are not in 0 to 1 range.

Is there a recommended preprocessing/postprocessing step?
