### ISSUE TITLE
40B多卡推理报错

### ISSUE THREAD

**Issue by liuao743** [OpenGVLab/InternVL#360]
![530f3d0e7197ac08d22bbf109712c7e](https://github.com/user-attachments/assets/d37fd151-5857-4f75-813f-084451bd511c)
如图，使用两张卡推理报错。
另外，我尝试修改modeling文件，但是每次都会重新下载modeling文件，覆盖掉我改的，设置local_files_only仍然不起作用

**Comment by xiangzhenge** [comment]
I also encountered the same problem

**Comment by liuao743** [comment]
> ![530f3d0e7197ac08d22bbf109712c7e](https://private-user-images.githubusercontent.com/62134958/348162965-d37fd151-5857-4f75-813f-084451bd511c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODA1MDksIm5iZiI6MTcyMDc4MDIwOSwicGF0aCI6Ii82MjEzNDk1OC8zNDgxNjI5NjUtZDM3ZmQxNTEtNTg1Ny00Zjc1LTgxM2YtMDg0NDUxYmQ1MTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEwMzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNmY0YmJiM2Y2MzY5NjFiZDNjNmVkMDBjYjAyNmU0ZWRhZDQ2ZDIxZWI1NGU0YjljY2M3Y2ZkNTNiYTZkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kDm5kWROFW-NjVQKJtAR1MCW7V5mHL7IPYepAOwqJdc) 如图，使用两张卡推理报错。 另外，我尝试修改modeling文件，但是每次都会重新下载modeling文件，覆盖掉我改的，设置local_files_only仍然不起作用

pdb了一下，觉得是transformer的问题，他那个unfinished_sequences是按照input_ids的device来的，而internvl用双卡，device_map='auto'的话，语言模型前面会放到0卡，后面会放到1卡，导致输出最终在1卡上，而unfinished_sequences还在0卡上，改一下就好了

**Comment by fourierer** [comment]
> > ![530f3d0e7197ac08d22bbf109712c7e](https://private-user-images.githubusercontent.com/62134958/348162965-d37fd151-5857-4f75-813f-084451bd511c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODA1MDksIm5iZiI6MTcyMDc4MDIwOSwicGF0aCI6Ii82MjEzNDk1OC8zNDgxNjI5NjUtZDM3ZmQxNTEtNTg1Ny00Zjc1LTgxM2YtMDg0NDUxYmQ1MTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEwMzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNmY0YmJiM2Y2MzY5NjFiZDNjNmVkMDBjYjAyNmU0ZWRhZDQ2ZDIxZWI1NGU0YjljY2M3Y2ZkNTNiYTZkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kDm5kWROFW-NjVQKJtAR1MCW7V5mHL7IPYepAOwqJdc) 如图，使用两张卡推理报错。 另外，我尝试修改modeling文件，但是每次都会重新下载modeling文件，覆盖掉我改的，设置local_files_only仍然不起作用
> 
> pdb了一下，觉得是transformer的问题，他那个unfinished_sequences是按照input_ids的device来的，而internvl用双卡，device_map='auto'的话，语言模型前面会放到0卡，后面会放到1卡，导致输出最终在1卡上，而unfinished_sequences还在0卡上，改一下就好了

您好，请问您是在哪里修改的呢，我这里也遇到了相同的问题
![image](https://github.com/user-attachments/assets/8dd1a9c4-d008-4a00-b6ba-13e976220de0)
