### ISSUE TITLE
What version of internvl2 is on this site https://internvl.intern-ai.org.cn/ ？

### ISSUE THREAD

**Issue by lmx760581375** [OpenGVLab/InternVL#361]
Thanks for open source, amazing work!

These days, I tried to test the model effect on your chat demo and found that the effect is very good. But I found that the demo effect of my own locally deployed internvl2-26b is quite different from that of this website. May I ask whether the LLM base of this website is internLM-20b? Which dialogue template is used?

Looking forward to hearing back from your team, I hope to replicate the amazing results on my own local demo.

**Comment by whai362** [comment]
108B

**Comment by whai362** [comment]
We will release a large parameter version next week. Thanks for your attention.

**Comment by feihuamantian** [comment]
https://github.com/OpenGVLab/InternVL/issues/351

**Comment by czczup** [comment]
We ran a larger model using Llama3, and it achieved performance very close to InternVL2-Pro. It is open-sourced here: https://huggingface.co/OpenGVLab/InternVL2-Llama3-76B
