### ISSUE TITLE
finetune internvl2.0

### ISSUE THREAD

**Issue by Sisi0518** [OpenGVLab/InternVL#364]
请问如何finetune InternVL2.0 ？和这个finetune internvl_chat_v1_2是一样的？https://github.com/OpenGVLab/InternVL/blob/v2.0.0/document/How_to_finetune_internvl_chat_v1_2_on_a_custom_dataset.md

**Comment by xiaohuihui52309** [comment]
同问

**Comment by xiaohuihui52309** [comment]
基于InternVL2.0 进行finetune的方法与internvl_chat_v1_2一样吗

**Comment by dszpr** [comment]
老哥，你微调跑起来了吗，我基于llava的训练代码去微调internvl2，目前还是有报错

**Comment by xiaohuihui52309** [comment]
我用swift跑起来了

发自我的iPhone

**Comment by feihuamantian** [comment]
https://github.com/OpenGVLab/InternVL/issues/351

**Comment by pbarker** [comment]
+1

**Comment by Varun-GP** [comment]
+1

**Comment by CharRic** [comment]
+1

**Comment by cxmscb** [comment]
+1

**Comment by Road2Redemption** [comment]
Same question!

**Comment by czczup** [comment]
现在可以按照以下的文档，用本仓库的代码微调InternVL2的模型：
https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html
