### ISSUE TITLE
Code for video-text retrieval evaluation on MSR-VTT

### ISSUE THREAD

**Issue by YasmineXXX** [OpenGVLab/InternVL#37]
Thank you for your great work! Could you please share the code for video-text retrieval evaluation on MSR-VTT dataset?

**Comment by czczup** [comment]
Hello, thank you for your interest. We plan to open-source this code soon, but it is not yet fully organized. We need some time to sort out the code. Thank you for your patience in waiting.

**Comment by Arsiuuu** [comment]
@czczup Hi~has it been resolved?

**Comment by czczup** [comment]
Hello, thanks for your attention; The code for video-text retrieval will soon be open-sourced in the repo of [InternVideo2](https://github.com/OpenGVLab/InternVideo2). Thanks again for your patience.

**Comment by czczup** [comment]
Code for MSR-VTT retrieval is released at:
https://github.com/OpenGVLab/InternVL/blob/main/video_retrieval/test_msrvtt.py
