### ISSUE TITLE
InternVL2不支持Flash Attention

### ISSUE THREAD

**Issue by dszpr** [OpenGVLab/InternVL#373]
感谢作者的精彩工作
微调InternVL2-26B时报错，在模型加载时，报错ValueError: InternVLChatModel does not support Flash Attention 2.0 yet.
在模型加载代码中将 attn_implementation注释掉可以正常加载
            model = transformers.AutoModel.from_pretrained(
                model_args.model_name_or_path,
                cache_dir=training_args.cache_dir,
                # attn_implementation=attn_implementation,
                torch_dtype=(torch.bfloat16 if training_args.bf16 else None),
                trust_remote_code=True,
                **bnb_model_from_pretrained_args
请问目前InternVL2不支持Flash Attention吗？还是需要对Flash Attention的版本进行升级？

**Comment by feihuamantian** [comment]
https://github.com/OpenGVLab/InternVL/issues/351

**Comment by czczup** [comment]
我猜测应该是因为之前没有在模型代码里加上supports_flash_attn_2 = True， 现在已经加上了

<img width="776" alt="image" src="https://github.com/user-attachments/assets/4a19a277-79a9-414c-b9f2-c985b24293d1">
