### ISSUE TITLE
InternVL2 fine-tuning on video-to-text dataset

### ISSUE THREAD

**Issue by BillChan226** [OpenGVLab/InternVL#374]
Great work! I'm wondering when will InternVL2 provides a pipeline fine-tuning on our customized video-to-text dataset? Thank you!

**Comment by czczup** [comment]
Hi, you can prepare video data refer to this document: https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#video-data

And follow this document to fine-tune InternVL2 models:
https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html
