### ISSUE TITLE
InternVL-C如何提取图片和文本的向量，而不是直接求相似度

### ISSUE THREAD

**Issue by liumingzhu6060** [OpenGVLab/InternVL#376]
InternVL-C如何提取图片和文本的向量，而不是直接求相似度
![d176b240741f3ca70754c514ede9776](https://github.com/user-attachments/assets/1ab9202f-b62d-4e2e-be76-7dce54ea55fe)

**Comment by liumingzhu6060** [comment]
已解决

**Comment by Liam-Ji** [comment]
请问怎么解决的？
