### ISSUE TITLE
蒸馏

### ISSUE THREAD

**Issue by sssssshf** [OpenGVLab/InternVL#378]
请问“InternViT-300M-448px”这个模型的蒸馏代码开源了吗

**Comment by feihuamantian** [comment]
https://github.com/OpenGVLab/InternVL/issues/351

**Comment by sssssshf** [comment]
> #351

群已满。有蒸馏视觉大模型的这方面的技术资料吗

**Comment by czczup** [comment]
没有，暂时没有计划开源这部分的代码
