### ISSUE TITLE
max_seq_length

### ISSUE THREAD

**Issue by ecnuycxie** [OpenGVLab/InternVL#381]
Hello, I want to fine-tune the internvl2-26B model using my dataset with 48w conversation data. However, most of the conversations exceed 4096 tokens in length, no more than 5000 tokens. 

Can I set the max_seq_length to 5000 in my experiments? will this decrease the performance of InternVL2?

**Comment by czczup** [comment]
Hello, you can set the `max_seq_length` according to your needs; our InternVL2 series models were trained with `max_seq_length=8192`.

**Comment by peace-zy** [comment]
> Hello, you can set the `max_seq_length` according to your needs; our InternVL2 series models were trained with `max_seq_length=8192`.

@czczup 你好，问下max_seq_length是图片+文本的总长度吗？
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L374C1-L379C71

**Comment by czczup** [comment]
> > Hello, you can set the `max_seq_length` according to your needs; our InternVL2 series models were trained with `max_seq_length=8192`.
> 
> @czczup 你好，问下max_seq_length是图片+文本的总长度吗？ https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L374C1-L379C71

是的，是整个序列所有token的总长度
