### ISSUE TITLE
InternVL1.5两个训练阶段使用的数据集

### ISSUE THREAD

**Issue by ATing0203** [OpenGVLab/InternVL#382]
请问internVL1.5论文中提到的这些训练数据集是否会开源？

internVL1.2提供的那些并不完整。https://github.com/OpenGVLab/InternVL/tree/v2.0.0/internvl_chat#prepare-training-datasets

![image](https://github.com/user-attachments/assets/ff4fe1b9-8d7d-4c86-b367-3d067e4e52a8)

**Comment by czczup** [comment]
您好，感谢您对我们工作的关注。我们暂时没有计划去进一步开源训练数据，我们使用的大部分是整理过的开源数据，进行二次分发在licence上可能也存在一些问题。
