### ISSUE TITLE
huggingFace space中 InternVL-Pro是哪个模型？

### ISSUE THREAD

**Issue by hehuang139** [OpenGVLab/InternVL#383]
如题。
非常感谢开源的InternVL2多模态模型，在space上测试，发现效果很棒，其中有一个InternVL-Pro模型效果是最好的，请问这个模型是哪个版本？

**Comment by HubHop** [comment]
同问

**Comment by bendanzzc** [comment]
盲猜就是76B？https://github.com/OpenGVLab/InternVL/issues/358 这个issue说pro能第一也没回答76B的排名情况，但看榜单76目前第一

**Comment by czczup** [comment]
那个模型暂时还没有开源，还在走我们实验室内部的审批流程。

**Comment by cxmscb** [comment]
> 那个模型暂时还没有开源，还在走我们实验室内部的审批流程。

请问预计什么时候可以开源？
