### ISSUE TITLE
InternVL2-26B / 40B AWQ 4bit至少需要多少VRAM？

### ISSUE THREAD

**Issue by tungloong** [OpenGVLab/InternVL#386]
https://huggingface.co/OpenGVLab/InternVL2-26B-AWQ
https://huggingface.co/OpenGVLab/InternVL2-40B-AWQ
请问这俩模型做推理，分别至少需要多少显存？

**Comment by thiner** [comment]
根据我之前部署InternVL-1.5-26b的经验，需要至少三块A10 24GB 显卡。
