### ISSUE TITLE
internvl_chat_finetune.py bug?

### ISSUE THREAD

**Issue by VietDunghacker** [OpenGVLab/InternVL#389]
def __getitem__(self, i) -> Dict[str, torch.Tensor]:
        i = i % len(self.raw_data)
        while True:
            try:
                data_item = json.loads(self.raw_data[i])
                if 'image' in data_item and len(data_item['image']) != 0:
                    ret = self.multi_modal_get_item(data_item)
                else:
                    ret = self.pure_text_get_item(data_item)
                break

In the v2.0 code, there is new function video_get_item and multi_modal_multi_image_get_item to handle new type of data, but in __getitem__ you are still using the old code of handling single image data and text data only.

**Comment by czczup** [comment]
Yes, you are right. It was my oversight. I will fix this bug immediately.

**Comment by czczup** [comment]
This issue has been solved.
