### ISSUE TITLE
Bare minimum code for InternVL-Chat?

### ISSUE THREAD

**Issue by paulgavrikov** [OpenGVLab/InternVL#39]
Hi, 

do you have any example available to run InternVL-Chat without gradio? It would be very helpful if you could share some bare minimum python script to load the model from HF and interact.

Thanks!

**Comment by czczup** [comment]
Thanks for your suggestion, we will provide bare minimum python script as soon as possible.

**Comment by czczup** [comment]
Hi, you can run InternVL-Chat with transformers like this code:

```python
import torch
from PIL import Image
from transformers import AutoModel, CLIPImageProcessor
from transformers import AutoTokenizer

path = "OpenGVLab/InternVL-Chat-Chinese-V1-1"
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map='auto').eval()

tokenizer = AutoTokenizer.from_pretrained(path)
image = Image.open('./examples/image2.jpg').convert('RGB')
image = image.resize((448, 448))
image_processor = CLIPImageProcessor.from_pretrained(path)

pixel_values = image_processor(images=image, return_tensors='pt').pixel_values
pixel_values = pixel_values.to(torch.bfloat16).cuda()

generation_config = dict(
    num_beams=1,
    max_new_tokens=512,
    do_sample=False,
)

question = "Describe this image in detail."
response = model.chat(tokenizer, pixel_values, question, generation_config)
```

**Comment by paulgavrikov** [comment]
Thank you for providing this! I think there are some wrong import checks. I get an error when loading the model from HF: `ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run "pip install flash_attn"`. However, I have this already installed. 
Before that I also got the error `ImportError: This modeling file requires the following packages that were not found in your environment: fastchat. Run "pip install fastchat"`. Fastchat does not exists in pip, but I could fix it by installing `fschat`

**Comment by czczup** [comment]
Thanks for your feedback. The implementation of flash attention in InternViT-6B is compatible with both old and new versions. After my testing, it runs normally from v0.2.8 to v2.3.6. There may be some interface changes in v2.5.2, and I am currently verifying this. Additionally, fastchat was not actually used, and I have already removed it from the code.

**Comment by czczup** [comment]
Thank you for bringing this to our attention. The issue has been addressed and closed. Feel free to reach out if you have any more concerns. Thanks again!

**Comment by paulgavrikov** [comment]
Hi, It seems that recents commots reintroduced fastchat is back as a dependency for all models. Could you kindly check?

**Comment by czczup** [comment]
> Hi, It seems that recents commots reintroduced fastchat is back as a dependency for all models. Could you kindly check?

I just fixed this issue, thanks for feedback!

**Comment by Iven2132** [comment]
> > Hi, It seems that recents commots reintroduced fastchat is back as a dependency for all models. Could you kindly check?
> 
> I just fixed this issue, thanks for feedback!

How did you fix that?
