### ISSUE TITLE
执行from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig from lmdeploy.vl import load_image  model = 'OpenGVLab/InternVL2-8B' system_prompt = '我是书生·万象，英文名是InternVL，是由上海人工智能实验室及多家合作单位联合开发的多模态大语言模型。' image = load_image('E:/ai3/LLaMA-Factory/OpenGVLab/InternVL2-8B/examples/image1.jpg') chat_template_config = ChatTemplateConfig('internvl-internlm2') chat_template_config.meta_instruction = system_prompt pipe = pipeline(model, chat_template_config=chat_template_config,                 backend_config=TurbomindEngineConfig(session_len=8192)) response = pipe(('describe this image', image)) print(response.text)

### ISSUE THREAD

**Issue by anstonjie** [OpenGVLab/InternVL#391]
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin, please note cuda version should >= 11.3 when compiled with cuda 11
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[WARNING] gemm_config.in is not found; using default GEMM algo

**Comment by czczup** [comment]
Thank you for your message. Unfortunately, ensuring the proper operation of lmdeploy on Windows is beyond our scope of support. We recommend using a Linux platform for optimal performance. Alternatively, you may find more specific assistance by consulting the [lmdeploy](https://github.com/InternLM/lmdeploy/tree/main) repository or reaching out to their support team.
