### ISSUE TITLE
执行 model = 'OpenGVLab/InternVL2-8B' 的hello wold的例子 入门的出现下面的错误

### ISSUE THREAD

**Issue by anstonjie** [OpenGVLab/InternVL#392]
执行下面的代码
from lmdeploy import pipeline, TurbomindEngineConfig, ChatTemplateConfig
from lmdeploy.vl import load_image

model = 'OpenGVLab/InternVL2-8B'
system_prompt = '我是书生·万象，英文名是InternVL，是由上海人工智能实验室及多家合作单位联合开发的多模态大语言模型。'
image = load_image('E:/ai3/LLaMA-Factory/OpenGVLab/InternVL2-8B/examples/image1.jpg')
chat_template_config = ChatTemplateConfig('internvl-internlm2')
chat_template_config.meta_instruction = system_prompt
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192))
response = pipe(('describe this image', image))
print(response.text)

出现 也没有输出结果怎么回事呀
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin, please note cuda version should >= 11.3 when compiled with cuda 11
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[WARNING] gemm_config.in is not found; using default GEMM algo

**Comment by czczup** [comment]
你能在windows环境下用lmdeploy运行其他模型吗，建议在lmdeply的仓库里查询一下windows系统部署相关的操作：https://github.com/InternLM/lmdeploy
