### ISSUE TITLE
Finetuning code/script/guide for InternVL 2.0 model series

### ISSUE THREAD

**Issue by Nyandwi** [OpenGVLab/InternVL#395]
Hello, thanks for putting powerful InternVL 2.0 VLMs in the wild. We would appreciate if you can release the script/code/guide for fine-tuning them. Thanks!

**Comment by feihuamantian** [comment]
https://github.com/OpenGVLab/InternVL/issues/351

**Comment by stay-leave** [comment]
> #351

这个二维码过期了，可以更新下吗

**Comment by Road2Redemption** [comment]
I find something on modelscope, but I'm not sure whether there are better ways to fine-tune InternVL 2.0 models. I hope there are scripts like InternVL 1.0 models in github. Thanks~

**Comment by THU-Kingmin** [comment]
+1

**Comment by wangwang110** [comment]
+1

**Comment by czczup** [comment]
InternVL2的文档已经发布了：

transformers快速启动：https://internvl.readthedocs.io/en/latest/internvl2.0/quick_start.html
微调：https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html
评测：https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html
部署：https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html
