### ISSUE TITLE
[Bug] 推理停不下来

### ISSUE THREAD

**Issue by eigen2017** [OpenGVLab/InternVL#396]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

lmdeploy部署，用的openai的http请求方式，

加了stop=['</s>']

以及penalty全为2

怀疑遇到了终止token但没停下来。
生成结果如下
![6068afdf920485132cded142e748dfe](https://github.com/user-attachments/assets/67f50423-d162-4210-8acc-1ec15b598463)

### Reproduction

none

### Environment

```Shell
none
```

### Error traceback

```Shell
none
```

**Comment by czczup** [comment]
请问您的lmdeploy版本是什么，可以升级到v0.5.2再试试
