### ISSUE TITLE
公式显示问题

### ISSUE THREAD

**Issue by hflexx** [OpenGVLab/InternVL#397]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

![image](https://github.com/user-attachments/assets/6754451a-e148-4db4-963d-39df91f71526)
尝尝遇到公式输出失败的问题

### Reproduction

公式显示问题

### Environment

```Shell
公式显示问题
```

**Comment by czczup** [comment]
您好，感谢您的反馈。我们已经安排了同学去看前端显示的问题。
