### ISSUE TITLE
Fine-tuning Code For InternLM2 Series

### ISSUE THREAD

**Issue by KaranBhuva22** [OpenGVLab/InternVL#398]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

The InternVL2 series is outstanding. We would appreciate it if you could release both the fine-tuning code and detailed documentation on how to fine-tune a InternVL2 series.

Thank you!!

### Reproduction

.

### Environment

```Shell
.
```

**Comment by Road2Redemption** [comment]
Are there scripts or codes on fine-tuning InternVL2 models too?

**Comment by THU-Kingmin** [comment]
+1

**Comment by KaranBhuva22** [comment]
![Screenshot from 2024-07-24 16-58-01](https://github.com/user-attachments/assets/17516924-38aa-4a6c-a2a7-c1f168d0b535)
The image shows a TODO list where @czczup  has marked "Release training/evaluation code for InternVL2 series" as complete. However, I cannot locate the actual training code for the InternVL2 series. @czczup it would be great if you can you guide us for the training steps!

**Comment by chris-tng** [comment]
I'm interested in fine-tuning code as well. It would be also great if it supports multi-image fine-tuning.

Thanks

**Comment by VietDunghacker** [comment]
From what I have experimented, the training procedure is the same with InternVL 1.5, just different checkpoint. To support multi-image fine-tuning, in the dataset, you only need add multiple image tag <image> for each image.

**Comment by VietDunghacker** [comment]
@KaranBhuva22 Yes, I have finetuned it on my custom dataset. The code worked without error so far, and the results are good.

**Comment by KaranBhuva22** [comment]
Thanks @VietDunghacker

**Comment by czczup** [comment]
InternVL2的微调文档已经发布了，可以试试看按照这个指南进行微调。

如果遇到问题欢迎和我反馈，我来修改文档让他更好用～

https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html

**Comment by KaranBhuva22** [comment]
I will look at it into it. Thank you so much @czczup.

**Comment by royzhang12** [comment]
> InternVL2的微调文档已经发布了，可以试试看按照这个指南进行微调。
> 
> 如果遇到问题欢迎和我反馈，我来修改文档让他更好用～
> 
> https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html



> InternVL2的微调文档已经发布了，可以试试看按照这个指南进行微调。
> 
> 如果遇到问题欢迎和我反馈，我来修改文档让他更好用～
> 
> https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html

@czczup 请问internvl2-76B的微调什么时候发布？ 或者可以直接用40B的脚本进行微调
