### ISSUE TITLE
[Bug] InternVL2-26B回答牛头不对马嘴

### ISSUE THREAD

**Issue by wciq1208** [OpenGVLab/InternVL#400]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

![test](https://github.com/user-attachments/assets/d965816d-a3ad-4aca-88bb-c56b5da668a0)
输入该图片和问题，结果分别输出如下：

输入：图片里说了什么东西
输出：这张图片上写着“Tank Destroyer”，这是《坦克世界》（World of Tanks）中的一个术语，指的是一种类型的坦克，通常具有强大的火炮和装甲，用于摧毁敌方坦克。

输入：图片里有什么事物
输出：这张图片显示了一辆坦克。坦克是一种用于陆地作战的装甲战斗车辆，通常具有强大的火力和防护能力。图片中的坦克似乎是军事用途的，可能用于训练或展示。

输入：图片里有什么文字信息吗
输出：图片中的文字信息是：“Tank Destroyer”。

输入：给图片做个总结
输出：这张图片显示了一辆坦克，上面有“T-34”的字样，表明这是一辆T-34坦克。T-34坦克是苏联在第二次世界大战期间使用的一种著名坦克，以其坚固的设计和强大的火力而闻名。

而图片跟WOT完全没任何关联

### Reproduction

```python
if __name__ == "__main__":
    txt_list = ["图片里说了什么东西", "图片里有什么事物", "图片里有什么文字信息吗", "给图片做个总结"]
    model_path = os.path.join(ROOT_DIR, "model", "InternVL2-26B")
    model = AutoModel.from_pretrained(
        InternVL2.model_path,
        torch_dtype=torch.bfloat16,
        low_cpu_mem_usage=True,
        trust_remote_code=True, quantization_config=BitsAndBytesConfig(load_in_4bit=True), device_map="cuda:1").eval()
    tokenizer = AutoTokenizer.from_pretrained(InternVL2.model_path, trust_remote_code=True)
    generation_config = dict(
        num_beams=1,
        max_new_tokens=1024,
        do_sample=False,
    )
    pixel_values = load_image("123.jpg", max_num=6).to(device=lvm_device, dtype=torch.bfloat16)
    for t in txt_list:
        response, history = model.chat(tokenizer, pixel_values, f"<image>\n{t}", generation_config, history=None, return_history=True)
        print(response)
```

### Environment

```Shell
镜像：pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
transformers==4.42.4
RTX 3090

8B的模型没出现这个问题，只有26B出现了
```

**Comment by czczup** [comment]
因为6B的ViT不能做bitsandbytes的4bit量化，量化误差太大了

**Comment by wciq1208** [comment]
> 因为6B的ViT不能做bitsandbytes的4bit量化，量化误差太大了

请问一下AWQ的精度可以吗，我看huggingface上有76B的AWQ
