### ISSUE TITLE
GeoQA+ dataset link is not working

### ISSUE THREAD

**Issue by oroojlooy** [OpenGVLab/InternVL#402]
The google drive link for the GeoQA+ dataset is not working. It says: 
```
Sorry, the file you have requested does not exist.

Make sure that you have the correct URL and the file exists.
```

**Comment by czczup** [comment]
You can download it from here: https://huggingface.co/OpenGVLab/InternVL/resolve/main/geoqa%2B_images.zip

See more detailed information in here: https://internvl.readthedocs.io/en/latest/internvl1.2/reproduce.html

**Comment by oroojlooy** [comment]
Thanks for the quick reply. 
Previously, there were two links for this dataset: 
`- GeoQA+: [GeoQA+](https://drive.google.com/file/d/1KL4_wIzr3p8XSKMkkLgYcYwCbb0TzZ9O/view) [images](https://huggingface.co/OpenGVLab/InternVL/resolve/main/geoqa%2B_images.zip)`
So, the other dataset is not required?

**Comment by oroojlooy** [comment]
Besides, a similar issue exists over the SAM dataset. When I run the pretrain stage, I get a lot of errors on not finding image errors like: 
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/afshin/InternVL/internvl_chat/playground/data/sam/images/sa_23647.jpg'
Failed to load image: playground/data/sam/images/sa_23647.jpg, the dataset is: sharegpt4v_instruct_gpt4-vision_cap100k
[Errno 2] No such file or directory: '/home/afshin/InternVL/internvl_chat/playground/data/sam/images/sa_23960.jpg' sharegpt4v_instruct_gpt4-vision_cap100k
```
How can we get the whole SAM dataset that is used in `sharegpt4v_instruct_gpt4-vision_cap100k.jsonl`?

**Comment by czczup** [comment]
> Thanks for the quick reply. Previously, there were two links for this dataset: `- GeoQA+: [GeoQA+](https://drive.google.com/file/d/1KL4_wIzr3p8XSKMkkLgYcYwCbb0TzZ9O/view) [images](https://huggingface.co/OpenGVLab/InternVL/resolve/main/geoqa%2B_images.zip)` So, the other dataset is not required?

The first link was originally the original GeoQA+ dataset, presumably provided by the original author. I’m not sure why it became invalid. The second link is the GeoQA+ dataset after I converted the format. For training, you can directly use the converted one.

**Comment by czczup** [comment]
To download the ShareGPT4V dataset, you can refer to their original documentation [here](https://github.com/InternLM/InternLM-XComposer/blob/main/projects/ShareGPT4V/docs/Data.md). This document should provide detailed instructions on how to access and download the dataset.

**Comment by oroojlooy** [comment]
Thanks for the link and explanations!

**Comment by njucckevin** [comment]
Hi, 
Thanks for your good work!  Does anyone know where can I find the annotation of GeoQA+? Since the original link in GeoQA+ Github is invalid and the link provided in this issue seems only contain the images.
And additionally, is there an English version of the GeoQA+ dataset?

**Comment by willpat1213** [comment]
> Hi, Thanks for your good work! Does anyone know where can I find the annotation of GeoQA+? Since the original link in GeoQA+ Github is invalid and the link provided in this issue seems only contain the images. And additionally, is there an English version of the GeoQA+ dataset?

https://huggingface.co/OpenGVLab/InternVL/resolve/main/playground.zip
