### ISSUE TITLE
performance camparison between internvit-300m, siglip, and eva clip

### ISSUE THREAD

**Issue by annopackage** [OpenGVLab/InternVL#406]
hi, thanks for your great work. I wonder if you have compare your small vit-300m-448px model with other clip models.

**Comment by czczup** [comment]
Hello,

Thank you for your interest. At this time, we have not yet conducted a comprehensive comparison between InternViT-300M and other vision models. What we do know is that using InternViT-300M can achieve state-of-the-art performance.

Best regards.
