### ISSUE TITLE
[Feature] Colbert(ColPali-like) support

### ISSUE THREAD

**Issue by VoVAllen** [OpenGVLab/InternVL#408]
### Motivation

https://github.com/illuin-tech/colpali

Recently Colbert+PaliGemma showed huge improvement on pdf file retrieval by using multimodal model instead of OCR+LLM. Would be nice if InternVL can support Colbert-like usage for downstream retrieval tasks.

**Comment by czczup** [comment]
Hi, thanks for your advice.
