### ISSUE TITLE
intervl2微调

### ISSUE THREAD

**Issue by wangwang110** [OpenGVLab/InternVL#411]
![image](https://github.com/user-attachments/assets/a839aa9c-018c-406c-a2e4-5a7dc14d68a2)
 请问下，我在ntervl2-4b基础上使用这个脚本微调
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/hermes2_yi34b/internvl_chat_v1_2_hermes2_yi34b_448_res_finetune_continue_lora.sh 
会跑到上图中的NotImplemented哪里？怎么处理？用Phi3ForCausalLM吗？
![image](https://github.com/user-attachments/assets/05d2e6d9-3b02-4f54-a2c7-0b758226350d)

**Comment by wangwang110** [comment]
或者说我想微调intervl2_4b的话，我需要用哪个shell脚本呢？ https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/shell

**Comment by czczup** [comment]
您可以拉一下最新的代码，按照这个文档的说明进行微调，所有脚本我都测试过可以正常运行:

https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html
