### ISSUE TITLE
循环多次单图单轮对话后出现out of memory，请问这是什么原因造成的？

### ISSUE THREAD

**Issue by Qigqi** [OpenGVLab/InternVL#413]
``   for result in tqdm(json_results):

        image_path = os.path.join(args.image_folder, image_filename)

        if os.path.exists(image_path):

            pixel_values = load_image(image_path, max_num=6).to(torch.bfloat16).cuda()
            response = model.chat(tokenizer, pixel_values, question, generation_config)
            print(f'Question:{json_question}')
            print(f'Assistant: {response}')

            torch.cuda.empty_cache()

**Comment by Qigqi** [comment]
已解决

**Comment by KnightHand** [comment]
求问，怎么解决的？

> 已解决
