### ISSUE TITLE
[Docs] InternVL2 1B evaluation results

### ISSUE THREAD

**Issue by wangbo-zhao** [OpenGVLab/InternVL#414]
### 📚 The doc issue

Hello. I run InternVL2 1B on textQA following https://github.com/OpenGVLab/InternVL/blob/main/document/How_to_evaluate_internvl_chat_v1_5.md
GPUS=8 bash evaluate.sh model_ckpts/models--OpenGVLab--InternVL2-1B  vqa-textvqa-val-ocr --dynamic --max-num 24

and onlyget 0.6046 acc which is much lower than 
![image](https://github.com/user-attachments/assets/493fd9ca-fe34-436b-a08f-7206484cba2c)

the results you provide.
![image](https://github.com/user-attachments/assets/dbbe06cb-64e7-4656-8244-4fa25fe7cd4e)

I would like to know if there is any problem. Thanks.

**Comment by wangbo-zhao** [comment]
I solve this problem by changing vqa-textvqa-val-ocr to vqa-textvqa-val.   It looks that the ocr tokens are not useful fir InterVL.

**Comment by wangbo-zhao** [comment]
It would be highly appreciated if the authors could provide a readme for the evaluation of InternVL2. Thanks.🤔

**Comment by czczup** [comment]
Hi, the document of evaluating InternVL2 is provided at here: 
https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html
