### ISSUE TITLE
[Docs] QLLaMA in newer versions of InternVL

### ISSUE THREAD

**Issue by oroojlooy** [OpenGVLab/InternVL#418]
### 📚 The doc issue

I read the paper of the InternVL 1.5 report, and it looks like that the QLLaMA is not available in the architecture of InternVL anymore as the language middleware in newer version of InternVL. Is this a correct observation? 
If so, do you use vision+MLP+LLM architecture?

**Comment by czczup** [comment]
Yes, we no longer use QLLaMA as middleware in InternVL 1.5; We use vision+MLP+LLM architecture.
