### ISSUE TITLE
[Docs] about License and Commercial Use

### ISSUE THREAD

**Issue by vietpho** [OpenGVLab/InternVL#421]
### 📚 The doc issue

Hi,

I have read the README and blog, and it seems that the InternVL family models have been trained using the ShareGPT dataset. From what I understand, any checkpoints trained with ShareGPT cannot be used for commercial purposes.

Specifically, I've seen the following license information regarding ShareGPT:
```
Code License Data License Usage and License Notices: The data and checkpoint are intended and licensed for research use only. They are also restricted to uses that follow the license agreement of LLaMA, Vicuna, and GPT-4. The dataset is CC BY NC 4.0 (allowing only non-commercial use) and models trained using the dataset should not be used outside of research purposes.

```

Given this, does it mean that all models in the InternVL family are not allowed for commercial use?

Thank you.

**Comment by czczup** [comment]
We no longer use the ShareGPT dataset in training for InternVL2 series.

**Comment by vietpho** [comment]
So, what you're saying is that internvl2 models, including those used with LLaMA and Qwen that allow commercial use based on user count, are commercially usable, except for LLaVA, which is not. Is that correct?

Additionally, is it impossible to use internvl2-pro without an API? I want to use it for commercial purposes, not just research.

Is it permissible to use internvl2-pro commercially, even if it requires using the API?
