### ISSUE TITLE
动态分辨率

### ISSUE THREAD

**Issue by echo840** [OpenGVLab/InternVL#422]
为什么在使用动态分辨率时，会保持图像的长宽比最接近而不是分辨率大小更接近呢？比如一张（300，400）分辨率的图片会被internvl resize成（3x448，4x448）,为什么不resize成（448，448）从而保证分辨率大小更接近呢？

**Comment by czczup** [comment]
Thank you for your suggestion. Of course, this is possible. Dynamic resolution strategy is also one of the main areas of improvement we are currently focusing on.

**Comment by echo840** [comment]
我有点不明白为什么是保持图像的长宽比最接近而不是分辨率大小更接近。您这样做有什么考虑吗？
