### ISSUE TITLE
[Bug] internVL2-llama3.1 76B 加载时候有bug 4卡机器只会用到第一张卡

### ISSUE THREAD

**Issue by CSEEduanyu** [OpenGVLab/InternVL#425]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

 internVL2-llama3.1 76B 加载时候有bug 4卡机器只会用到第一张卡

### Reproduction

 internVL2-llama3.1 76B 加载时候有bug 4卡机器只会用到第一张卡

### Environment

```Shell
internVL2-llama3.1 76B 加载时候有bug 4卡机器只会用到第一张卡
```

**Comment by chchenhui** [comment]
您好，请问这个问题解决了吗，我也遇到了类似的问题
