### ISSUE TITLE
InternVL2在微调时需要训练视觉端吗

### ISSUE THREAD

**Issue by ghntd** [OpenGVLab/InternVL#426]
我们发现在新公开的InternVL2微调脚本中，视觉端的参数被冻结了，而在1.5的模型中这部分参数是参与训练的。并且我们的实验也发现打开视觉端的训练有很明显的收益。想问一下这一设置不适合InternVL2吗。

**Comment by czczup** [comment]
不是，在这些脚本中关掉ViT的训练只是为了省点显存，总体看肯定是打开来训练更好的。

这些脚本只是一个能跑的实例，不是最优的超参数，您可以通过调参获得最好的性能。
