### ISSUE TITLE
你好，InterVL2-4b支持image caption任务的微调以及评测吗[Docs] 

### ISSUE THREAD

**Issue by afasijbfk** [OpenGVLab/InternVL#428]
### 📚 The doc issue

你好，InterVL2-4b支持image caption任务的微调以及评测吗

**Comment by czczup** [comment]
您好，支持的，您可以使用COCO Caption或者其他caption数据进行微调。

微调教程见：https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html
Caption评测数据准备：https://internvl.readthedocs.io/en/latest/get_started/eval_data_preparation.html
评测命令：https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html
