### ISSUE TITLE
During the process of using InternVL-Chat-V1.1, an error occurred

### ISSUE THREAD

**Issue by Ranceeeee** [OpenGVLab/InternVL#43]
Hello, I encountered an error related to model deployment while using the code you provided for testing InternVL-Chat-V1.1, which seems to be related to model_base and model_name. 
Could you please tell me where I can find reference code for evaluating InternVL-Chat-V1.1? Thanks!

**Comment by czczup** [comment]
Hi, the evaluation code for InternVL-Chat-V1.1 is [here](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#-how-to-evaluate).

Could you provide me the specific error information?
