### ISSUE TITLE
[Bug] load video frames bug.

### ISSUE THREAD

**Issue by xmy0916** [OpenGVLab/InternVL#431]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/dataset.py#L143
![image](https://github.com/user-attachments/assets/cf0c16ef-bbe3-44e5-908f-3b6797fcf630)

### Reproduction

这直接sort文件名不太行吧，视频帧的顺序都乱了，例如[11.jpg,2.jpg] sort完是11.jpg在前面

### Environment

```Shell
123
```

**Comment by czczup** [comment]
感谢反馈！

**Comment by czczup** [comment]
这个问题已经修复
