### ISSUE TITLE
InternVL2测评问题

### ISSUE THREAD

**Issue by bang123-box** [OpenGVLab/InternVL#432]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

您好，我在用internvl2进行benchmark的测评，使用internvl_chat_llava/scripts_internvl/eval/textvqa.sh之后出现了出现两个问题，第一个是加载模型的时候非常慢卡在这里“/InternVL/internvl_chat_llava/llava/model/builder.py", line 103，卡在这里；第二个同样是在这个文件137行，vision_tower = model.get_vision_tower()这里出来的vision_tower是None,就导致了下面的if语句出错

### Reproduction

internvl_chat_llava/scripts_internvl/eval/textvqa.sh

### Environment

```Shell
None
```

### Error traceback

```Shell
None
```

**Comment by czczup** [comment]
internvl_chat_llava是InternVL 1.0，不是InternVL2

**Comment by czczup** [comment]
InternVL2的评测可以按照这个文档：https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html
或者更方便点，直接用[VLMEvalKit](https://github.com/open-compass/VLMEvalKit)评测
