### ISSUE TITLE
[Bug] 使用lora训练得到的InternVL2无法加载并测试

### ISSUE THREAD

**Issue by pangr** [OpenGVLab/InternVL#433]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

使用lora训练得到的InternVL2无法加载并测试

### Reproduction

使用常规的模型加载

### Environment

```Shell
普通的hunggingface推理
```

**Comment by czczup** [comment]
应该需要把lora权重合并一下

**Comment by smurf-1119** [comment]
怎么合并呢，有脚本吗

**Comment by czczup** [comment]
在这里写了个教程：https://internvl.readthedocs.io/en/latest/tutorials/coco_caption_finetune.html#merging-lora-weights
合并脚本是这个：https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/tools/merge_lora.py
这个是刚刚传上去的，注意拉一下最新的代码

**Comment by THU-Kingmin** [comment]
Doesn't work!
![image](https://github.com/user-attachments/assets/66d5a5b6-8261-4743-bae8-494e40d2a84f)

**Comment by HongyuCao3** [comment]
same problem

> Doesn't work! ![image](https://private-user-images.githubusercontent.com/43465723/367567204-66d5a5b6-8261-4743-bae8-494e40d2a84f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NDQxMTEsIm5iZiI6MTczMzU0MzgxMSwicGF0aCI6Ii80MzQ2NTcyMy8zNjc1NjcyMDQtNjZkNWE1YjYtODI2MS00NzQzLWJhZTgtNDk0ZTQwZDJhODRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDAzNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZDRiMjg2OTg3YmE2MTNmZmZjYzUyNGYxZTg4NmMwMzFlZDU5MjI2YWRmNDYzMmViNTU0NDFhZmEwMWY4Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mz6qoeqTgPWzlWn6wwDAi7kYS1lDpcAw3WUpiO5qVCc)
