### ISSUE TITLE
using InternVL-Chat for multimodal chat : `Multiple GPUs` section.

### ISSUE THREAD

**Issue by LSKhappychild** [OpenGVLab/InternVL#435]
Thanks for your great work.

As I'm trying to do some testing, I took a look at the section "using InternVL-Chat for multimodal chat".

As a comment, there was a saying : 

Otherwise, you need to load a model using multiple GPUs, please refer to the `Multiple GPUs` section.

Where can I find that 'Multiple GPUs' section?

Thanks a lot, always

**Comment by czczup** [comment]
Hi, see here: https://internvl.readthedocs.io/en/latest/internvl2.0/quick_start.html#multiple-gpus

**Comment by LSKhappychild** [comment]
Thanks for your help!
