### ISSUE TITLE
[Bug] 多图时本地推理和用提供的demo推理结果不一致

### ISSUE THREAD

**Issue by cxmscb** [OpenGVLab/InternVL#436]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

测试版本：26B。加载图片的max_num改为12，generation_config和网页的一致，transformer的版本4.37.2。
请问可以提供一下demo运行的多图推理代码吗，感谢。

### Reproduction

Na

### Environment

```Shell
Na
```

### Error traceback

```Shell
Na
```

**Comment by cxmscb** [comment]
请问一下系统提示在提问中怎么添加？

**Comment by czczup** [comment]
您可以按照这个指南试试在本地部署新的在线demo: https://internvl.readthedocs.io/en/latest/get_started/local_chat_demo.html

demo里的多图处理逻辑确实有些专门的改动，主要在这：https://github.com/OpenGVLab/InternVL/blob/main/streamlit_demo/model_worker.py#L282

就是要在合适的时候插入一些`Image-1:`, `Image-2:`这样的label提示模型
