### ISSUE TITLE
Will you release the pretrained weights of the MLP projector after the Stage 1 pretraining of InternVL2?

### ISSUE THREAD

**Issue by gcd19** [OpenGVLab/InternVL#437]
Thank you for your excellent job! 

Another question: since the InternVL2 blog does not mention any updates to the ViT models (InternViT-300M-448px / InternViT-6B-448px-V1-5), I wonder if you have made any updates to them. Can I just use `OpenGVLab/InternViT-300M-448px` from HuggingFace?

**Comment by yuecao0119** [comment]
Thanks for your question.
Question 1: Please refer to [InternVL2-Pretrain-Models](https://huggingface.co/OpenGVLab/InternVL2-Pretrain-Models).
Question 2: Please refer to [#603](https://github.com/OpenGVLab/InternVL/issues/603).
Hope this helps you.
