### ISSUE TITLE
Dataset release?

### ISSUE THREAD

**Issue by luohao123** [OpenGVLab/InternVL#44]
Dataset release?

**Comment by czczup** [comment]
Hi, we release the training data for InternVL-Chat-V1.2. You can get then from [here](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#prepare-training-datasets). 

Or do you want to get the data described in table3 of the paper?

**Comment by luohao123** [comment]
@czczup  Yes, data in table3
