### ISSUE TITLE
GPU显存的最低要求[Docs] 

### ISSUE THREAD

**Issue by fangxin2github** [OpenGVLab/InternVL#441]
### 📚 The doc issue

https://internvl.readthedocs.io/en/latest/internvl1.0/internvl_g.html
文档中的表格
![image](https://github.com/user-attachments/assets/d1a0ec3b-dc4c-43eb-b33b-72ac8f3afb66)
GPUs for training是要求每个GPU显存是32G，但是Required GPU memory 要求24G。要以哪个为准呢？GPU的显存最低要求是4*32G还是4*24G？

**Comment by czczup** [comment]
我这里看正好消耗了24G显存，只有24G显存的卡不一定跑得起来

**Comment by fangxin2github** [comment]
明白了，谢谢
