### ISSUE TITLE
Data size for InternVL 1.5 and 2.0

### ISSUE THREAD

**Issue by oroojlooy** [OpenGVLab/InternVL#449]
### 📚 The doc issue

I did not see any info about the data size for the pre-train and fine-tuning stages for InternVL 1.5 and 2.0. 
Do you use the same dataset and sizes that you use for InternVL 1.2 plus? i.e., 39.3M for pretraining and 12M for fine-tuning?

**Comment by czczup** [comment]
Hello, if this issue should be resolved by now?

**Comment by lll2343** [comment]
The data size for fine-tuning is compared in the latest InternVL 2.5 Technical Report[https://huggingface.co/papers/2412.05271](https://huggingface.co/papers/2412.05271), with statistics for 1.5, 2.0, and 2.5 available in **Figure 7**.
