### ISSUE TITLE
Reason for setting llm backbone to eval mode when finetuning?

### ISSUE THREAD

**Issue by royzhang12** [OpenGVLab/InternVL#456]
Hi, @czczup 
Thank you for providing such a wonderful work. Just have a question about the  detail of the [finetune code](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py).  If using lora, you set the llm to eval model while the vision backbone not. Would you mind to share the reason for doing that? 

![image](https://github.com/user-attachments/assets/e9b6d0c0-0e15-43ae-9019-1c4064200f67)

**Comment by czczup** [comment]
See #277
