### ISSUE TITLE
Wrong model name on internvl2_8b fine-tuning code

### ISSUE THREAD

**Issue by oroojlooy** [OpenGVLab/InternVL#457]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

It looks like that the model name is not the correct one in the fine-tuning script for model=`internvl2_8b`, where it should be `[internlm2_5-7b-chat](https://huggingface.co/internlm/internlm2_5-7b-chat)` while it is `--model_name_or_path "./pretrained/InternVL2-2B"`:
`https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/internvl2.0/2nd_finetune/internvl2_8b_internlm2_7b_dynamic_res_2nd_finetune_lora.sh`

### Reproduction

N/A

### Environment

```Shell
N/A
```

**Comment by czczup** [comment]
Hi, thanks for your feedback. This typo has been fixed.
