### ISSUE TITLE
报错：flash_attn_2_cuda

### ISSUE THREAD

**Issue by CachCheng** [OpenGVLab/InternVL#467]
/home/ubuntu/miniconda3/envs/llm/lib/python3.9/site-packages/[flash_attn_2_cuda.cpython-39-x86_64-linux-gnu.so](http://flash_attn_2_cuda.cpython-39-x86_64-linux-gnu.so/): undefined symbol: _ZN2at4_ops9_pad_enum4callERKNS_6TensorEN3c108ArrayRefINS5_6SymIntEEElNS5_8optionalIdEE

请问flash-attention安装有问题，怎么解决呢？

**Comment by czczup** [comment]
这个是因为flash attention没有安装成功，建议您卸载之后重新安装试试
