### ISSUE TITLE
InternVL2-Pro is amazing!

### ISSUE THREAD

**Issue by cxmscb** [OpenGVLab/InternVL#469]
I have made some experiments on the chat demo, and found InternVL2-Pro is amazing! Could you tell how large InternVL2-Pro is and when to release its model? And will there also be InternVL2-Pro-8B and InternVL2-Pro-26B?

**Comment by czczup** [comment]
Hi, the InternVL2-Pro model is currently not planned for release because we are planning to open-source even better model weights soon. Stay tuned!

**Comment by URRealHero** [comment]
> Hi, the InternVL2-Pro model is currently not planned for release because we are planning to open-source even better model weights soon. Stay tuned!

May I ask do InternVL2-Pro support video reasoning? how do I input a video into it?
