### ISSUE TITLE
[Bug] merge_lora.py 报错

### ISSUE THREAD

**Issue by chopinchenx** [OpenGVLab/InternVL#472]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

File "/home/InternVL2/internvl_chat/internvl/model/internvl_chat/configuration_internvl_chat.py", line 9, in <module>
    from internvl.model.internlm2.configuration_internlm2 import InternLM2Config
ModuleNotFoundError: No module named 'internvl'

### Reproduction

python3 tools/merge_lora.py work_dirs/internvl_chat_v2_0/internvl2_8b_lora/ work_dirs/internvl_chat_v2_0/internvl2_8b_lora_merge

### Environment

```Shell
CUDA 12.0
```

**Comment by chopinchenx** [comment]
需要修改几处代码，添加 internvl_chat.包

**Comment by shiva-vardhineedi** [comment]
how did you solve this?

**Comment by chopinchenx** [comment]
> how did you solve this?

yeah. i use pycharm ide to run script. and you need to modify some lines that add 'internvl_chat.' prefix. 

the files are as follows:
merge_lora.py: line 2
configuration_internvl_chat.py: line 9-10
modeling_internvl_chat.py: line 12-14

**Comment by Apricot1225** [comment]
or you can simply copy the merge_lora.py from intern_chat/tools to the intern_chat/ folder, which is the same folder with internvl module.  

then run the command in folder intern_chat/ as python3 merge_lora.py work_dirs/internvl_chat_v2_0/internvl2_8b_lora/ work_dirs/internvl_chat_v2_0/internvl2_8b_lora_merge
