### ISSUE TITLE
[Docs] image-text retrieval

### ISSUE THREAD

**Issue by azuredsky** [OpenGVLab/InternVL#473]
### 📚 The doc issue

I'm confused about the internvl_c_retrieval and internvl_g_retrieval ,what's the different? and the video_retrieval can an example replace it?

### Suggest a potential alternative/fix

could you show me some  image-text retrieval examples code

**Comment by czczup** [comment]
Hi, see here to use the retrieval model:
https://huggingface.co/OpenGVLab/InternVL-14B-224px#model-usage
