### ISSUE TITLE
[Bug] KeyError: 'internvl_chat'

### ISSUE THREAD

**Issue by ATing0203** [OpenGVLab/InternVL#475]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

当使用transformers==4.37.2进行模型加载时报错：
```
The checkpoint you are trying to load has model type `internvl_chat` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
KeyError: 'internvl_chat'
```

### Reproduction

```
from transformers import AutoModel, AutoTokenizer
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    device_map=device_map).eval()
```

### Environment

```Shell
tokenizers                    0.15.2
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.1
torch                         2.0.1
torchaudio                    2.0.2
torchvision                   0.15.2
tornado                       6.4.1
tqdm                          4.66.4
traitlets                     5.14.3
transformers                  4.37.2
transformers-stream-generator 0.0.5
triton                        2.0.0
```

**Comment by czczup** [comment]
请问您使用的路径是类似`OpenGVLab/InternVL2-1B`这样的路径吗，还是微调过的路径？

**Comment by ATing0203** [comment]
> 请问您使用的路径是类似`OpenGVLab/InternVL2-1B`这样的路径吗，还是微调过的路径？

感谢回复，我用的是微调后的路径`/export/work_dirs/internvl_chat_v1_5_finetune_lora`

**Comment by czczup** [comment]
您好，微调后的模型如果想要使用AutoModel来加载，需要您首先合并lora权重，然后把预训练模型里面的python代码复制到对应的文件夹里。你可以按照这个教程进行这些操作：https://internvl.readthedocs.io/en/latest/tutorials/coco_caption_finetune.html#merging-lora-weights

或者其实可以直接`from internvl.model.internvl_chat import InternVLChatModel`，这样不需要做lora合并和AutoModel封装，也可以加载模型

**Comment by ATing0203** [comment]
感谢！参照您的lora权重合并方法，现在已经可以正常使用AutoModel来加载了。
