### ISSUE TITLE
关于InternVL2微调使用的数据集 

### ISSUE THREAD

**Issue by QingrongH** [OpenGVLab/InternVL#477]
### 📚 The doc issue

请问InternVL2的grounding和多图任务使用了哪些数据集？预训练和微调阶段都涵盖了这两类任务吗？

**Comment by yuecao0119** [comment]
感谢您的提问，可以关注我们InternVL2.5的[技术报告](https://huggingface.co/papers/2412.05271)，其中4.3章节详细罗列了我们预训练和微调阶段使用的数据集。
