### ISSUE TITLE
[Feature] 还有一个问题，streamlit run app.py启动后无法选择模型

### ISSUE THREAD

**Issue by lckj2009** [OpenGVLab/InternVL#480]
### Motivation

选择模型那里是灰色的，不能选择，是什么原因呢？麻烦请教一下怎么弄。模型用的是InternVL2-Llama3-76B。路径如下图：

### Related resources

请问下图中是不是路径不对？/root/InternVL/InternVL2-Llama3-76B 里面是 OpenGVLab/InternVL2-Llama3-76B 模型文件和其他文件。

### Additional context

![ubuntulujing](https://github.com/user-attachments/assets/632411a0-05cb-4658-a27e-18c46f8ba69d)

![无法选择模型](https://github.com/user-attachments/assets/78db5f3f-f546-4c6b-92e9-2418b4026c33)

**Comment by lckj2009** [comment]
还是说，这个私有化部署也只能支持26B模型，不支持 InternVL2-Llama3-76B ？？？

**Comment by iamyanyanyan** [comment]
26b的模型也出现这个情况，请问你解决了吗？

**Comment by lckj2009** [comment]
> 是fastapi接口没调试好，调试好后就可以了。

https://internvl.readthedocs.io/en/latest/get_started/local_chat_demo.html  这里没说要调试 fastapi接口 呀，具体要怎么做呢？我是启动了 Step 2: Start the Streamlit Web Server 和 Step 3: Start the Controller。之后要启动 fastapi吗？在哪里启动

**Comment by iamyanyanyan** [comment]
> > 是fastapi接口没调试好，调试好后就可以了。
> 
> https://internvl.readthedocs.io/en/latest/get_started/local_chat_demo.html 这里没说要调试 fastapi接口 呀，具体要怎么做呢？我是启动了 Step 2: Start the Streamlit Web Server 和 Step 3: Start the Controller。之后要启动 fastapi吗？在哪里启动

我是在controller.py里app=fastAPI()加了
@app.get("/")
async def read_root():
    return('get':200}

对了，你要用76b的模型不用量化模型吗。我用量化的24b显卡都占了大概70G了。
然后我试过如果用量化模型好像不能用streamlit，所以最后我调试好了streamlit界面但最后还是选择了用lmdeploy+gradio部署的。

**Comment by lckj2009** [comment]
> > > 是fastapi接口没调试好，调试好后就可以了。
> > 
> > 
> > https://internvl.readthedocs.io/en/latest/get_started/local_chat_demo.html 这里没说要调试 fastapi接口 呀，具体要怎么做呢？我是启动了 Step 2: Start the Streamlit Web Server 和 Step 3: Start the Controller。之后要启动 fastapi吗？在哪里启动
> 
> 我是在controller.py里app=fastAPI()加了 @app.get("/") async def read_root(): return('get':200}
> 
> 对了，你要用76b的模型不用量化模型吗。我用量化的24b显卡都占了大概70G了。 然后我试过如果用量化模型好像不能用streamlit，所以虽然我调试好了streamlit界面但最后还是选择了用lmdeploy+gradio部署的。

嗯，后来我没用76B，我是直接尝试了mini的4B，之后也尝试了VL2的8B。都可以。24B的话，估计我那显卡撑不住。

**Comment by lckj2009** [comment]
> lmdeploy+gradio部署

另外，我之前尝试过 lmdeploy+gradio部署，但是报错了，所以是用其他方式部署的
