### ISSUE TITLE
[Docs] Seems to be an error in the document

### ISSUE THREAD

**Issue by Zzzzzzzzzzj** [OpenGVLab/InternVL#484]
### 📚 The doc issue

In "Enhancing InternVL2 on COCO Caption Using LoRA Fine-Tuning" tutorial, "Next, we’ll fine-tune the InternVL2-2B model using LoRA. Execute the following command for fine-tuning:

GPUS=8 PER_DEVICE_BATCH_SIZE=4 sh shell/internvl2.0/2nd_finetune/internvl2_2b_internlm2_1_8b_dynamic_res_2nd_finetune_lora.sh" is wrong.

### Suggest a potential alternative/fix

I think it should be "GPUS=8 PER_DEVICE_BATCH_SIZE=4 sh shell/internvl2.0/2nd_finetune/internvl2_2b_internlm2_1_8b_dynamic_res_2nd_finetune_lora_coco.sh"

**Comment by czczup** [comment]
Thank you very much for your attention to detail. I have already fixed this error in the document.
