### ISSUE TITLE
[Feature] Is internvl trained to output json format output ?

### ISSUE THREAD

**Issue by shubham303** [OpenGVLab/InternVL#485]
### Motivation

JSON format output from an VLM provides structured data, making it easier to parse and integrate with other systems. In zero-shot classification, JSON allows the VLM to clearly define categories and attributes, facilitating accurate and efficient classification without needing additional post processing.

**Comment by zyandtom** [comment]
@czczup could you please provide any json formatted training data sample, i'm curious about how to train it

**Comment by shubham303** [comment]
Take a look at my huggingface account https://huggingface.co/shubh303

**Comment by zyandtom** [comment]
> Take a look at my huggingface account https://huggingface.co/shubh303

thx, is that internvl official format ?

**Comment by shubham303** [comment]
No. You will need to update it. Although I think that should be straightforward
