### ISSUE TITLE
关于40B模型与76B模型的对话模版问题

### ISSUE THREAD

**Issue by ghntd** [OpenGVLab/InternVL#488]
InternVL2的76B模型的基座是LLama，但是微调脚本中使用的对话模版都使用的InternLM2的风格，而40B模型虽然在微调脚本里用的Hermes-2的风格，但是其在LMdeploy中还是用的InternLM2的风格。然而我观察这两者的token id好像都不太对。请问二者在训练时应该用哪一种对话模版

**Comment by czczup** [comment]
这两个对话模板在推理的时候是一样的，混用没有关系。
