### ISSUE TITLE
[Bug] 回答的文字一直不断的重复

### ISSUE THREAD

**Issue by molu-ggg** [OpenGVLab/InternVL#490]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

回答的文字一直不断的重复，是否预训练存在一些问题呢？

### Reproduction

`User: <image>
以马桶为参照物，描述图片中其他物体的相对位置关系.
Assistant: 以马桶为参照物，图片中其他物体的相对位置关系如下：

1. **马桶左侧**：
   - 上方有一个黑色毛巾架，上面挂着一条白色毛巾。
   - 毛巾架的下方有一个白色淋浴喷头。

2. **马桶右侧**：
   - 有一个白色的马桶刷，放在马桶旁边。
   - 马桶旁边有一个白色的马桶刷桶。
   - 马桶旁边还有一个白色的马桶刷盖。

3. **马桶前方**：
   - 马桶前方有一个白色的马桶刷。

4. **马桶右侧**：
   - 有一个白色的马桶刷盖。

5. **马桶右侧**：
   - 有一个白色的马桶刷。

6. **马桶右侧**：
   - 有一个白色的马桶刷盖。

7. **马桶右侧**：
   - 有一个白色的马桶刷。

8. **马桶右侧**：
   - 有一个白色的马桶刷盖。

9. **马桶右侧**：
   - 有一个白色的马桶刷。

10. **马桶右侧**：
    - 有一个白色的马桶刷盖。

11. **马桶右侧**：
    - 有一个白色的马桶刷。

12. **马桶右侧**：
    - 有一个白色的马桶刷盖。

13. **马桶右侧**：
    - 有一个白色的马桶刷。

14. **马桶右侧**：
    - 有一个白色的马桶刷盖。

15. **马桶右侧**：
    - 有一个白色的马桶刷。

16. **马桶右侧**：
    - 有一个白色的马桶刷盖。

17. **马桶右侧**：
    - 有一个白色的马桶刷。

18. **马桶右侧**：
    - 有一个白色的马桶刷盖。

19. **马桶右侧**：
    - 有一个白色的马桶刷。

20. **马桶右侧**：
    - 有一个白色的马桶刷盖。

21. **马桶右侧**：
    - 有一个白色的马桶刷。

22. **马桶右侧**：
    - 有一个白色的马桶刷盖。

23. **马桶右侧**：
    - 有一个白色的马桶刷。

24. **马桶右侧**：
    - 有一个白色的马桶刷盖。

25. **马桶右侧**：
    - 有一个白色的马桶刷。

26. **马桶右侧**：
    - 有一个白色的马桶刷盖。

27. **马桶右侧**：
    - 有一个白色的马桶刷。

28. **马桶右侧**：
    - 有一个白色的马桶刷盖。

29. **马桶右侧**：
    - 有一个白色的马桶刷。

30. **马桶右侧**：
    - 有一个白色的马桶刷盖。

31. **马桶右侧**：
    - 有一个白色的马桶刷。

32. **马桶右侧**：
    - 有一个白色的马桶刷盖。

33. **马桶右侧**：
    - 有一个白色的马桶刷。

34. **马桶右侧**：
    - 有一个白色的马桶刷盖。

35. **马桶右侧**：
    - 有一个白色的马桶刷。

36. **马桶右侧**：
    - 有一个白色的马桶刷盖。

37. **马桶右侧**：
    - 有一个白色的马桶刷。

38. **马桶右侧**：
    - 有一个白色的马桶刷盖。

39. **马桶右侧**：
    - 有一个白色的马桶刷。

40. **马桶右侧**：
    - 有一个白色的马桶刷盖。

41. **马桶右侧**：
    - 有一个白色的马桶刷。

42. **马桶右侧**：
    - 有一个白色的马桶刷盖。

43. **马桶右侧**：
    - 有一个白色的马桶刷。

44. **马桶右侧**：
    - 有一个白色的马桶刷盖。

45. **马桶右侧**：
    - 有一个白色的马桶刷。

46. **马桶右侧**：
    - 有一个白色的马桶刷盖。

47. **马桶右侧**：
    - 有一个白色的马桶刷。

48. **马桶右侧**：
    - 有一个白色的马桶刷盖。

49. **马桶右侧**：
    - 有一个白色的马桶刷。

50. **马桶右侧**：
    - 有一个白色的马桶刷盖。

51. **马桶右侧**：
    - 有一个白色的马桶刷。

52. **马桶右侧**：
    - 有一个白色的马桶刷盖。

53. **马桶右侧**：
    - 有一个白色的马桶刷。

54. **马桶右侧**：
    - 有一个白色的马桶刷盖。

55. **马桶右侧**：
    - 有一个白色的`

### Environment

```Shell
INternVL-8B
```

**Comment by czczup** [comment]
您好，感谢您的反馈，这个问题主要还是因为训练数据中存在一些噪声，我们会继续清洗数据，在下一个版本中改进这个问题
