### ISSUE TITLE
torchrun --nproc-per-node=8 run.py   can not find run.py file

### ISSUE THREAD

**Issue by luyao-cv** [OpenGVLab/InternVL#494]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

torchrun --nproc-per-node=8 run.py   can not find run.py file

### Reproduction

torchrun --nproc-per-node=8 run.py   can not find run.py file

### Environment

```Shell
torch 2.0.1
```

### Error traceback

```Shell
torchrun --nproc-per-node=8 run.py   can not find run.py file
```

**Comment by czczup** [comment]
Hello, part of our evaluation was completed using VLMEvalKit. The `run.py` script is also provided by VLMEvalKit, and you can check it out here: [VLMEvalKit](https://github.com/open-compass/VLMEvalKit).
