### ISSUE TITLE
[Bug] 请教一下，书生2.0的最低pytorch版本要求是多少？要最低，因为想跟一个较旧的模型兼容

### ISSUE THREAD

**Issue by lzk9508** [OpenGVLab/InternVL#496]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

如题

### Reproduction

如题

### Environment

```Shell
如题
```

**Comment by czczup** [comment]
我这里用的最低的就是pytorch 2.0.1；Pytorch 1.x版本我不确定会不会有兼容性问题，您是想用pytorch 1.x吗
