### ISSUE TITLE
[Feature] InternVL2.0 Evaluation on MMIU benchmark

### ISSUE THREAD

**Issue by cxmscb** [OpenGVLab/InternVL#498]
### Motivation

For the evaluation, could you please add the MMIU benchmark(https://mmiu-bench.github.io/) in https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html?

**Comment by czczup** [comment]
Thanks for your suggestion, multi-image evaluation is really meaningful, I will add it soon.
