### ISSUE TITLE
[Feature] Tools Calling support

### ISSUE THREAD

**Issue by skywalkerfmc** [OpenGVLab/InternVL#499]
### Motivation

模型不支持Tools Calling吗

**Comment by czczup** [comment]
您好，可以按照我们使用的语言模型本身的tools calling的格式来调用工具，因为我们的训练中不太涉及到工具调用的数据，所以这部分的能力是又语言模型本身的预训练来支持的。在多模态的SFT之后，语言模型会在一定程度上保留原本的工具调用能力。
