### ISSUE TITLE
about interleaved data

### ISSUE THREAD

**Issue by coder4nlp** [OpenGVLab/InternVL#505]
The interleaved data from OmniCorpus was also utilized. Could you please provide an example to illustrate the data processing process? Thanks!

**Comment by yuecao0119** [comment]
Thank you for your question. 
For the overall multi-image data format, please refer to our [document](https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#multi-image-data). For interlaced image data, we do not move the <image> tag forward, but keep their original position in the sequence.
