### ISSUE TITLE
[Docs] Chat Data Format_多轮图文对话类是否支持

### ISSUE THREAD

**Issue by lysandre001** [OpenGVLab/InternVL#509]
### 📚 The doc issue

你好，我的数据是涉及到多轮对话并含图片的情况，请问internvl是否支持？数据示例如下
给定一张书籍图片
Q：请问这张图片可以分成多少个栏目？
A：这张图片可以分为三个栏目，因为xxxx
Q：这三个栏目的坐标分别是什么？<ref>栏目1</ref><ref>栏目2</ref><ref>栏目3</ref>
A: \n\n<ref>栏目 1</ref><box>[[1, 2, 269, 235]]</box>\n<ref>栏目 2</ref><box>[[1, 2, 269, 235]]</box>\n<ref>栏目 3</ref><box>[[1, 2, 269, 235]]</box>\n

**Comment by czczup** [comment]
你好，这种类型支持的，这就是单图的多轮对话，您可以看我们的数据格式文档：https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#single-image-data
