### ISSUE TITLE
[Feature] InternVL2如何有效的使用Grounding能力

### ISSUE THREAD

**Issue by scl-01** [OpenGVLab/InternVL#510]
### Motivation

在评估InternVL2的grounding能力时，我使用的是InternVL-Chat-V1-2-Plus中给出的prompt模板，但是效果很不理想，我希望了解InternVL2的grounding能力如何有效评估，以及输出的bbox的坐标范围和坐标形式

### Related resources

评估参考的是https://github.com/OpenGVLab/InternVL/issues/58

**Comment by czczup** [comment]
你好，Grounding能力的评估你可以参考我们评测refcoco的代码：https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/eval/refcoco/evaluate_grounding.py
