### ISSUE TITLE
[Docs] How much training resources are needed for 76B fine-tuning

### ISSUE THREAD

**Issue by THU-Kingmin** [OpenGVLab/InternVL#516]
### 📚 The doc issue

How much training resources are needed for 76B fine-tuning

**Comment by G-z-w** [comment]
We recommend at least 128 A100 GPUs when using zero3

**Comment by czczup** [comment]
If you want to fine-tune the full LLM, you need at least 32 GPUs with 80GB each; if you are only fine-tuning the Lora Adapter on the LLM, then 8 GPUs will suffice.
