### ISSUE TITLE
[Bug] 请问支持断点重新训练嘛

### ISSUE THREAD

**Issue by liuw20** [OpenGVLab/InternVL#517]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

请问支持断点重新训练嘛

### Reproduction

请问支持断点重新训练嘛

### Environment

```Shell
请问支持断点重新训练嘛
```

**Comment by czczup** [comment]
你好，支持的，这个是transformers trainer自带的功能

**Comment by czczup** [comment]
一种方法是把--overwrite_output_dir True 改成False，就会自动resume了，如果需要其他的resume方式可以查阅transformers的文档。

**Comment by linssonSUSUSU** [comment]
> 一种方法是把--overwrite_output_dir True 改成False，就会自动resume了，如果需要其他的resume方式可以查阅transformers的文档。

设置为False但是看起来是重新开始训练，也尝试了resume_from_checkpoint,然后会报错Error: loaded state dict contains a parameter group that doesn’t match the size of optimizer’s group

**Comment by Zxr1314** [comment]
> 一种方法是把--overwrite_output_dir True 改成False，就会自动resume了，如果需要其他的resume方式可以查阅transformers的文档。

断点续训后是否要把replacement设置为True呢，发现之前训练过的数据集会被直接跳过
