### ISSUE TITLE
MLP Training

### ISSUE THREAD

**Issue by BlueBlueFF** [OpenGVLab/InternVL#52]
From https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat#prepare-training-datasets, Is the mlp between llm and vit is random init?

**Comment by BlueBlueFF** [comment]
One more thing, I notice the LLava 1.6 is train all params in sft stage2, so i guess internvl-chat is trained as follow stage:
SFT Stage1: Train MLP in LLava 665k Pretrain(is v1.2/v1.2 plus use this)?
SFT Stage2 : Train Full model in LLava 665K or self collect sft data.

**Comment by czczup** [comment]
When conducting experiments for the paper, we initially utilized a setting akin to LLaVA-1.5, where we first trained the MLP and then trained the MLP + LLM. However, later on, we discovered that training the entire model together yielded better results. Therefore, in versions v1.1/v1.2, we adopted different settings.

**Comment by czczup** [comment]
In summary, for v1.2/v1.2 plus:
SFT Stage1: Trained on 8192 (batch size) x 4800 (iterations) =39.3M samples, including COYO, LAION, CC12M, CC3M, SBU, Wukong, GRIT, Objects365, OpenImages, and OCR data. Including tasks such as captioning, grounding, detection, and OCR.
SFT Stage2 : Train Full model in open-sourced 1.2M SFT data.

**Comment by zhouxincheng** [comment]
> In summary, for v1.2/v1.2 plus: SFT Stage1: Trained on 8192 (batch size) x 4800 (iterations) =39.3M samples, including COYO, LAION, CC12M, CC3M, SBU, Wukong, GRIT, Objects365, OpenImages, and OCR data. Including tasks such as captioning, grounding, detection, and OCR. SFT Stage2 : Train Full model in 1.2M (v1.2) or 12M (v1.2 plus) SFT data.
It confuses me that in SFT Stage1 and Stage2, did you train full model all the time  ?

**Comment by czczup** [comment]
SFT Stage1: Train the **MLP** on 8192 (batch size) x 4800 (iterations) =39.3M samples, including COYO, LAION, CC12M, CC3M, SBU, Wukong, GRIT, Objects365, OpenImages, and OCR data. Including tasks such as captioning, grounding, detection, and OCR.


SFT Stage2 : Train **full model** in 1.2M (v1.2) or 12M (v1.2 plus) SFT data.

**Comment by zhouxincheng** [comment]
Thanks a lot

**Comment by zhengyunqq** [comment]
Thanks

**Comment by zhengyunqq** [comment]
> > What datasets are included in the 12M SFT data. 
> 
> 
> 
> There are a lot of academic VQA datasets here, including COCO caption, VQAv2, VSR, OKVQA, AOKVQA, IconQA, AI2D, GQA, TextVQA, OCRVQA, ChartQA, DocQA, STVQA, ESTVQA, InfoVQA, LLaVAR, VisDial, CLEVR, ScienceQA...
> 
> 
> 
> And about 2M of open-source OCR datasets, like LSVT, RCTW, ...
> 
> 
> 
> Visual grounding datasets like RefCOCO and Toloka, ...
> 
> 
> 
> NLP dataset like ShareGPT, OpenOrca, OpenHermes2.5, ...
> 
> 
> 
> GPT4V long caption datasets like ShareGPT4V, SVIT, ...

Thanks a lot.
