### ISSUE TITLE
[Docs] internvl2-8b模型微调完保存的checkpoint怎么加载？AutoModel.from_pretrained和peft加载都有问题。

### ISSUE THREAD

**Issue by JiYinshuai** [OpenGVLab/InternVL#521]
### 📚 The doc issue

internvl2-8b模型微调完保存的checkpoint怎么加载？AutoModel.from_pretrained和peft加载都有问题。

**Comment by G-z-w** [comment]
你可以使用InternVLChatModel加载，参考https://github.com/OpenGVLab/InternVL/blob/c62fa4f7c850165d7386bdc48ac6bc5a6fab0864/internvl_chat/eval/mmbench/evaluate_mmbench.py#L293
