### ISSUE TITLE
(Continuous) Batch Serving Internvl2 using lmdeploy

### ISSUE THREAD

**Issue by zzjchen** [OpenGVLab/InternVL#523]
I'm trying to serve InternVL2 (llama3 76B) using lmdeploy as the example [here](https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html#serving-with-openai-compatible-server) on 4 A100-80G GPUs. However, I found that the server is always processing one request after another.
I've referred to [Lmdeploy's Issue](https://github.com/InternLM/lmdeploy/issues/2327) to adjust the --vision-max-batch-size to 8, but still can't see the server processing requests in parallel.
Is it possible to server a InternVL2-Llama3-76B where (dynamic) batching is enabled? By batching, I mean the server can generate response for multiple request at the same time (probably similar to vllm's continuous batching). If so, how to do it?
If not possible, is there someway that I can process batched inputs in one request, i.e. requesting 4 (or 8 etc.) different outputs together in one request?

**Comment by G-z-w** [comment]
You can use batch [inference](https://lmdeploy.readthedocs.io/en/latest/multi_modal/vl_pipeline.html#batch-prompts-inference), or you can deploy an [openai api server](https://lmdeploy.readthedocs.io/en/latest/multi_modal/api_server_vl.html#option-1-launching-with-lmdeploy-cli) and then request it.

**Comment by zzjchen** [comment]
Thanks, I've understood the whole process through [lmdeploy's issue](https://github.com/InternLM/lmdeploy/issues/2347)

**Comment by kavinn-bautomate** [comment]
@zzjchen Were you able to achieve the above issue raised? Processing multiple requests at same time? If yes can how did u do it . Please let me know.
