### ISSUE TITLE
resources required for training with 72b language models

### ISSUE THREAD

**Issue by annopackage** [OpenGVLab/InternVL#526]
Hi, thanks for your great work. I was wondering the how many gpus are needed to training internvl with 72b llm.

**Comment by czczup** [comment]
Hello, if you start with separate ViT and LLM models, connect them with a randomly initialized MLP projector, and perform complete pretraining and SFT, you will need at least 256 GPUs with 80GB memory each. However, if you are fine-tuning based on our released InternVL2-Llama3-76B model, we recommend using 32 GPUs.
