### ISSUE TITLE
[Bug] 多张图片推理的时候，如何在prompt引用某一张图片

### ISSUE THREAD

**Issue by gxlover0625** [OpenGVLab/InternVL#528]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

请问多张图片推理的时候，如何在prompt中引用某一些图片，是否要用图一这些词汇，还是要加一些特殊的tag？

### Reproduction

for i in range(len(images)):
                prompt_prefix += f'Image-{i+1}: {IMAGE_TOKEN}\n'
                prompt = prompt_prefix + query
images代表我输入的图片列表，query代表我的问题，我知道要在prompt最前面加入IMAGE_TOKEN代表图片，但是query里面如何指代第一张图片？

### Environment

```Shell
无
```

**Comment by G-z-w** [comment]
你可以使用Image 1这类词汇，在prompt的上下文中指代所代表的图片。

**Comment by czczup** [comment]
可以用Image-1, Image-2这样的标签去指代图片
