### ISSUE TITLE
[Feature] Can InternVL-chat directly support semantic segmentation tasks?

### ISSUE THREAD

**Issue by fyting** [OpenGVLab/InternVL#531]
### Motivation

Can InternVL-chat directly support semantic segmentation tasks?

**Comment by czczup** [comment]
Hello, we currently cannot use the chat model to perform semantic segmentation tasks. However, integrating VisionLLMv2 tools with InternVL will enable this functionality. This feature is not ready at the moment, so we kindly ask for your patience.
