### ISSUE TITLE
[Feature] How to select the value of gradient_accumulation_steps?

### ISSUE THREAD

**Issue by TongkunGuan** [OpenGVLab/InternVL#532]
### Motivation

The basic setting in internvl2_2b_internlm2_1_8b_dynamic_res_2nd_finetune_full.sh:
```
GPUS=${GPUS:-8}
BATCH_SIZE=${BATCH_SIZE:-128}
PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-4}
GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))
```

I have three 3090s, PER_DEVICE_BATCH_SIZE=1, BATCH_SIZE should equal to 1X3XGRADIENT_ACC(4) = 12?

**Comment by G-z-w** [comment]
Your understanding is correct. In the script, gradient_accumulation_steps is automatically calculated.

**Comment by czczup** [comment]
Hello, you only need to set the number of GPUs and the batch size; the gradient_accumulation_steps will be automatically calculated.
