### ISSUE TITLE
OCR data format

### ISSUE THREAD

**Issue by Hiwyl** [OpenGVLab/InternVL#536]
hi , 如果要做端到端的OCR ， 检测和识别的数据集应该是什么格式，一个box对应一张图和文本label吗？

**Comment by czczup** [comment]
我们训练OCR的格式是：
User: 请识别图中的文字（类似这样的几十个模板）
Assistant: 图中的文字包括：\nXXX\nXXX\nXXX\nXXX（直接输出OCR的结果）

我们没有使用OCR的坐标框进行训练，具体的格式可以见我们的数据格式文档：
https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html

**Comment by Hiwyl** [comment]
> 我们训练OCR的格式是： User: 请识别图中的文字（类似这样的几十个模板） Assistant: 图中的文字包括：\nXXX\nXXX\nXXX\nXXX（直接输出OCR的结果）
> 
> 我们没有使用OCR的坐标框进行训练，具体的格式可以见我们的数据格式文档： https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html

感谢感谢，这块有没有好的建议：
1. 直接识别整图我发现中文基本会重复；
2. 按行 box + label

**Comment by czczup** [comment]
我们没有训练ocr的box是因为，大量的box训练对语言模型的语言能力破坏很厉害

**Comment by Kouuh** [comment]
> 我们没有训练ocr的box是因为，大量的box训练对语言模型的语言能力破坏很厉害

想请教下这是怎么发现的？因为我们现在训练box发现有时候会出现box大量重复。
