### ISSUE TITLE
How much data is necessary for effective fine-tuning?

### ISSUE THREAD

**Issue by asrlhhh** [OpenGVLab/InternVL#539]
I am planning to fine-tune an 8B model (using LoRA) for a customized document understanding task. On average, how much data would be sufficient for this? Are we looking at around 100 training samples, 1,000, or even more?

**Comment by czczup** [comment]
Hi, for fine-tuning an 8B model with LoRA:

- **~100 samples**: Likely too few; may overfit.
- **~1,000 samples**: A reasonable start for many tasks.
- **10,000+ samples**: Better for complex or varied tasks to improve generalization.

At least 1,000 samples is usually a good starting point.
