### ISSUE TITLE
ocrvqa_train_206k 数据标注文件

### ISSUE THREAD

**Issue by Hiwyl** [OpenGVLab/InternVL#541]
![image](https://github.com/user-attachments/assets/4dcc1a10-8cdd-4036-a6ab-8217878559a2)
好像没有上传这个标注文件

**Comment by czczup** [comment]
你好，可以从这里下载这些数据集：
https://huggingface.co/datasets/OpenGVLab/InternVL-Chat-V1-2-SFT-Data/tree/main/data

<img width="761" alt="image" src="https://github.com/user-attachments/assets/ea1fe973-c4d2-4c09-949c-342cfc80ea42">

**Comment by Hiwyl** [comment]
> 你好，可以从这里下载这些数据集： https://huggingface.co/datasets/OpenGVLab/InternVL-Chat-V1-2-SFT-Data/tree/main/data
> 
> <img alt="image" width="761" src="https://private-user-images.githubusercontent.com/23737120/362201901-ea1fe973-c4d2-4c09-949c-342cfc80ea42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzM5MDYsIm5iZiI6MTcyNDgzMzYwNiwicGF0aCI6Ii8yMzczNzEyMC8zNjIyMDE5MDEtZWExZmU5NzMtYzRkMi00YzA5LTk0OWMtMzQyY2ZjODBlYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA4MjY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNGM3MTY4NDcyYjU2NDQ5NjVmNmY4Y2ZjMGFmMzYzZmVmNTYyNTY2NTg2Njc4ZTNlZjFlYzU3MzljZTExOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6JVXCHsMOBzDosB_ScZy_X3XZ-r9sMg4qsJb1kv_VbI">

您好，数据下载了，好像没看到对应的SFT 标注文件

**Comment by czczup** [comment]
噢对了，DocVQA的标注是包含在sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.jsonl这个文件里面的。

https://huggingface.co/datasets/OpenGVLab/InternVL-Chat-V1-2-SFT-Data/blob/main/opensource/sharegpt4v_mix665k_cap23k_coco-ap9k_lcs3k_sam9k_div2k.jsonl
