### ISSUE TITLE
不同模型的输入最长长度有区别吗？

### ISSUE THREAD

**Issue by zz-hitnlper** [OpenGVLab/InternVL#542]
我用8B的超出了，不同模型的最长长度是否都是8192？
<img width="845" alt="Snipaste_2024-08-28_20-30-53" src="https://github.com/user-attachments/assets/caaa3d9f-9056-4cee-8571-ac3a2ddbe071">

**Comment by zz-hitnlper** [comment]
> 训练的时候是8192，如果做推理，可以设置更大

请问如何设置？

**Comment by ErfeiCui** [comment]
tokenizer_config.json可以在这个文件里设置
