### ISSUE TITLE
[Bug] Vision backbone is not freezed correctly?

### ISSUE THREAD

**Issue by Birdylx** [OpenGVLab/InternVL#544]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

https://github.com/OpenGVLab/InternVL/blob/c62fa4f7c850165d7386bdc48ac6bc5a6fab0864/internvl_chat/internvl/train/internvl_chat_finetune.py#L776
InternViT use droppath, but the freeze didn't call the `eval` to disable droppath?

### Reproduction

None

### Environment

```Shell
None
```

**Comment by czczup** [comment]
Thank you for your observation. This behavior is intentional and can be considered a form of data augmentation to enhance the model's robustness.
