### ISSUE TITLE
InternVL-Chat-V1.2 on mmbench-dev-cn only got acc = 71.73, not acc = 79.5

### ISSUE THREAD

**Issue by yzbx** [OpenGVLab/InternVL#55]
InternVL-Chat-V1.2 is number one in [mmbench-dev-cn](https://mmbench.opencompass.org.cn/leaderboard) with acc = 79.5%

I use the weight from [InternVL-Chat-Chinese-V1-2](https://huggingface.co/OpenGVLab/InternVL-Chat-Chinese-V1-2) which is shown on README. 

evaluation code: 
```
torchrun \
  --nnodes=1 \
  --node_rank=0 \
  --master_addr=127.0.0.1 \
  --nproc_per_node=${GPUS} \
  --master_port=${MASTER_PORT} \
  eval/mmbench/evaluate_mmbench.py --checkpoint ${CHECKPOINT} --datasets mmbench_dev_cn_20231003
```

the results is: 
total question = 4329
tp = 3105
acc = 0.7173

**Comment by czczup** [comment]
Hello, may I ask how your score is calculated? It is not in the same format as the results returned by the mmbench evaluation server.

I just ran a test with the latest code,  and my test command is:
```
torchrun --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --nproc_per_node=4 --master_port=63665 eval/mmbench/evaluate_mmbench.py --checkpoint ./release/InternVL-Chat-Chinese-V1-2 --datasets mmbench_dev_cn_20231003
```

After testing, the results will be saved as an `xlsx` file, and the code will print the path of this file.
In my test, the `xlsx` file is:
<img width="551" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/75b0bac4-d91f-4326-be4d-734121d49378">

Then, upload this xlsx file to the [mmbench evaluation server](https://mmbench.opencompass.org.cn/mmbench-submission). The server will return the score:

<img width="868" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/ed7ec9b1-78f9-405e-958f-b81eacb181ce">

It shows the overall score on `mmbench-dev-cn` is `79.5`, as same as the result on the mmbench official leadboard.

**Comment by yzbx** [comment]
> Hello, may I ask how your score is calculated? It is not in the same format as the results returned by the mmbench evaluation server.
> 
> I just ran a test with the latest code, and my test command is:
> 
> ```
> torchrun --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --nproc_per_node=4 --master_port=63665 eval/mmbench/evaluate_mmbench.py --checkpoint ./release/InternVL-Chat-Chinese-V1-2 --datasets mmbench_dev_cn_20231003
> ```
> 
> After testing, the results will be saved as an `xlsx` file, and the code will print the path of this file. In my test, the `xlsx` file is: <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/23737120/310111855-75b0bac4-d91f-4326-be4d-734121d49378.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTM4ODEsIm5iZiI6MTcwOTcxMzU4MSwicGF0aCI6Ii8yMzczNzEyMC8zMTAxMTE4NTUtNzViMGJhYzQtZDkxZi00MzI2LWJlNGQtNzM0MTIxZDQ5Mzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA4MjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMDI3N2M0YWFhNTY5ODMyNzAxMjg1YzA1ZThmMzczYWY4NjRjYzIxNGZjMWFlYjUyZGExMzc4MzA5YmEyNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1DAdAM4G11ybpBT8LsF2glRRuT0sCHXlUzGZdVfsdY">
> 
> Then, upload this xlsx file to the [mmbench evaluation server](https://mmbench.opencompass.org.cn/mmbench-submission). The server will return the score:
> <img alt="image" width="868" src="https://private-user-images.githubusercontent.com/23737120/310112445-ed7ec9b1-78f9-405e-958f-b81eacb181ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTM4ODEsIm5iZiI6MTcwOTcxMzU4MSwicGF0aCI6Ii8yMzczNzEyMC8zMTAxMTI0NDUtZWQ3ZWM5YjEtNzhmOS00MDVlLTk1OGYtYjgxZWFjYjE4MWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA4MjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYjM3YTliZjJjMWEzMjJlOWUyYTIxNWQ1YmM4N2U2MzNlMmU2OTVhZGY1M2JjNTQ3MjY3MWIxNzc5ZTJhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7y1PnJ9e8dh_0ZHxy6YUUlYrXDc07rEXAuMfttD_yLU">
> 
> It shows the overall score on `mmbench-dev-cn` is `79.5`, as same as the result on the mmbench official leadboard.

I use `regular expression` to obtain the choice A/B/C/D, got acc = 71.73. 
while upload to [mmbench evaluation server](https://mmbench.opencompass.org.cn/mmbench-submission), got acc = 56.79, Result【id:e9c4e0bf77334ec2a510879b14121d6d】

**Comment by czczup** [comment]
Could you please provide more information to help me locate the problem, such as the screenshot during inference, the final output xlsx file, and the transformers version you used? Thank you.

**Comment by czczup** [comment]
I tested InternVL-Chat-Chinese-V1-2 using VLMEvalKit and got a higher result than the official benchmark shows.
This is the result (MMBench_DEV_EN) returned by the VLMEvalKit framework:

<img width="1701" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/b86c8cb9-93c3-4b40-a7c4-38bcde311552">

**Comment by czczup** [comment]
I guess I found the reason. Please use transformers==4.36.2 and tokenizers==0.15.1
You can see the [INSTALLATION](https://github.com/OpenGVLab/InternVL/blob/main/INSTALLATION.md) document for more detail.

**Comment by yzbx** [comment]
> I guess I found the reason. Please use `transformers==4.36.2` and `tokenizers==0.15.1`. In my impression, the 4.31.0 version should not support LLaMA2 architecture. You can see the [INSTALLATION](https://github.com/OpenGVLab/InternVL/blob/main/INSTALLATION.md) document for more details.

after update to transformers==4.36.2 and tokenizers==0.15.1, the acc = 85 with regex
