### ISSUE TITLE
[Docs] Dataset release

### ISSUE THREAD

**Issue by GohioAC** [OpenGVLab/InternVL#551]
### 📚 The doc issue

Is the full dataset used for pre-training and fine-tuning released publicly? If not, is there any plan to do?

### Suggest a potential alternative/fix

Add more details about the type of instructions used during training. This has a direct impact on prompt tuning.

**Comment by ErfeiCui** [comment]
Thank you for your suggestion. The datasets used have already been specified in our paper, and we will add various data details in our user manual shortly.
