### ISSUE TITLE
[Bug]  数据量超过5000w条以后，内存出现OOM

### ISSUE THREAD

**Issue by liangdashuang** [OpenGVLab/InternVL#554]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

用5000w以上的数据微调8B的模型，batchsize设置为1， 当dataloader_num_workers设置为大于1的时候，到dataloader时出现内存OOM错误；当dataloader_num_workers设置为0或者1的时候，可以正常训练;
内存大小有115G，数据json在磁盘中大约有30G
<img width="1773" alt="image" src="https://github.com/user-attachments/assets/3d18bbf5-fb43-408d-a4d5-4618a374fe8a">

### Reproduction

GPUS=1 BATCH_SIZE=1 PER_DEVICE_BATCH_SIZE=1 sh internvl2_8b_internlm2_7b_dynamic_res_2nd_finetune_lora.sh

### Environment

```Shell
Python 3.10.14
torch 2.1.0
```

**Comment by ErfeiCui** [comment]
应该还是受限于硬件资源，设置为1即可

**Comment by zxc351200** [comment]
我也遇到了这个问题，5000w数据会内存不足。
但是我把dataloader_num_workers设置为1，好像还是会遇到错误，有什么比较好的解决方法吗？

**Comment by liangdashuang** [comment]
当前把dataloader_num_workers设置为了1，然后勉强可以训练，再不行降低下batchsize数。不过感觉internvl官方还是还是需要把代码完善下，数据不要一下全部读到内存里面。

**Comment by liangdashuang** [comment]
> 我也遇到了这个问题，5000w数据会内存不足。 但是我把dataloader_num_workers设置为1，好像还是会遇到错误，有什么比较好的解决方法吗？

当前把dataloader_num_workers设置为了1，然后勉强可以训练，再不行降低下batchsize数。不过感觉internvl官方还是还是需要把代码完善下，数据不要一下全部读到内存里面。
