### ISSUE TITLE
多语种文字理解MTVQA benchmark

### ISSUE THREAD

**Issue by JohnTang93** [OpenGVLab/InternVL#557]
可以report一下在多语种文字理解MTVQA benchmark上的表现嘛

**Comment by czczup** [comment]
您好，这里有MTVQA的性能：https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html#mtvqa

**Comment by JohnTang93** [comment]
谢谢~我们在榜单中添加一下~

**Comment by czczup** [comment]
谢谢～
