### ISSUE TITLE
max_dynamic_patch

### ISSUE THREAD

**Issue by Hiwyl** [OpenGVLab/InternVL#561]
--max_dynamic_patch 这个参数有什么建议吗？训练6，推理6 偶尔会输出不完整，推理使用12推理正确

**Comment by czczup** [comment]
我们为了保证较好的OCR能力，训练的时候默认用--max_dynamic_patch 12。不过如果微调场景不需要特别高的分辨率，使用--max_dynamic_patch 6也是可以的。

另外想问一下偶尔会输出不完整具体能提供一些例子吗。

**Comment by Hiwyl** [comment]
> 我们为了保证较好的OCR能力，训练的时候默认用--max_dynamic_patch 12。不过如果微调场景不需要特别高的分辨率，使用--max_dynamic_patch 6也是可以的。
> 
> 另外想问一下偶尔会输出不完整具体能提供一些例子吗。

![image](https://github.com/user-attachments/assets/d6a65de7-270b-490c-b20c-87e4780667d8)
比如上图，红框以上全部输出了，红框内的字没有输出

**Comment by czczup** [comment]
感觉可能还是训练不够充分
