### ISSUE TITLE
 用InternVL2-4B 微调后遇到到灾难性遗忘的问题

### ISSUE THREAD

**Issue by crmlei** [OpenGVLab/InternVL#568]
### Motivation

用InternVL2-4B 在一个700多张图片的数据集上微调一个垂直领域的图片理解任务。微调后发现输入通用prompt，比如“请简单描述图片的内容”或“请问图片中是否有车辆”，但输出基本都是微调数据集上的答案。好像通用的能力消失了。不知道这样的问题有没有解决方案？谢谢。

**Comment by crmlei** [comment]
补充说明下，是全参数微调

**Comment by czczup** [comment]
这个是正常的现象，如果想要保留模型的通用能力，需要将通用数据集和垂直领域数据集按照一个配比混合起来训练。

**Comment by crmlei** [comment]
> 这个是正常的现象，如果想要保留模型的通用能力，需要将通用数据集和垂直领域数据集按照一个配比混合起来训练。

那么一般这个比例是多少合适？

**Comment by czczup** [comment]
通用：垂直领域=1:1或者通用：垂直领域=5:1都可以，侧重点有区别；

如果是通用：垂直领域=1:1，就是比较侧重垂直领域；
如果是通用：垂直领域=5:1，就是在侧重通用的情况下增强垂直领域。

**Comment by AIFFFENG** [comment]
> 这个是正常的现象，如果想要保留模型的通用能力，需要将通用数据集和垂直领域数据集按照一个配比混合起来训练。

如果全量微调带上通用的数据，指标大概会比全量微调提升多少，你们有做过相关的实验吗？

**Comment by weweus** [comment]
> 通用：垂直领域=1:1或者通用：垂直领域=5:1都可以，侧重点有区别；
> 
> 如果是通用：垂直领域=1:1，就是比较侧重垂直领域； 如果是通用：垂直领域=5:1，就是在侧重通用的情况下增强垂直领域。

@czczup 
请问，我全量微调InternVL2-8B，用了sft数据中的部分VQA数据，在`ai2diagram_test`测试集上评测，accuracy下降的很严重（不如pretrained model），怎么训才能达到甚至超过pretrained model？

* 数据集用了`chartqa`、`ai2d`、`geoqa+`
* 2张80G的GPU，并且`PER_DEVICE_BATCH_SIZE=1`
* 由于卡数和显存不足，deepspeed用了`zero_stage3_config.json`
* 其他超参保持默认

```
set -x

GPUS=${GPUS:-8}
BATCH_SIZE=${BATCH_SIZE:-128}
PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-4}
GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))


export PYTHONPATH="${PYTHONPATH}:$(pwd)"
export MASTER_PORT=34229
export TF_CPP_MIN_LOG_LEVEL=3
export LAUNCHER=pytorch

OUTPUT_DIR='work_dirs/internvl_chat_v2_0/internvl2_8b_internlm2_7b_dynamic_res_2nd_finetune_full'

if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"
fi

# number of gpus: 8
# batch size per gpu: 4
# gradient accumulation steps: 4
# total batch size: 128
# epoch: 1
torchrun \
  --nnodes=1 \
  --node_rank=0 \
  --master_addr=127.0.0.1 \
  --nproc_per_node=${GPUS} \
  --master_port=${MASTER_PORT} \
  internvl/train/internvl_chat_finetune.py \
  --model_name_or_path "./pretrained/InternVL2-8B" \
  --conv_style "internlm2-chat" \
  --output_dir ${OUTPUT_DIR} \
  --meta_path "reimplement_internvl_1_2_finetune_custom.json" \
  --overwrite_output_dir True \
  --force_image_size 448 \
  --max_dynamic_patch 6 \
  --down_sample_ratio 0.5 \
  --drop_path_rate 0.1 \
  --freeze_llm False \
  --freeze_mlp False \
  --freeze_backbone True \
  --vision_select_layer -1 \
  --dataloader_num_workers 4 \
  --bf16 True \
  --num_train_epochs 1 \
  --per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
  --gradient_accumulation_steps ${GRADIENT_ACC} \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 200 \
  --save_total_limit 1 \
  --learning_rate 4e-5 \
  --weight_decay 0.01 \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --max_seq_length 4096 \
  --do_train True \
  --grad_checkpoint True \
  --group_by_length True \
  --dynamic_image_size True \
  --use_thumbnail True \
  --ps_version 'v2' \
  --deepspeed "zero_stage3_config.json" \
  --report_to "tensorboard" \
  2>&1 | tee -a "${OUTPUT_DIR}/training_log.txt"
```

* 训练过程loss如下
![image](https://github.com/user-attachments/assets/d21fd7fe-cf2e-45d2-b69b-94728c070f0b)

* pretrained、ckpt400、ckpt600、ckpt800、last，在`ai2diagram_test`测试集上accuracy分别是0.8374、0.5126、0.6635、0.6885、0.6881，如下
![image](https://github.com/user-attachments/assets/67862472-0729-4c93-b21c-da1d305ffa27)
![image](https://github.com/user-attachments/assets/49a05a1e-cc22-49f4-8748-0156e9808a23)
![image](https://github.com/user-attachments/assets/51178cd9-fa76-4f72-906c-a586095a9f64)
![image](https://github.com/user-attachments/assets/3ece4f9c-1f27-4680-bf3c-cec926cf0ab9)
![image](https://github.com/user-attachments/assets/664ff23c-426a-42f1-8806-2172e6e40c2a)

**Comment by czczup** [comment]
> > 通用：垂直领域=1:1或者通用：垂直领域=5:1都可以，侧重点有区别；
> > 如果是通用：垂直领域=1:1，就是比较侧重垂直领域； 如果是通用：垂直领域=5:1，就是在侧重通用的情况下增强垂直领域。
> 
> @czczup 请问，我全量微调InternVL2-8B（用了sft数据中的一部分VQA数据），最终在`ai2diagram_test`测试集上评测，发现accuracy下降的很严重（不如pretrained model），怎么训才能达到甚至超过pretrained model？
> 
> * 数据集用了`chartqa`、`ai2d`、`geoqa+`
> * 2张80G的GPU，并且`PER_DEVICE_BATCH_SIZE=1`
> * 由于卡数和显存不足，deepspeed用了`zero_stage3_config.json`
> * 其他超参保持默认
> 
> ```
> set -x
> 
> GPUS=${GPUS:-8}
> BATCH_SIZE=${BATCH_SIZE:-128}
> PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-4}
> GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))
> 
> 
> export PYTHONPATH="${PYTHONPATH}:$(pwd)"
> export MASTER_PORT=34229
> export TF_CPP_MIN_LOG_LEVEL=3
> export LAUNCHER=pytorch
> 
> OUTPUT_DIR='work_dirs/internvl_chat_v2_0/internvl2_8b_internlm2_7b_dynamic_res_2nd_finetune_full'
> 
> if [ ! -d "$OUTPUT_DIR" ]; then
>   mkdir -p "$OUTPUT_DIR"
> fi
> 
> # number of gpus: 8
> # batch size per gpu: 4
> # gradient accumulation steps: 4
> # total batch size: 128
> # epoch: 1
> torchrun \
>   --nnodes=1 \
>   --node_rank=0 \
>   --master_addr=127.0.0.1 \
>   --nproc_per_node=${GPUS} \
>   --master_port=${MASTER_PORT} \
>   internvl/train/internvl_chat_finetune.py \
>   --model_name_or_path "./pretrained/InternVL2-8B" \
>   --conv_style "internlm2-chat" \
>   --output_dir ${OUTPUT_DIR} \
>   --meta_path "reimplement_internvl_1_2_finetune_custom.json" \
>   --overwrite_output_dir True \
>   --force_image_size 448 \
>   --max_dynamic_patch 6 \
>   --down_sample_ratio 0.5 \
>   --drop_path_rate 0.1 \
>   --freeze_llm False \
>   --freeze_mlp False \
>   --freeze_backbone True \
>   --vision_select_layer -1 \
>   --dataloader_num_workers 4 \
>   --bf16 True \
>   --num_train_epochs 1 \
>   --per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
>   --gradient_accumulation_steps ${GRADIENT_ACC} \
>   --evaluation_strategy "no" \
>   --save_strategy "steps" \
>   --save_steps 200 \
>   --save_total_limit 1 \
>   --learning_rate 4e-5 \
>   --weight_decay 0.01 \
>   --warmup_ratio 0.03 \
>   --lr_scheduler_type "cosine" \
>   --logging_steps 1 \
>   --max_seq_length 4096 \
>   --do_train True \
>   --grad_checkpoint True \
>   --group_by_length True \
>   --dynamic_image_size True \
>   --use_thumbnail True \
>   --ps_version 'v2' \
>   --deepspeed "zero_stage3_config.json" \
>   --report_to "tensorboard" \
>   2>&1 | tee -a "${OUTPUT_DIR}/training_log.txt"
> ```
> 
> * 训练过程loss如下
>   ![image](https://private-user-images.githubusercontent.com/37571526/366704484-d21fd7fe-cf2e-45d2-b69b-94728c070f0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzU4OTMsIm5iZiI6MTczMjM3NTU5MywicGF0aCI6Ii8zNzU3MTUyNi8zNjY3MDQ0ODQtZDIxZmQ3ZmUtY2YyZS00NWQyLWI2OWItOTQ3MjhjMDcwZjBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzRkNjljNTE1MWFkODEzMWIwMTM1YjI5MTM3ZTNlOTJlYTQ4OGZlOWE0MTA0ZDZmY2NlNzEzMDRhM2Q3ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5BBTZf3dqCMXAq-WQONipeGMx6mdgYgYO5IFSV9uL9E)
> * pretrained、ckpt400、ckpt600、ckpt800、last，在`ai2diagram_test`测试集上accuracy分别是0.8374、0.5126、0.6635、0.6885、0.6881，如下
>   ![image](https://private-user-images.githubusercontent.com/37571526/366705053-67862472-0729-4c93-b21c-da1d305ffa27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzU4OTMsIm5iZiI6MTczMjM3NTU5MywicGF0aCI6Ii8zNzU3MTUyNi8zNjY3MDUwNTMtNjc4NjI0NzItMDcyOS00YzkzLWIyMWMtZGExZDMwNWZmYTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYThjZmJkZTE3YmVlNmRjNWIwZWE4YzY3ZGFjNDNmZDdjYTE1ZjYxZjcwMDM5NGY0YWVmODJiZjkzYjlhNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v9ZDZZ3GBeK9mz49imCR6j7RJ9HkO5AyhsCG-YG2L8o)
>   ![image](https://private-user-images.githubusercontent.com/37571526/366705162-49a05a1e-cc22-49f4-8748-0156e9808a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzU4OTMsIm5iZiI6MTczMjM3NTU5MywicGF0aCI6Ii8zNzU3MTUyNi8zNjY3MDUxNjItNDlhMDVhMWUtY2MyMi00OWY0LTg3NDgtMDE1NmU5ODA4YTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZDQwZjFhOTdkZTdmNDFlMTFiMzgyMDE4MWZlOTNiMjgwZDU1NTg0NDI2ZTYwMjc3NTY1ZTJhNzcyZWQ1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J_RxvLL817XpUF3Yur-dqzlMexnwRemrDxU3cp1OACQ)
>   ![image](https://private-user-images.githubusercontent.com/37571526/366705259-51178cd9-fa76-4f72-906c-a586095a9f64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzU4OTMsIm5iZiI6MTczMjM3NTU5MywicGF0aCI6Ii8zNzU3MTUyNi8zNjY3MDUyNTktNTExNzhjZDktZmE3Ni00ZjcyLTkwNmMtYTU4NjA5NWE5ZjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZGJlNzZlZWJlYjczZjFhOTNmZGEwZmE0YjkxNjgxNjkxNTMwNDQ3NzkwNDEyYTI2NGU2YTAzOTRjZmYwZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VoOk2NSdvPc48zCGPgJsA6mnb9TW-MjX7iY3XRZt9yE)
>   ![image](https://private-user-images.githubusercontent.com/37571526/366705378-3ece4f9c-1f27-4680-bf3c-cec926cf0ab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzU4OTMsIm5iZiI6MTczMjM3NTU5MywicGF0aCI6Ii8zNzU3MTUyNi8zNjY3MDUzNzgtM2VjZTRmOWMtMWYyNy00NjgwLWJmM2MtY2VjOTI2Y2YwYWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NjAyODE4ZWU5YjI0OTQ2NDJlMjg1OGU2M2ZhYjZmODg0ZDNlNTg3MmNlZmZkYzYxODY3YmI1Y2FjOGE0MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.09AAiE1oq7__KKWyilr0mqrux6wHi2znNq5QkwtkMs4)
>   ![image](https://private-user-images.githubusercontent.com/37571526/366705587-664ff23c-426a-42f1-8806-2172e6e40c2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNzU4OTMsIm5iZiI6MTczMjM3NTU5MywicGF0aCI6Ii8zNzU3MTUyNi8zNjY3MDU1ODctNjY0ZmYyM2MtNDI2YS00MmYxLTg4MDYtMjE3MmU2ZTQwYzJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE1MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiY2ZmZDliMmEwODBjN2UxOGUxMjQ0NThjZmY3OTg2NWUzNjRjNjY5YTAxZjI5Y2ZkNDQ5N2I0MDFhZDNmZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._ezvR--N3uMEJn9XhP8_g9nw3CV_j8ktd3qA8osBNEM)

您好，因为您说的这几个数据集在我们训练过程中都有，而且已经训练了2-4个epoch了，您在此使用他们进行微调可能会导致过拟合的，只用这几个数据集想要获得更高的点数比较困难。

**Comment by Kazma11** [comment]
请问8B微调大概要多少显存？
