### ISSUE TITLE
请问在做微调时 如何指定图片的augment方法（比如随机旋转、翻转、亮度对比度调整等）？

### ISSUE THREAD

**Issue by crmlei** [OpenGVLab/InternVL#570]
### Motivation

感谢大神们在大模型开源的工作！

正常测试在一个小的图片集上做微调，请问在做微调时，有做图片的augment吗？如何指定对数据集图片的augment方法，比如随机旋转、翻转、亮度对比度调整等？

**Comment by Weiyun1025** [comment]
可以在如下位置引入数据增强相关的代码，随机旋转等功能的实现可以参考torchvision的文档

https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L329
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/dataset.py#L260
