### ISSUE TITLE
[Docs] 能否提供仅CPU运行的Local Chat Demo代码示例

### ISSUE THREAD

**Issue by gy850222** [OpenGVLab/InternVL#572]
### 📚 The doc issue

能否提供仅CPU运行的Local Chat Demo代码示例 ：）
非常感谢！

**Comment by Weiyun1025** [comment]
可以参考这个部分的做法：https://github.com/OpenGVLab/InternVL/issues/163#issuecomment-2114083407

然后将我们提供的demo中device相关的代码改成cpu试一下

**Comment by gy850222** [comment]
感谢您的回复，我已经实现了仅CPU运行和离线部署。
