### ISSUE TITLE
推理时候的maximum sequence length指的是什么？

### ISSUE THREAD

**Issue by Lanbai-eleven** [OpenGVLab/InternVL#573]
在进行视频推理的时候，输入的帧数太多会报以下提示：
![image](https://github.com/user-attachments/assets/cc9cf9d4-c654-4c21-82a1-07c03e81869a)
请问这里的maximum sequence length指的是什么？ 是表示一次输入的token长度限制吗？如果是的话8k的输入长度是不是有点偏低了。

**Comment by Lanbai-eleven** [comment]
> 是的，maximum sequence length表示输入的最大token数量，正常情况下是需要截断到8K的，但是也可以不截断强行做推理，但是这个时候模型性能会有下降。
> 
> 目前多模态长序列的训练数据比较匮乏，因此我们的模型支持的最大长度也较短，我们最近也已经在做长序列的相关工作了，届时可以关注一下。

这里的token数量指的是视频这部分的token还是完整输入的token，我记得InternVL所使用的语言模型的上下文长度没有这么短吧，还是说因为训练数据的缘故限制在这个长度的表现会比较好。

**Comment by czczup** [comment]
是的，用的语言模型的上下文基本都是不止8K的。在实际用的时候你可以忽略这个warning，输入更长的sequence问题不大。
