### ISSUE TITLE
每次推理，显存占用都会不断增加是什么问题

### ISSUE THREAD

**Issue by Note-Liu** [OpenGVLab/InternVL#575]
命令：CUDA_VISIBLE_DEVICES=0 python3.10 model_worker.py --host 0.0.0.0 --controller $CONTROLLER_URL --port 40001 --worker http://0.0.0.0:40001 --model-path InternVL2-8B

**Comment by corkiyao** [comment]
> 命令：CUDA_VISIBLE_DEVICES=0 python3.10 model_worker.py --host 0.0.0.0 --controller $CONTROLLER_URL --port 40001 --worker http://0.0.0.0:40001 --model-path InternVL2-8B

你好，请问解决了吗？我也是一直在增加。但是发现不了问题在哪
