### ISSUE TITLE
[Docs] Can't evaluate GQA testdev.

### ISSUE THREAD

**Issue by Zzzzzzzzzzj** [OpenGVLab/InternVL#576]
### 📚 The doc issue

<img width="831" alt="image" src="https://github.com/user-attachments/assets/19c50af2-a932-4714-9fc2-af895205aa4d">

I don't think it's possible to get the structure of the dataset as depicted below in the diagram as shown in the diagram.

### Suggest a potential alternative/fix

I don't know...

**Comment by czczup** [comment]
You can download these files from the official website of GQA dataset:
https://cs.stanford.edu/people/dorarad/gqa/download.html
