### ISSUE TITLE
[Feature] image_flags.squeeze(-1) Error: How can i get loss and logits in InternVL2 and InternVL-Chat Family?

### ISSUE THREAD

**Issue by V2LLAIN** [OpenGVLab/InternVL#578]
### Motivation

i wanna use loss for experiments so use like below. 
but it doesn't work so i wanna solution.

### Related resources

model = AutoModel.from_pretrained(
    path, torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True
    ).eval().cuda()

tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True, use_fast=False, add_eos_token=True)

pixel_values = load_image('/data/hc/0.jpg', max_num=80).to(torch.bfloat16).cuda()
generation_config = dict(max_new_tokens=2048, do_sample=False)

question = "<image>\nWhat is the girl looking?"
response = model.chat(tokenizer, pixel_values, question, generation_config)
print(f'{response}'

input_ids = tokenizer(question, return_tensors='pt', max_length=80,
                      truncation=True, padding='max_length').input_ids.cuda()
loss, logits = model(pixel_values, input_ids)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 1
----> 1 loss, logits = model(pixel_values, input_ids)

File /data/hc/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/nn/modules/module.py:1553, in Module._wrapped_call_impl(self, *args, **kwargs)
   1551     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552 else:
-> 1553     return self._call_impl(*args, **kwargs)

File /data/hc/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/nn/modules/module.py:1562, in Module._call_impl(self, *args, **kwargs)
   1557 # If we don't have any hooks, we want to skip the rest of the logic in
   1558 # this function, and just call forward.
   1559 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1560         or _global_backward_pre_hooks or _global_backward_hooks
   1561         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562     return forward_call(*args, **kwargs)
   1564 try:
   1565     result = None

File ~/.cache/huggingface/modules/transformers_modules/internvl2_8b_merge/modeling_internvl_chat.py:100, in InternVLChatModel.forward(self, pixel_values, input_ids, attention_mask, position_ids, image_flags, past_key_values, labels, use_cache, output_attentions, output_hidden_states, return_dict)
     84 def forward(
     85         self,
     86         pixel_values: torch.FloatTensor,
   (...)
     96         return_dict: Optional[bool] = None,
     97 ) -> Union[Tuple, CausalLMOutputWithPast]:
     98     return_dict = return_dict if return_dict is not None else self.config.use_return_dict
--> 100     image_flags = image_flags.squeeze(-1)
    101     input_embeds = self.language_model.get_input_embeddings()(input_ids)
    103     vit_embeds = self.extract_feature(pixel_values)

AttributeError: 'NoneType' object has no attribute 'squeeze'

**Comment by czczup** [comment]
Hi, you need to pass in an `image_flags` parameter, which indicates whether the 256 visual tokens generated from the current 448x448 image are valid or if the image is just padding. Only valid images will be passed to the language model.

Therefore, for input `pixel_values` with a shape of `bsx3x448x448`, you need to provide a vector with a shape of `[1, bs]`, where each value is set to 1, indicating that all these `pixel_values` are valid.

**Comment by V2LLAIN** [comment]
it's very very thank you! im very appreciate about it!

**Comment by lnhtrn** [comment]
I follow the example and put down the `image_flags` as follow:
```
input_ids = tokenizer(question, return_tensors='pt', max_length=80,
truncation=True, padding='max_length').input_ids.cuda()
output = model(pixel_values, input_ids, image_flags=torch.ones((1,1)))
```
But I encountered this problem:

```RuntimeError                              Traceback (most recent call last)
File ~/.cache/huggingface/modules/transformers_modules/OpenGVLab/InternVL2-1B/a84c71e158b16180df4fd1c5fe963fdf54b2cd43/modeling_internvl_chat.py:119, in InternVLChatModel.forward(self, pixel_values, input_ids, attention_mask, position_ids, image_flags, past_key_values, labels, use_cache, output_attentions, output_hidden_states, return_dict)
    118 try:
--> 119     input_embeds[selected] = input_embeds[selected] * 0.0 + vit_embeds.reshape(-1, C)
    120 except Exception as e:

RuntimeError: The size of tensor a (80) must match the size of tensor b (256) at non-singleton dimension 1

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[24], line 10
      4 # question = "\nWhat is the girl looking?"
      5 # response = model.chat(tokenizer, pixel_values, question, generation_config)
      6 # print(f'{response}'
      8 input_ids = tokenizer(question, return_tensors='pt', max_length=80,
      9 truncation=True, padding='max_length').input_ids.cuda()
---> 10 output = model(pixel_values, input_ids, image_flags=torch.ones((1,1)))

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1553, in Module._wrapped_call_impl(self, *args, **kwargs)
   1551     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1552 else:
-> 1553     return self._call_impl(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1562, in Module._call_impl(self, *args, **kwargs)
   1557 # If we don't have any hooks, we want to skip the rest of the logic in
   1558 # this function, and just call forward.
   1559 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1560         or _global_backward_pre_hooks or _global_backward_hooks
   1561         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1562     return forward_call(*args, **kwargs)
   1564 try:
   1565     result = None

File ~/.cache/huggingface/modules/transformers_modules/OpenGVLab/InternVL2-1B/a84c71e158b16180df4fd1c5fe963fdf54b2cd43/modeling_internvl_chat.py:124, in InternVLChatModel.forward(self, pixel_values, input_ids, attention_mask, position_ids, image_flags, past_key_values, labels, use_cache, output_attentions, output_hidden_states, return_dict)
    121     vit_embeds = vit_embeds.reshape(-1, C)
    122     print(f'warning: {e}, input_embeds[selected].shape={input_embeds[selected].shape}, '
    123           f'vit_embeds.shape={vit_embeds.shape}')
--> 124     n_token = selected.sum()
    125     input_embeds[selected] = input_embeds[selected] * 0.0 + vit_embeds[:n_token]
    127 input_embeds = input_embeds.reshape(B, N, C)

AttributeError: 'bool' object has no attribute 'sum'
```

How can I solve this?

**Comment by YoloBird** [comment]
@lnhtrn 我也遇到了相同的问题，请问解决了吗

**Comment by YoloBird** [comment]
@V2LLAIN 请问您解决了吗

**Comment by Granluke** [comment]
I have the same problem. anyone?

**Comment by KerwinFuyihang** [comment]
> [@lnhtrn](https://github.com/lnhtrn) I have the same problem. anyone solved this?

I guess this code works, please check it out.

`def get_logits_from_prompt(model, tokenizer, question, pixel_values):
    if '<image>' not in question:
        question = '<image>\n' + question

    num_patches = pixel_values.shape[0]          
    tokens_per_patch = model.num_image_token            
    num_vit_tokens = num_patches * tokens_per_patch      

    # Step 1: temporarily insert too many <IMG_CONTEXT>
    question = question.replace('<image>', '<img>' + '<IMG_CONTEXT>' * (num_vit_tokens + 100) + '</img>')

    # Step 2: tokenize and trim to match vit_tokens
    model_inputs = tokenizer(question, return_tensors='pt')
    input_ids = model_inputs['input_ids'].to(model.device)
    attention_mask = model_inputs['attention_mask'].to(model.device)

    # Step 3: trim input to match vision tokens exactly
    img_context_token_id = tokenizer.convert_tokens_to_ids('<IMG_CONTEXT>')
    model.img_context_token_id = img_context_token_id

    selected = (input_ids == img_context_token_id)
    selected_count = selected.sum().item()

    if selected_count > num_vit_tokens:
        # Too many <IMG_CONTEXT> tokens → zero out extra
        extra = selected_count - num_vit_tokens
        selected_positions = torch.nonzero(selected[0], as_tuple=False)
        to_zero = selected_positions[-extra:]
        for pos in to_zero:
            input_ids[0, pos[0]] = tokenizer.pad_token_id
            attention_mask[0, pos[0]] = 0
        selected = (input_ids == img_context_token_id)

    assert selected.sum().item() == num_vit_tokens, \
        f"<IMG_CONTEXT> tokens ({selected.sum().item()}) != vision tokens ({num_vit_tokens})"

    # image_flags
    image_flags = torch.ones(num_patches, 1, dtype=torch.long).to(model.device)  # [12, 1]

    # Step 5: forward
    with torch.no_grad():
        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            pixel_values=pixel_values.to(model.device),
            image_flags=image_flags
        )
    return outputs.logits, input_ids`
