### ISSUE TITLE
[Bug] 偶发性出现了相似的一种格式乱码

### ISSUE THREAD

**Issue by sxh-lsc** [OpenGVLab/InternVL#579]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

在使用模型推理一系列图片时，大多时候表现良好，但是完成批数据后，发现有一批描述的乱码特征非常的相似，显著特点是都近似`firefox`的html的感觉：
![image](https://github.com/user-attachments/assets/94a86143-2554-45e7-8372-c14bd0f32353)
在重跑相同的提示词和图片后，这种描述就复现不了，不知道是哪里的编码出了问题，还是某些训练数据脏的原因?

### Reproduction

` { "max_tokens": 768, "repetition_penalty": 1.0, "temperature": 0.5, "top_p": 0.95 }`

### Environment

```Shell
model: InternVL2-26B-AWQ
```

**Comment by czczup** [comment]
我在最近标注的Caption里搜索了一下，没有找到这种pattern，可能是因为AWQ模型损失了精度的原因？目前还是推荐在标注完成后做一些简单的过滤，我有发现标注出来的样本中有小概率存在一些其它的异常情况，比如复读机之类的。
