### ISSUE TITLE
[Bug] 模型微调之后使用refcoco进行评测时报错FileNotFoundError: [Errno 2] No such file or directory: 'data/refcoco/refcoco_val.jsonl'

### ISSUE THREAD

**Issue by jamesbondzhou** [OpenGVLab/InternVL#580]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

我用自己的数据集微调之后，想评测一下模型性能，按照官方文档，选了refcoco的（GPUS=8 sh evalulate.sh pretrained/InternVL2-2B refcoco --dynamic）
就报错FileNotFoundError: [Errno 2] No such file or directory: 'data/refcoco/refcoco_val.jsonl'，这个文件哪里有呢？

### Reproduction

我用自己的数据集使用intervl2-2B的模型进行了微调，这个数据集是按照如下格式描述的
{
  "id": 0,
  "image": "images/5.png",
  "conversations": [
    {
      "from": "human",
      "value": "<image>\nPlease provide the bounding box coordinate of the region this sentence describes: <ref>XXX</ref>"
    },
    {
      "from": "gpt",
      "value": "<ref>XXX</ref><box>[[253, 231, 733, 787]]</box>"
    }
}
模型完成微调之后，可以正常对话，但是推理的时候输出的坐标不准确。
在对模型评估的时候，因为我做的目标检测，找了refcoco的评测，然后就报错了。
另外还有两个问题请教一下：
1.我看了官方文档里refcoco那些指标，这些数值是什么含义呢，这个refcoco指标的评测可以作为目标检测的评估指标吗？
![企业微信截图_17261239313362](https://github.com/user-attachments/assets/dd91c506-5101-4d8e-8c4b-bd2a07c8ccc5)

2.模型在推理的时候输出的坐标位置不准确，这个怎么提升呢，是要上到26B以上的模型吗，我看26B以下的模型视觉部分都是一样的，还是有其他提升的点呢？

### Environment

```Shell
按照官方文档安装。
```

**Comment by czczup** [comment]
在这里下载refcoco的标注：https://internvl.readthedocs.io/en/latest/get_started/eval_data_preparation.html#refcoco-refcoco-refcoco-g
