### ISSUE TITLE
关于训练格式

### ISSUE THREAD

**Issue by galactic123** [OpenGVLab/InternVL#584]
![image](https://github.com/user-attachments/assets/d6982afd-91c8-4047-8981-011bf3bc7ee6)
我看到这里gpt输出的键值是text不是value，请问这有什么影响吗？还是说这里键值是text和value都行？

**Comment by czczup** [comment]
感谢您的反馈，这里是一个笔误，应该全部是value才对。我现在就改掉

**Comment by czczup** [comment]
文档里已经修改
