### ISSUE TITLE
[Bug] InternVL2-Llama3-76B: Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by chchenhui** [OpenGVLab/InternVL#587]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Encountered this error when using 6 A100-40G GPUs to inference InternVL2-Llama3-76B: 
```RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:4 and cuda:0!```
I checked this error and found that ```next tokens``` are not on the same device. 
Changing this line of code in ```transformers``` package: https://github.com/huggingface/transformers/blob/v4.44.2/src/transformers/generation/utils.py#L3026 to ```next_tokens = next_tokens.to(input_ids.device) * unfinished_sequences + pad_token_id * (1 - unfinished_sequences)``` works. However, I think there should be other good solutions.

### Reproduction

InternVL2-Llama3-76B Inference

### Environment

```Shell
transformers==4.42.3
```

**Comment by czczup** [comment]
Hello, did you use this `split_model` code to specify the GPU?

The reason for writing the code this way is to avoid errors that occur during multi-GPU inference due to tensors not being on the same device. By ensuring that the first and last layers of the large language model (LLM) are on the same device, we prevent such errors.

https://internvl.readthedocs.io/en/latest/internvl2.0/quick_start.html#multiple-gpus

```python
import math
import torch
from transformers import AutoTokenizer, AutoModel

def split_model(model_name):
    device_map = {}
    world_size = torch.cuda.device_count()
    num_layers = {
        'InternVL2-1B': 24, 'InternVL2-2B': 24, 'InternVL2-4B': 32, 'InternVL2-8B': 32,
        'InternVL2-26B': 48, 'InternVL2-40B': 60, 'InternVL2-Llama3-76B': 80}[model_name]
    # Since the first GPU will be used for ViT, treat it as half a GPU.
    num_layers_per_gpu = math.ceil(num_layers / (world_size - 0.5))
    num_layers_per_gpu = [num_layers_per_gpu] * world_size
    num_layers_per_gpu[0] = math.ceil(num_layers_per_gpu[0] * 0.5)
    layer_cnt = 0
    for i, num_layer in enumerate(num_layers_per_gpu):
        for j in range(num_layer):
            device_map[f'language_model.model.layers.{layer_cnt}'] = i
            layer_cnt += 1
    device_map['vision_model'] = 0
    device_map['mlp1'] = 0
    device_map['language_model.model.tok_embeddings'] = 0
    device_map['language_model.model.embed_tokens'] = 0
    device_map['language_model.output'] = 0
    device_map['language_model.model.norm'] = 0
    device_map['language_model.lm_head'] = 0
    device_map[f'language_model.model.layers.{num_layers - 1}'] = 0

    return device_map
```

**Comment by chchenhui** [comment]
Hi @czczup , thanks for your response! I found ```split_model``` useful but there is an error as reported in this issue: https://github.com/OpenGVLab/InternVL/issues/420. Adding a line ```device_map['language_model.model.rotary_emb'] = 0``` to ```split_model()```  works!
