### ISSUE TITLE
Question: What is the minimum size of an image that can be classified?

### ISSUE THREAD

**Issue by ChangGiMoon** [OpenGVLab/InternVL#594]
I want to use InternVL2-8B to do binary classification (e.g. yes or no) on very small images. Specifically, I am going to use the cropped bounding box patch (which is the result of Object Detection) as input for InternVL2-8B and verify whether the class of bounding box is correct. **Can you tell me the approximate minimum image size that can be classified?** The prompt will use the following input. The input images have various sizes and appearances as shown below.

prompt:
Based on the given image, answer the following question with 'yes' or 'no': Question: [Is there a person in this image?], Answer:

input image example:
![ex](https://github.com/user-attachments/assets/f59b0cfc-6901-4dfb-b7a7-8a9cfe4d5c80)

**Comment by qishisuren123** [comment]
The minimum image size should be equal to or greater than the patch size, which is 14 by default.

**Comment by heibaidaolx123** [comment]
> The minimum image size should be equal to or greater than the patch size, which is 14 by default.

@qishisuren123 
Hi, the small image will be scaled to multiple of input_size 448 in the preprocessing, right? 
Why >= patch size 14? Did I miss something?
