### ISSUE TITLE
【question】TypeError: InternVLChatModel.forward() missing 1 required positional argument: 'pixel_values'

### ISSUE THREAD

**Issue by ererdewubudesi** [OpenGVLab/InternVL#596]
请问如果想用模型做纯文本推理，应该怎么写呢？outputs = self.model(**inputs, output_hidden_states=True, return_dict=True)，现在这样会TypeError: InternVLChatModel.forward() missing 1 required positional argument: 'pixel_values'，如果加上pixel_values=None，会有image_flags = image_flags.squeeze(-1)
AttributeError: 'NoneType' object has no attribute 'squeeze'

**Comment by qishisuren123** [comment]
Please refer to the examples provided in [code](https://huggingface.co/OpenGVLab/InternVL2-2B) for more details.
