### ISSUE TITLE
请问internvl2还会单独发布VIT和LLM部分吗

### ISSUE THREAD

**Issue by Gav1n-is-here** [OpenGVLab/InternVL#603]
### Motivation

如果想要尝试已有版本不存在的组合如较小规模的LLM搭配更大的VIT改如何呢？

**Comment by qishisuren123** [comment]
我不确定我理解对了您的问题，如果您是要改变模型语言或视觉部分的模型的话您需要修改https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py#L46和相关配置代码

**Comment by czczup** [comment]
感谢提问，InternVL2用的ViT还是InternVL1.5的ViT，就是这个：
https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5

我们在InternVL2这个版本中没有对ViT做额外的增量预训练。

**Comment by ccl-private** [comment]
后续训练[InternViT-6B-448px-V1-5](https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5)权重也是冻结的吗

**Comment by Gav1n-is-here** [comment]
> 我不确定我理解对了您的问题，如果您是要改变模型语言或视觉部分的模型的话您需要修改[https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py#L46和相关配置代码](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py#L46%E5%92%8C%E7%9B%B8%E5%85%B3%E9%85%8D%E7%BD%AE%E4%BB%A3%E7%A0%81)

谢谢你！

**Comment by Gav1n-is-here** [comment]
> 感谢提问，InternVL2用的ViT还是InternVL1.5的ViT，就是这个： https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5
> 
> 我们在InternVL2这个版本中没有对ViT做额外的增量预训练。

谢谢你的解答！

**Comment by awakenlee180** [comment]
> > 感谢提问，InternVL2用的ViT还是InternVL1.5的ViT，就是这个： https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5
> > 我们在InternVL2这个版本中没有对ViT做额外的增量预训练。
> 
> 谢谢你的解答！

请问有预训练vit部分的代码嘛
