### ISSUE TITLE
[Question] pretrain训练时，每隔几个step会出现一次前向耗时异常（正常step的4-10倍左右），导致整体训练速度较慢

### ISSUE THREAD

**Issue by CSammyfd** [OpenGVLab/InternVL#604]
背景：用internvl作为codebase，Qwen2-7B-instruct进行多模态模型训练时发生此现象，拖慢pretrain的训练速度。经排查发现是训练时llm前向时发生异常耗时

*同样的question issue也提在了Qwen2的issue中 https://github.com/QwenLM/Qwen2.5/issues/948

一些细节与观察：
1）仅在pretrain时发生此现象，sft时耗时稳定（所以想不明白），已保证两者的训练参数基本一致（注：仅开放adapter训练）
2）经观察，和当前样本的seq长度似乎无关
3）进行细节的耗时打印发现异常耗时发生时，主要有decoderlayer引发，各层decoderlayer的耗时会呈现 快
->慢->极慢(1000倍耗时)->慢 的特点
异常耗时主要由极慢的那层贡献
4）耗时基本由self.attn贡献，用sdpa和flashattn均如此

目前不清楚产生的原因及接下去的排查/解决思路，希望有了解的同学可以告知思路或原因，感谢~

**Comment by czczup** [comment]
如果是deepspeed显示的forward时间异常，也有可能是卡在了dataloader的数据读取上：
```
[2024-09-25 14:00:21,198] [INFO] [logging.py:96:log_dist] [Rank 0] rank=0 time (ms) | optimizer_allgather: 417.75 | optimizer_gradients: 0.57 | optimizer_step: 0.49
[2024-09-25 14:00:21,199] [INFO] [logging.py:96:log_dist] [Rank 0] rank=0 time (ms) | forward_microstep: 1311.59 | backward_microstep: 4363.83 | backward_inner_microstep: 2968.95 | backward_allreduce_microstep: 1394.86 | step_microstep: 445.37
[2024-09-25 14:00:21,199] [INFO] [logging.py:96:log_dist] [Rank 0] rank=0 time (ms) | forward: 1311.58 | backward: 4363.83 | backward_inner: 2968.95 | backward_allreduce: 1394.86 | step: 445.39
Replace train sampler!!
```

**Comment by CSammyfd** [comment]
感谢回复，目前探明原因是混入了混排数据，通过某种奇怪的机理引发了llm推理变慢

**Comment by czczup** [comment]
感谢反馈，我之前没怎么注意这一方面，确实训练过程中偶尔有出现变慢，之前还以为是卡在数据读取..

**Comment by CSammyfd** [comment]
> 感谢反馈，我之前没怎么注意这一方面，确实训练过程中偶尔有出现变慢，之前还以为是卡在数据读取..

刚看到你的回复，我可以再提供一些更详细的信息：这个问题的触发条件是
1）用zero3
2）一个global batch内，不同样本间图像数量差别大

目前我们就把单图数据和图文混排数据分开stage训了（用zero2的话有些大体量的模型训不起来），然后图文混排数据下采样以节省时间，之后可能看看是否实现一下groupbyimgnum这种

但根据我目前对zero的理解上，我没法理解这两个事情是怎么耦合的，如果你们这边得知了底层原理的话，还望告知一下hhh

**Comment by Purshow** [comment]
您好，我也碰到了使用qwen在base model预训练时发生耗时过长的问题，qwen2 7b pretrain大概要10h，使用的llava的pretrain数据，conv_style选择的heremes，请问您能否分享下您训练所使用的代码呢？

**Comment by Purshow** [comment]
> 如果是deepspeed显示的forward时间异常，也有可能是卡在了dataloader的数据读取上：
> 
> ```
> [2024-09-25 14:00:21,198] [INFO] [logging.py:96:log_dist] [Rank 0] rank=0 time (ms) | optimizer_allgather: 417.75 | optimizer_gradients: 0.57 | optimizer_step: 0.49
> [2024-09-25 14:00:21,199] [INFO] [logging.py:96:log_dist] [Rank 0] rank=0 time (ms) | forward_microstep: 1311.59 | backward_microstep: 4363.83 | backward_inner_microstep: 2968.95 | backward_allreduce_microstep: 1394.86 | step_microstep: 445.37
> [2024-09-25 14:00:21,199] [INFO] [logging.py:96:log_dist] [Rank 0] rank=0 time (ms) | forward: 1311.58 | backward: 4363.83 | backward_inner: 2968.95 | backward_allreduce: 1394.86 | step: 445.39
> Replace train sampler!!
> ```

请问对于qwen7b+clip，您的batch_size的设置是多少呢?我发现我基于internvl的codebase所写的代码只能将batchsize设置到64（8*a100）再多就爆了
