### ISSUE TITLE
I am here https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html I only understand the data format, but I want to use my own data to create a dataset that can be applied to fine-tuning. Do you have any related tutorials?

### ISSUE THREAD

**Issue by llll111111** [OpenGVLab/InternVL#610]

**Comment by YeShenglong1** [comment]
Regarding creating a dataset for fine-tuning with your own data, I recommend checking out this tutorial: https://internvl.readthedocs.io/en/latest/internvl2.0/finetune.html. It provides detailed guidance on preparing your data and the steps for fine-tuning, which will be very helpful for using your own dataset.

If you have any specific questions or need further assistance, feel free to ask!
