### ISSUE TITLE
[Feature] Support for RLHF Training Techniques (e.g. DPO)

### ISSUE THREAD

**Issue by fabriceyhc** [OpenGVLab/InternVL#614]
### Motivation

Right now it appears that InternVL only supports SFT, but it would be helpful to expand on this with preference datasets. This would allow for an even more diverse fine-tuning and potentially higher performance in VL models. 

### Related resources

https://github.com/hiyouga/LLaMA-Factory?tab=readme-ov-file#supported-training-approaches

**Comment by lll2343** [comment]
Hi, 

you might find this helpful: [https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/shell/internvl2.0_mpo](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/shell/internvl2.0_mpo).
