### ISSUE TITLE
测试评分高，为什么有些样例效果不如Qwen-VL

### ISSUE THREAD

**Issue by whysirier** [OpenGVLab/InternVL#62]
![1](https://github.com/OpenGVLab/InternVL/assets/142364107/afc9d20b-929b-4e3d-a0e3-39ee3958eef4)
![2](https://github.com/OpenGVLab/InternVL/assets/142364107/fb6e50af-5d02-4f0f-9d07-75a8803f256f)

**Comment by czczup** [comment]
<img width="469" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/45b021c3-11f9-4ea3-87b5-701876ec3b53">

您好，您试的这个应该是InternVL-Chat-V1.2-Plus吧。我试了一下InternVL-Chat-V1.1可以好这个问题，但V1.2-Plus做不好。我感觉主要是受到学术数据集和用户体验数据集比例的影响。

**Comment by czczup** [comment]
我们有计划在收集提高用户体验的数据，后续会继续更新版本

**Comment by whysirier** [comment]
> <img alt="image" width="469" src="https://private-user-images.githubusercontent.com/23737120/312400582-45b021c3-11f9-4ea3-87b5-701876ec3b53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNzgyODIsIm5iZiI6MTcxMDM3Nzk4MiwicGF0aCI6Ii8yMzczNzEyMC8zMTI0MDA1ODItNDViMDIxYzMtMTFmOS00ZWEzLTg3YjUtNzAxODc2ZWMzYjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAwNTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZDc5OTM1OWFlNzBmMjMwYmIzOGI4NzlkZjI1NDhlMTBjYTYwZGEzNmIzMzE4ZDQ5NzUzMzIyMGQ2NmQ1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uWnyxrqTMRAGbqKQwu-xzqG_R9LyzBYgUVzssgonCpY">
> 您好，您试的这个应该是InternVL-Chat-V1.2-Plus吧。我试了一下InternVL-Chat-V1.1可以好这个问题，但V1.2-Plus做不好。我感觉主要是受到学术数据集和用户体验数据集比例的影响。

是的, plus版感觉效果不好，谢谢
