### ISSUE TITLE
Evaluate grounding

### ISSUE THREAD

**Issue by lifan724** [OpenGVLab/InternVL#625]
InvernVl-8B, use prompt 
"Please provide the bounding box coordinates of the region this sentence describes: <ref>human</ref>"? 
to get bbox. However, the output of model  is 
"The bounding box coordinates of the region this sentence describes are [x1, y1, x2, y2]."

**Comment by YeShenglong1** [comment]
It seems that the model's output is normal. Could you please provide more details about your issue?
