### ISSUE TITLE
学习率设定问题请教

### ISSUE THREAD

**Issue by Wangman1** [OpenGVLab/InternVL#628]
### 📚 The doc issue

请问在预训练阶段（训练mlp）和 sft（训练vit+mlp+llm）的学习率分别推荐设定多少合适呢，谢谢您~

**Comment by yuecao0119** [comment]
感谢您的提问。可以参考我们的[训练脚本](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/shell)，里面有不同大小模型的训练配置，包括学习率等。希望能提供帮助。
