### ISSUE TITLE
[Docs] VL模型中，视觉模型和语言模型如何串联？

### ISSUE THREAD

**Issue by zixi01chen** [OpenGVLab/InternVL#630]
### 📚 The doc issue

现在在进行端侧部署，并单独导出了vit模型，输入输出信息：
name: input
tensor: float32[1,3,448,448]

name: output
tensor: float32[1,1025,1024]
name: 2452
tensor: float32[1,1024]

现在怎么和语言模型qwen0.5B进行串联？有没有相关说明？

**Comment by czczup** [comment]
您好，您可以参考这部分的代码：
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py#L268
