### ISSUE TITLE
[Feature] When will the InternVL2 paper get released?

### ISSUE THREAD

**Issue by KeesariVigneshwarReddy** [OpenGVLab/InternVL#631]
### Motivation

I want to understand the architecture behind InternVL2 models so that I can implement the same for my Dense Video Captioning task on UCA (UCF crime annotation) dataset. 

Pretty impressed state of the art results, I want to use the foundation models in my work.

Perhaps I could gain better insights about model architecture, training settings, hyperparameters and implementation details from the **research paper**.

**Comment by lll2343** [comment]
Hi,

For detailed information on the model architecture, training, and hyperparameters, you can refer to the latest InternVL 2.5 paper here: [[InternVL 2.5 Paper](https://huggingface.co/papers/2412.05271)](https://huggingface.co/papers/2412.05271). It covers both InternVL2 and 2.5 in detail.

Hope this helps!
