### ISSUE TITLE
[Bug] pretrain和finetune时，好像并没有处理<image>token在后面的问题。

### ISSUE THREAD

**Issue by thbupt** [OpenGVLab/InternVL#654]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

比如在internvl1.2 Reproduce中用的这个数据集
![image](https://github.com/user-attachments/assets/907b8f3a-0481-4036-92bd-e8d0aea42ec0)
在这个数据集里，有的image的token是默认放到query的后面的，
![image](https://github.com/user-attachments/assets/956547ca-cbd2-4d16-8fdf-45562dfb9ffe)
理论上image 的 token应该在query的最前面吧，但我看finetune和pretrain的代码里，并没有对这种情况做处理。
![image](https://github.com/user-attachments/assets/6fe4cb5d-6088-40b8-9ce5-ad0b3c764e14)

### Reproduction

None

### Environment

```Shell
None
```

**Comment by Weiyun1025** [comment]
这个放前面或者后面都是可以的，只要图像有放进去就行

**Comment by thbupt** [comment]
> 这个放前面或者后面都是可以的，只要图像有放进去就行

@Weiyun1025 但这边在后面的attention计算里，好像question就关注不到image的内容了吧

**Comment by Weiyun1025** [comment]
反过来也是一样的，image就关注不到question的内容了，只要模型生成response的时候能同时看到image和question就行，训练时候这两个的顺序不是那么重要，只要推理的时候保持一致就行

**Comment by thbupt** [comment]
明白了，多谢解答
