### ISSUE TITLE
微调模型数据模板相关问题

### ISSUE THREAD

**Issue by theignorantt** [OpenGVLab/InternVL#658]
我看了internvl2微调的数据模板，但我想问一下如果不按照这个模板去微调是否会使性能下降？
具体而言，我们的数据集如下所示

"conversations": [
            {
                "from": "human",
                "value": "What is the functionality of the element at: [0.6216,0.9507,0.7432,1.0000]?"
            },
            {
                "from": "gpt",
                "value": "Click to navigate to the Account tab."
            }
        ],

其中internvl2用的模板则用`<ref></ref><box></box>`的形式框起来了，且坐标均是相对坐标乘1000，那么如果我不按这种形式来是否会导致性能下降？又该如何改成符合的微调模板？`<ref>Click to navigate to the Account tab</ref>`将动词也一起包含在内吗？
另外，我看到要求带图的数据需要在第一句话前面加上`<image>\n`，我放在其他位置是否可以？

**Comment by yuecao0119** [comment]
非常感谢你的提问。

1. 其中internvl2用的模板则用<ref></ref><box></box>的形式框起来了，且坐标均是相对坐标乘1000，那么如果我不按这种形式来是否会导致性能下降？
回答：是的，因为我们grounding训练的数据主要采用这种形式。如果少量数据的训练推荐继续采用这种形式。

2. 又该如何改成符合的微调模板？
回答：我们在[项目文档](https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#grounding-detection-data)中介绍了各种类型数据的详细格式，这里也提供了如何转换坐标，希望能提供帮助。

3. <ref>Click to navigate to the Account tab</ref>将动词也一起包含在内吗？
回答：只需要包含形容词和名词

4. 另外，我看到要求带图的数据需要在第一句话前面加上<image>\n，我放在其他位置是否可以？
回答：放在其他位置也是可以的。不过对于单图形式，我们的训练数据大部分是放在问题最前面的，所以采用同样设置，模型的响应会更有效。
