### ISSUE TITLE
[Docs] A question of Mini-InternVL

### ISSUE THREAD

**Issue by xuliu-cyber** [OpenGVLab/InternVL#660]
### 📚 The doc issue

Hello, I read the paper "Mini-InternVL: A Flexible-Transfer Pocket Multimodal Model with 5% Parameters and 90% Performance", I wonder that during the domain adaptation phase, do you fine-tune three models separately in each domain? Thank you!

**Comment by G-z-w** [comment]
We fine-tune models separately for each domain.
