### ISSUE TITLE
Image Missing

### ISSUE THREAD

**Issue by chg0901** [OpenGVLab/InternVL#67]
File address: https://github.com/OpenGVLab/InternVL/blob/main/BLOG.md#internvl-chat-v12

Image link: https://github.com/czczup/InternVL-MoE/assets/23737120/9b68aa35-40fd-4e81-9595-d404cbbfc6bd

![image](https://github.com/OpenGVLab/InternVL/assets/8240984/42ec5bc8-8622-4f93-89cd-11f3f7069965)

**Comment by czczup** [comment]
Hi, thanks for your feedback. I will fix this broken image link.
