### ISSUE TITLE
normalize_type

### ISSUE THREAD

**Issue by Purshow** [OpenGVLab/InternVL#682]
在internvl中，对于image的normalize_type都采用的imagenet，是为了符合gvlab的internvit嘛？请问如果我想使用clip去替代，是否是要把normalize_type改为“clip”

**Comment by wjn922** [comment]
是的，如果用clip就需要把normalize_type改为“clip”。

**Comment by Purshow** [comment]
> 是的，如果用clip就需要把normalize_type改为“clip”。

谢谢您的回复！
