### ISSUE TITLE
about internvl2_2b_internlm2_1_8b_dynamic_res_finetune_drivelm.sh

### ISSUE THREAD

**Issue by hustvl-luckybear** [OpenGVLab/InternVL#684]
Can you share the download link for the file "./InternVL-Domain-Adaptation-Data/train_meta/internvl_1_2_finetune_drivelm.json"? drivelm data set has three data sets: train,val and test. I am not sure how to load train and val in finetune stage.
Look forward to your reply, thank you!

**Comment by hustvl-luckybear** [comment]
i have sloved the problem

**Comment by Mozhgan91** [comment]
can you please explain how you solved the problem? Specifically, how do you perform image processing and what data sets you used for the finetuning?
