### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'flash_attn'

### ISSUE THREAD

**Issue by DankoZhang** [OpenGVLab/InternVL#690]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

@czczup @h微调InternVL2时，报了这个错误，怎么能不使用flash_attn呢？

### Reproduction

GPUS=2 PER_DEVICE_BATCH_SIZE=1 sh shell/internvl2.0/2nd_finetune/internvl2_4b_phi3_3_8b_dynamic_res_2nd_finetune_lora.sh

### Environment

```Shell
cuda12.2
```

**Comment by czczup** [comment]
您好，我们会在近期加个option去关闭flash attention，目前代码默认使用flash attention，如果您急需不使用flash attention进行训练，需要改一下这里的代码：https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L868

**Comment by popoyaya** [comment]
> 您好，我们会在近期加个选项去关闭flash注意力，目前代码默认使用flash注意力，如果您急需不使用flash注意力进行训练，需要修改一下这里的代码： https: [//github.com/OpenGVLab/InternVL /blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L868](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L868)

请问应该如何修改代码，在微调时关闭flash-attn？谢谢！

**Comment by popoyaya** [comment]
> 您好，我们会在近期加个选项去修改关闭flash注意力，目前代码默认使用flash注意力，如果您急需不使用flash注意力进行训练，需要一下这里的代码：https: [//github.com/ OpenGVLab/InternVL /blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L868](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_finetune.py#L868)

请问应该如何修改代码，在微调时关闭flash-attn？谢谢！

**Comment by ChenJian7578** [comment]
我也遇到这个问题了，请问已经修改了吗
