### ISSUE TITLE
Not a bug, just a newbie question.  Does this model work under "lm-studio" or it currently has to be run through CLI?

### ISSUE THREAD

**Issue by kundeng** [OpenGVLab/InternVL#697]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Not a bug

### Reproduction

Not a bug. 

### Environment

```Shell
n/a
```

### Error traceback

```Shell
n/a
```

**Comment by czczup** [comment]
Thank you for your question! At the moment, this model is not supported in "lm-studio" and can only be run through the CLI. However, we are excited about the possibility of supporting "lm-studio" in the future, and it's definitely something we’re considering. Stay tuned for updates!
