### ISSUE TITLE
[Feature] Attention Visualization

### ISSUE THREAD

**Issue by paulgavrikov** [OpenGVLab/InternVL#700]
### Motivation

Could you kindly share code to visualize the attention to, both, the prompt (tokens) and the input image in InternVL?

**Comment by sms-s** [comment]
+1

**Comment by czczup** [comment]
Thank you for your interest in InternVL. At the moment, we do not have plans to implement the feature to visualize attention. However, the codebase is open, and you're welcome to modify it to suit your needs. We hope you find this helpful and appreciate your understanding!

**Comment by Eli-YiLi** [comment]
https://github.com/xmed-lab/TAM

In this project, visualization for MLLM is supported. 
It can be used to compare MLLMs in a visual aspect.

<img width="1003" height="779" alt="Image" src="https://github.com/user-attachments/assets/df99ee51-9d04-4059-ae53-6494db2a8364" />
