### ISSUE TITLE
[Bug] clip_benchmark评估internvn-g使用lora微调的模型性能极低

### ISSUE THREAD

**Issue by jiaaozhe** [OpenGVLab/InternVL#701]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

clip_benchmark评估internvn-g使用lora微调的模型性能极低，原因是lora_alpha参数不一致

评估代码 clip_benchmark/clip_benchmark/models/internvl_huggingface/modeling_internvl.py line 208没有传入config.use_backbone_lora参数
        if config.use_backbone_lora:
            self.wrap_backbone_lora(r=config.use_backbone_lora)
        if config.use_qllama_lora:
            self.wrap_qllama_lora(r=config.use_qllama_lora)

训练代码 internvl_g/internvl/model/internvl_stage2_retrieval/modeling_internvl.py line 250 
        if config.use_backbone_lora:
            self.wrap_backbone_lora(r=config.use_backbone_lora, lora_alpha=config.use_backbone_lora * 2)
        if config.use_qllama_lora:
            self.wrap_qllama_lora(r=config.use_qllama_lora, lora_alpha=config.use_qllama_lora * 2)

上述两个文件的lora配置参数不一致，导致模型评估结果性能极低

### Reproduction

None

### Environment

```Shell
None
```

**Comment by czczup** [comment]
感谢反馈，我修一下这个bug
