### ISSUE TITLE
No eval.py find  in the CodeLine in evaluate_vqa.py 

### ISSUE THREAD

**Issue by YihangLou** [OpenGVLab/InternVL#702]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

os.system(python_path + ' eval/vqa/convert_gqa_for_eval.py --src ' +
          results_file + ' --dst ' + dst_file)
command = f'cd ./data/gqa/ && {python_path} eval.py --tier testdev_balanced && cd ../../'
print(command)
accuracy = subprocess.check_output(command, shell=True, universal_newlines=True)

However, no eval.py is provided in the gqa or vqa file folder. It shows no files find error.

### Reproduction

I have check the code files, no corresponding files are found

### Environment

```Shell
No comments
```

### Error traceback

```Shell
No comments
```

**Comment by czczup** [comment]
Hello, this eval.py and other files of GQA are provided by the GQA dataset official.

You can download them from the official website of GQA: 

https://cs.stanford.edu/people/dorarad/gqa/evaluate.html
