### ISSUE TITLE
[Feature] 为什么LoRA SFT把freeze_backbone设为True

### ISSUE THREAD

**Issue by lck1201** [OpenGVLab/InternVL#705]
### Motivation

为什么internvl_chat/shell/internvl2.0/2nd_finetune/internvl2_40b_hermes2_yi_34b_dynamic_res_2nd_finetune_lora.sh，用LoRA跑SFT需要把freeze_backbone，freeze_mlp，freeze_backbone设置为True？是指梯度不直接更新权重吗？

**Comment by czczup** [comment]
您好，这个指的是冻住原本的参数，只训练新增的lora参数。
