### ISSUE TITLE
InternVL2-Llama3-76B speed on RTX3090 is slow

### ISSUE THREAD

**Issue by gggxxl** [OpenGVLab/InternVL#709]
we load InternVL2-Llama3-76B in 8-bit on 4 RTX3090, it takes 1minute or longer time to process 500 tokens prompt and 100 tokens output, is this speed normal?

**Comment by czczup** [comment]
Hello, the 8-bit mode provided by `transformers` does indeed slow down the speed. You might want to try using AWQ quantization with lmdeploy.
