### ISSUE TITLE
使用双卡3090，分布式加载 InternVL-14B-224px 进行推理，InternVL-C 的预测结果中只有image3对应的prob值与提供的参考值不同，请问是为什么？

### ISSUE THREAD

**Issue by lexilii** [OpenGVLab/InternVL#71]
InternVL-C probs:  tensor([[9.9609e-01, 5.2185e-03, 6.0070e-08],
        [2.2949e-02, 9.7656e-01, 5.9903e-06],
        [2.9057e-06, 6.6280e-05, 1.0000e+00]], device='cuda:0',
       dtype=torch.bfloat16, grad_fn=<SoftmaxBackward0>)

**Comment by czczup** [comment]
如果只是一点小误差的话，应该没事

**Comment by liumingzhu6060** [comment]
请问题主能不能分享一下InternVL-14B-224px加载到两张卡上的代码
