### ISSUE TITLE
[Docs] [Grounding] 微调模型 

### ISSUE THREAD

**Issue by wwYinYin** [OpenGVLab/InternVL#710]
### 📚 The doc issue

[Grounding] 如果我想要微调模型，使其能同时输出question中提到的多个主体的bbox，我应该怎么构建微调数据集

**Comment by czczup** [comment]
您好，您可以参考[这里的文档](https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#grounding-detection-data)来构建训练数据集。

具体来说，第一步是把坐标框归一化到[0, 1000]的范围内，然后构建QA对，并转换成jsonl的格式。

例如：
```json
{
  "id": 0,
  "image": "图像路径",
  "conversations": [
    {
      "from": "human",
      "value": "<image>\nPlease detect and label all XXX in the following image and mark their positions."
    },
    {
      "from": "gpt",
      "value": "Sure, I will detect and label all XXX in the image and mark their positions.\n\n```\n<ref>XXX</ref><box>[[x1, y1, x2, y2], [x3, y3, x4, y4]]</box>\n```"
    }
  ]
}
```

注意上面这个是为了方便可视化的json格式，请把数据转换成jsonl格式。

**Comment by corkiyao** [comment]
> 您好，您可以参考[这里的文档](https://internvl.readthedocs.io/en/latest/get_started/chat_data_format.html#grounding-detection-data)来构建训练数据集。
> 
> 具体来说，第一步是把坐标框归一化到[0, 1000]的范围内，然后构建QA对，并转换成jsonl的格式。
> 
> 例如：
> 
> {
>   "id": 0,
>   "image": "图像路径",
>   "conversations": [
>     {
>       "from": "human",
>       "value": "<image>\nPlease detect and label all XXX in the following image and mark their positions."
>     },
>     {
>       "from": "gpt",
>       "value": "Sure, I will detect and label all XXX in the image and mark their positions.\n\n```\n<ref>XXX</ref><box>[[x1, y1, x2, y2], [x3, y3, x4, y4]]</box>\n```"
>     }
>   ]
> }
> 注意上面这个是为了方便可视化的json格式，请把数据转换成jsonl

请问可以使用中文微调吗？就是将“Please detect and label all XXX in the following image and mark their positions”变成中文，回答也是中文。另外单目标，但是多个数量的格式怎么创建呢？
