### ISSUE TITLE
[Bug] AttributeError: 'MultimodalDPOTrainer' object has no attribute 'get_batch_logps'

### ISSUE THREAD

**Issue by zxc351200** [OpenGVLab/InternVL#711]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

mpo训练出现 AttributeError: 'MultimodalDPOTrainer' object has no attribute 'get_batch_logps'
我目前没有在trainer_dpo.py的MultimodalDPOTrainer里发现get_batch_logps，是漏提交了吗？
报错具体在：
all_logps, size_completion = self.get_batch_logps(
            all_logits,
            concatenated_batch["concatenated_labels"],
            # average_log_prob=self.loss_type == "ipo",
            is_encoder_decoder=self.is_encoder_decoder,
            label_pad_token_id=self.label_pad_token_id,
        )

### Reproduction

No

### Environment

```Shell
transformers
```

**Comment by Weiyun1025** [comment]
你好，可以试一下安装`transformers==4.37.2`和`trl==0.9.6`，这几个参数和函数都是`trl.DPOTrainer`自带的

**Comment by zxc351200** [comment]
好的，多谢

**Comment by yhl-hubhub** [comment]
环境为`transformers==4.37.2`和`trl==0.9.6`时，使用lora训练，最后保存会卡住，请问这个如何解决

**Comment by kfzyqin** [comment]
Yes, how can we get the function?
