### ISSUE TITLE
AttributeError: 'MultimodalDPOTrainer' object has no attribute 'is_vision_model'

### ISSUE THREAD

**Issue by shengyuwoo** [OpenGVLab/InternVL#714]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

MPO训练时在trainer_dpo.py脚本中缺少对 self.is_vision_model、self.aux_loss_enabled等变量的定义，导致在 MultimodalDPOTrainer 类中无法使用这些属性。

### Reproduction

  File "/code/InternVL/internvl_chat/internvl/train/trainer_dpo.py", line 193, in get_batch_loss_metrics
    forward_output = self.concatenated_forward(model, batch)
  File "/code/InternVL/internvl_chat_mpo/internvl/train/trainer_dpo.py", line 100, in concatenated_forward
    is_vision_model=self.is_vision_model,

### Environment

```Shell
transformers             4.45.0
trl                      0.9.2
```

**Comment by Weiyun1025** [comment]
你好，可以试一下安装`transformers==4.37.2`和`trl==0.9.6`，这几个参数都是`trl.DPOTrainer`自带的

**Comment by shengyuwoo** [comment]
> 你好，可以试一下安装`transformers==4.37.2`和`trl==0.9.6`，这几个参数都是`trl.DPOTrainer`自带的

好的，谢谢。
