### ISSUE TITLE
[Docs] can not find evaluate.sh file

### ISSUE THREAD

**Issue by Mollylulu** [OpenGVLab/InternVL#718]
### 📚 The doc issue

Hi, I wonder where is the `evaluate.sh` file, mentioned in the [Document evaluation part](https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html#).

Thank you for your guidance, or if anyone else can assist with this issue, thanks!

**Comment by Mollylulu** [comment]
I use the `evaluate.sh` found udner `internvl_g` dir to do caption-coco evaluation with 26B model, but got some problems when loading the 26B model back.

```
Some weights of InternVLModel were not initialized from the model checkpoint at pretrained/InternVL2-26B and are newly initialized
...
```
layers from `clip_projector`, `clip_projector2` and 'qllama` are missing their weights. do you know what is wrong here?

I run evaluate with:
```
bash internvl_g/evaluate.sh pretrained/InternVL2-26B "caption-coco --dynamic
```

**Comment by AmanDesai-coder** [comment]
Wait, sorry, were you able to resolve this? I was also confused about this aspect. Thank you!

**Comment by czczup** [comment]
Hi, evaluate.sh is located at here: 

https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/evaluate.sh
