### ISSUE TITLE
[Feature] 关于InternVL2-8B-MPO模型的指令跟随能力

### ISSUE THREAD

**Issue by 77h2l** [OpenGVLab/InternVL#719]
### Motivation

相同的prompt输入，要求输出为标准的JSON格式，InternVL2-8B基本可以做到精准的指令跟随，输出基本符合JSON格式，但是InternVL2-8B-MPO无论怎么修改prompt要求不输出JSON格式以外的其他内容，总是会有冗余的字符串过度cot的内容输出，请问这个符合预期吗，原因又是什么哇

**Comment by Weiyun1025** [comment]
这个可能是因为MPO训练的时候只用了CoT相关数据，导致非CoT场景的指令跟随能力下降了，我们会在下一版迭代的时候尽量解决这个问题
