### ISSUE TITLE
多轮对话

### ISSUE THREAD

**Issue by LRHstudy** [OpenGVLab/InternVL#72]
目前的internvl-chat-chinese-v1-2-plus中是没有支持多轮对话的吗，历史对话history无法传入到chat函数中

**Comment by LRHstudy** [comment]
modeling_internvl_chat.py中的chat函数做以下修改后，可以支持多轮对话，但是还不能支持输入多张图像。
    def chat(self, tokenizer, pixel_values, question, generation_config,
             IMG_START_TOKEN='<img>', IMG_END_TOKEN='</img>', IMG_CONTEXT_TOKEN='<IMG_CONTEXT>',
             history=None):

        img_context_token_id = tokenizer.convert_tokens_to_ids(IMG_CONTEXT_TOKEN)
        self.img_context_token_id = img_context_token_id

        from .conversation import get_conv_template

        template = get_conv_template(self.template)
        image_tokens = IMG_START_TOKEN + IMG_CONTEXT_TOKEN * self.num_image_token + IMG_END_TOKEN
        if history is None:
            history = []

        image_loaded =False
        for turn_query, turn_response in history:
            template.append_message(template.roles[0], turn_query)
            template.append_message(template.roles[1], turn_response)
            if image_tokens in turn_query:   #看历史记录中是否已经加载图像
                image_loaded = True

        if pixel_values is not None and not image_loaded:
            template.append_message(template.roles[0], image_tokens + '\n' + question)
        else:
            template.append_message(template.roles[0], question)

        template.append_message(template.roles[1], None)
        query = template.get_prompt()
        model_inputs = tokenizer(query, return_tensors='pt')
        input_ids = model_inputs['input_ids'].cuda()
        attention_mask = model_inputs['attention_mask'].cuda()

        generation_output = self.generate(
            pixel_values=pixel_values,
            input_ids=input_ids,
            attention_mask=attention_mask,
            **generation_config
        )
        response = tokenizer.batch_decode(generation_output, skip_special_tokens=True)[0]
        # query_to_print = query.replace(image_tokens, '<image>')
        # print(query_to_print, response)
        
        if pixel_values is not None and not image_loaded:
            history.append((image_tokens + '\n' + question, response))
        else:
            history.append((question, response))

        return response, history

**Comment by czczup** [comment]
您好，感谢您的代码支持。我刚刚实现了一版多轮对话的chat，已经更新到hf上了，才发现您这里也写了这段代码，非常感谢。

考虑到兼容以前旧的代码没有return history的形式（因为VLMEvalKit里面使用了那样的形式），现在可以这样使用：
```
import torch
from PIL import Image
from transformers import AutoModel, CLIPImageProcessor
from transformers import AutoTokenizer

path = "OpenGVLab/InternVL-Chat-Chinese-V1-2-Plus"
# If you have an 80G A100 GPU, you can put the entire model on a single GPU.
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True).eval().cuda()
# Otherwise, you need to set device_map='auto' to use multiple GPUs for inference.
# model = AutoModel.from_pretrained(
#     path,
#     torch_dtype=torch.bfloat16,
#     low_cpu_mem_usage=True,
#     trust_remote_code=True,
#     device_map='auto').eval()

tokenizer = AutoTokenizer.from_pretrained(path)
image = Image.open('./examples/image2.jpg').convert('RGB')
image = image.resize((448, 448))
image_processor = CLIPImageProcessor.from_pretrained(path)

pixel_values = image_processor(images=image, return_tensors='pt').pixel_values
pixel_values = pixel_values.to(torch.bfloat16).cuda()

generation_config = dict(
    num_beams=1,
    max_new_tokens=512,
    do_sample=False,
)

# 单轮对话
question = "请详细描述图片"
response = model.chat(tokenizer, pixel_values, question, generation_config)
print(question, response)

# 多轮对话
question = "请详细描述图片"
response, history = model.chat(tokenizer, pixel_values, question, generation_config, history=None, return_history=True)
print(question, response)

question = "请根据图片写一首诗"
response, history = model.chat(tokenizer, pixel_values, question, generation_config, history=history, return_history=True)
print(question, response)
```

另外，关于多图推理，因为目前这些模型的训练都是单图的，所以暂时没有支持这一功能；在之后若有图文交错训练的版本，会支持上多图推理。
