### ISSUE TITLE
[Docs] is this a mistake in these  two paper ？

### ISSUE THREAD

**Issue by wangwang110** [OpenGVLab/InternVL#727]
### 📚 The doc issue

<img width="928" alt="企业微信截图_ede9a163-8a0f-44ac-aa2c-fbcabf366ca1" src="https://github.com/user-attachments/assets/1267a6eb-d19f-4826-99ca-a6bdc3486fc9">
How Far Are We to GPT-4V? Closing the Gap to Commercial Multimodal Models with Open-Source Suites

<img width="525" alt="企业微信截图_8cbd1b93-3c30-4788-9527-a3aac8788b0a" src="https://github.com/user-attachments/assets/4f5988a5-1abe-4a03-8227-2bab2a33f871">
Mini-InternVL: A Flexible-Transfer Pocket Multimodal Model with 5% Parameters and 90% Performance

**Comment by czczup** [comment]
Hello, actually, "pixel shuffle" is a typo. Since it is a downsampling operation, it should be "pixel unshuffle." We will update and standardize it to "pixel unshuffle" moving forward.
