### ISSUE TITLE
[Docs] What is the difference between internvl_g, internvl_chat_llava, and internvl_chat?

### ISSUE THREAD

**Issue by 20191864218** [OpenGVLab/InternVL#729]
### 📚 The doc issue

Dear experts, what is the difference between internvl_g, internvl_chat_llava, and internvl_chat? If you can answer this question, it would be a great help to me. Thank you very much!

**Comment by yuecao0119** [comment]
Thank you very much for your question. The three models you mentioned are all proposed in our InternVL 1.0. For a detailed introduction, please refer to our [1.0 paper](https://huggingface.co/papers/2312.14238).

![image](https://github.com/user-attachments/assets/2f9efd5d-3969-45c8-b993-4cd39ec3bdd3)

* internvl_g: For contrastive tasks, as shown in Figure 4 (a) (b), we introduce two inference modes: InternVL-C and InternVL-G, using the vision encoder or the combination of InternViT and QLLaMA to encode visual features.

* internvl_chat: For multi-modal dialogue, we introduce InternVL-Chat, leveraging InternVL as the visual component to connect with LLMs.

* internvl_chat_llava: [InternVL-Chat-LLaVA](https://internvl.readthedocs.io/en/latest/internvl1.0/internvl_chat_llava.html#training) is a code implementation of InternVL-Chat V1.0. We mainly use the LLaVA code base to evaluate the performance of InternVL (InternViT-6B) in creating MLLM.

**Comment by zoezhu** [comment]
> Thank you very much for your question. The three models you mentioned are all proposed in our InternVL 1.0. For a detailed introduction, please refer to our [1.0 paper](https://huggingface.co/papers/2312.14238).
> 
> ![image](https://private-user-images.githubusercontent.com/81856177/394093204-2f9efd5d-3969-45c8-b993-4cd39ec3bdd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzExMzIsIm5iZiI6MTczMzk3MDgzMiwicGF0aCI6Ii84MTg1NjE3Ny8zOTQwOTMyMDQtMmY5ZWZkNWQtMzk2OS00NWM4LWI5OTMtNGNkMzllYzNiZGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAyMzM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MjMyMDFmYWJjODdiOGY0ODU2M2Q1OWM2YTk5MmU5OTlhNGNlN2JmNTBhZjVkNWYzZDk5ODU4MjM2ZTY5ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2BmX5AnW8JD_eNRxEN1ul1ujHtVzAMUwBAT0rvGRMZo)
> 
> * internvl_g: For contrastive tasks, as shown in Figure 4 (a) (b), we introduce two inference modes: InternVL-C and InternVL-G, using the vision encoder or the combination of InternViT and QLLaMA to encode visual features.
> * internvl_chat: For multi-modal dialogue, we introduce InternVL-Chat, leveraging InternVL as the visual component to connect with LLMs.
> * internvl_chat_llava: [InternVL-Chat-LLaVA](https://internvl.readthedocs.io/en/latest/internvl1.0/internvl_chat_llava.html#training) is a code implementation of InternVL-Chat V1.0. We mainly use the LLaVA code base to evaluate the performance of InternVL (InternViT-6B) in creating MLLM.

Is it possible to use InternVL2_5-8B in internvl_g structure? I want to replace Llama with InternVL2.5, but it seems has no cross attention part and no query either. What I can do to use InternVL2.5 in internvl_g and finetune it?  @yuecao0119

**Comment by yuecao0119** [comment]
Sorry, I may not understand what you mean.
Starting from InternVL 1.5, we have abandoned the QLLaMA middleware and adopted the simpler ViT-MLP-LLM framework. So InternVL 2.5 is a complete multi-modal dialogue model, and its purpose is closer to internvl_chat.

**Comment by 20191864218** [comment]
> Thank you very much for your question. The three models you mentioned are all proposed in our InternVL 1.0. For a detailed introduction, please refer to our [1.0 paper](https://huggingface.co/papers/2312.14238).
> 
> ![image](https://private-user-images.githubusercontent.com/81856177/394093204-2f9efd5d-3969-45c8-b993-4cd39ec3bdd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzMwMjYsIm5iZiI6MTczNDA3MjcyNiwicGF0aCI6Ii84MTg1NjE3Ny8zOTQwOTMyMDQtMmY5ZWZkNWQtMzk2OS00NWM4LWI5OTMtNGNkMzllYzNiZGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA2NTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlM2NlYTdkMjI3YTdlNTIxOTIxYjU5YzZmZmY4MWY2ZmM4NzQ3MjRmZGE0OTk3ZTVhYmExMjk4MGMxYTdmMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nRb6wp3qcjUlFFiOiQcD5PZYoCPGGzSnZRU_9djiZwA)
> 
> * internvl_g: For contrastive tasks, as shown in Figure 4 (a) (b), we introduce two inference modes: InternVL-C and InternVL-G, using the vision encoder or the combination of InternViT and QLLaMA to encode visual features.
> * internvl_chat: For multi-modal dialogue, we introduce InternVL-Chat, leveraging InternVL as the visual component to connect with LLMs.
> * internvl_chat_llava: [InternVL-Chat-LLaVA](https://internvl.readthedocs.io/en/latest/internvl1.0/internvl_chat_llava.html#training) is a code implementation of InternVL-Chat V1.0. We mainly use the LLaVA code base to evaluate the performance of InternVL (InternViT-6B) in creating MLLM.

Thank you for your response, which has given me a very clear understanding！ May I ask what are the differences between[https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat](internvl_chat) and [https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat_llava](internvl_chat_llava), and is there any difference in their performance?
Thank you again for your answer！

**Comment by yuecao0119** [comment]
> > Thank you very much for your question. The three models you mentioned are all proposed in our InternVL 1.0. For a detailed introduction, please refer to our [1.0 paper](https://huggingface.co/papers/2312.14238).
> > ![image](https://private-user-images.githubusercontent.com/81856177/394093204-2f9efd5d-3969-45c8-b993-4cd39ec3bdd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzMwMjYsIm5iZiI6MTczNDA3MjcyNiwicGF0aCI6Ii84MTg1NjE3Ny8zOTQwOTMyMDQtMmY5ZWZkNWQtMzk2OS00NWM4LWI5OTMtNGNkMzllYzNiZGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA2NTIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlM2NlYTdkMjI3YTdlNTIxOTIxYjU5YzZmZmY4MWY2ZmM4NzQ3MjRmZGE0OTk3ZTVhYmExMjk4MGMxYTdmMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nRb6wp3qcjUlFFiOiQcD5PZYoCPGGzSnZRU_9djiZwA)
> > 
> > * internvl_g: For contrastive tasks, as shown in Figure 4 (a) (b), we introduce two inference modes: InternVL-C and InternVL-G, using the vision encoder or the combination of InternViT and QLLaMA to encode visual features.
> > * internvl_chat: For multi-modal dialogue, we introduce InternVL-Chat, leveraging InternVL as the visual component to connect with LLMs.
> > * internvl_chat_llava: [InternVL-Chat-LLaVA](https://internvl.readthedocs.io/en/latest/internvl1.0/internvl_chat_llava.html#training) is a code implementation of InternVL-Chat V1.0. We mainly use the LLaVA code base to evaluate the performance of InternVL (InternViT-6B) in creating MLLM.
> 
> Thank you for your response, which has given me a very clear understanding！ May I ask what are the differences between[https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat](internvl_chat) and [https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat_llava](internvl_chat_llava), and is there any difference in their performance? Thank you again for your answer！

The internvl folder mainly contains the implementation of the V1.1~2.5 series of InternVL-Chat. Reference reports: [V1.5 paper](https://huggingface.co/papers/2404.16821), [V2.5 report](https://huggingface.co/papers/2412.05271).

The internvl-chat-llava folder mainly contains the implementation of InternVL-Chat V1.0, corresponding to Section 4.4 of our [InternVL 1.0 paper](https://huggingface.co/papers/2312.14238).

Model version evaluation, better overall performance, more supported modes.

**Comment by fangxin2github** [comment]
Is it possible to replace the ViT from InternVL2.5 with the one in InternVL-C? I would like to know whether a ViT trained with dynamic resolution methods would perform better on retrieval tasks. If it's feasible, please tell me which parts of the code need to be modified. Looking forward to your reply.
