### ISSUE TITLE
[Docs] data size of the fine-tune

### ISSUE THREAD

**Issue by ChenJian7578** [OpenGVLab/InternVL#730]
### 📚 The doc issue

What is the recommended minimum amount of data when the model is fine-tuned using lora

### Suggest a potential alternative/fix

What is the recommended minimum amount of data when the model is fine-tuned using lora

**Comment by czczup** [comment]
Hello, thank you for your question, but there is no standard answer on how much data is needed, depending on your task, it may be thousands of data samples or tens of thousands of data samples.
