### ISSUE TITLE
Evaluate on custom dataset

### ISSUE THREAD

**Issue by ILoveAkizukiKanna** [OpenGVLab/InternVL#734]
Hello,

Thank you for your great work. I want to evaluate InternVL2 on custom dataset. I have read  issue387. But I can find how to organize evaluation custom dataset in the document (https://internvl.readthedocs.io/en/latest/internvl2.0/evaluation.html) .

Besides, can I simply change evaluate_vqa.py and evaluate_caption.py to evaluate InternVL2?

Thank you

**Comment by lll2343** [comment]
After running inference, you can modify the evaluation step in the evaluate_vqa.py (line 434) and evaluate_caption.py (line 190) to suit your custom dataset’s evaluation method. Simply update the scoring logic in those sections to align with your dataset’s specific requirements.

**Comment by ILoveAkizukiKanna** [comment]
Thank you
