### ISSUE TITLE
[Bug] Chat Demo没有任何响应

### ISSUE THREAD

**Issue by duoyw** [OpenGVLab/InternVL#735]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

提供的chat demo（https://internvl.opengvlab.com/chat/542e46cb-e0f8-4ccc-b5b3-87f07d6c5d3b/0）中，模型不能响应输入问题

### Reproduction

在https://internvl.opengvlab.com/chat/542e46cb-e0f8-4ccc-b5b3-87f07d6c5d3b/0中输入问题

### Environment

```Shell
无
```

**Comment by czczup** [comment]
您好，感谢您的反馈。我们最近在调整demo的后端，现在应该可以访问了。
