### ISSUE TITLE
Regrading processing Drivelm images

### ISSUE THREAD

**Issue by Mozhgan91** [OpenGVLab/InternVL#737]
I understand that you are using *tools/images_stitching.py* to process the DriveLM images. However, the annotation file being used is *v1_1_val_nus_q_only.json*, which reads images from the validation subset. Does this mean you download the *validation* images into your defined *nuscenes* folder? Also, based on what *drivelm* subset you train the model, given that the provided fine-tuning code retrieves images from the *stitch* folder? In other  words, do you process images for the train subset using its corresponding annotation file and put both val and train images in the same *stitch* folder? I would appreciate it if you could clarify this.

**Comment by G-z-w** [comment]
Thank you for your attention.

1) You need to download the validation and trimages into the defined nuscenes folder, and then run:

```
python tools/images_stitching.py --data-root InternVL-Domain-Adaptation-Data/images/drivelm --ann-file path/to/v1_1_val_nus_q_only.json
```
   
2) We use the same code file to process both the training and validation images.

3) For the convenience of open-sourcing the code and writing documentation,  we placed the training and validation images in the same folder `drivelm/stitch/`. You can choose to place the test images in another location and then modify the `image_root` in this [script](
https://github.com/OpenGVLab/InternVL/blob/262f905675565f92565279093ccf4a8985888956/internvl_chat/eval/domain_specific/drivelm/evaluate.py#L22).
