### ISSUE TITLE
Request for Fine-Tuning Parameters of Mini-InternVL on DriveLM Dataset

### ISSUE THREAD

**Issue by BigBoomDream** [OpenGVLab/InternVL#738]
Thank you for your excellent work on "Mini-InternVL: A Flexible-Transfer Pocket Multimodal Model with 5% Parameters and 90% Performance".

![Table](https://github.com/user-attachments/assets/ac2955b2-bf3c-4d82-b923-d1582c1cf2de)

I have been reviewing Table 4 of your paper, particularly the results for Mini-InternVL models fine-tuned on the DriveLM dataset, including the variants Mini-InternVL-DA-1B, Mini-InternVL-DA-2B, and Mini-InternVL-DA-4B.

Could you kindly provide the fine-tuned model parameters (after training) for these specific variants? Access to the trained parameters would be invaluable for understanding and replicating the results presented in the paper.

Thank you for your time and assistance!

**Comment by G-z-w** [comment]
Thank you for your attention. We have released the weights after finetuning, and we welcome your suggestions.
[Mini-InternVL2-DA](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/shell/mini_internvl#adaptation-models)

**Comment by BigBoomDream** [comment]
> Thank you for your attention. We have released the weights after finetuning, and we welcome your suggestions. [Mini-InternVL2-DA](https://github.com/OpenGVLab/InternVL/tree/main/internvl_chat/shell/mini_internvl#adaptation-models)

Thank you for sharing this information! I appreciate the development team's prompt response in releasing the fine-tuned weights for Mini-InternVL2-DA. This will be very helpful for those looking to replicate and build upon the research results. The team's openness to sharing resources and welcoming suggestions demonstrates great community engagement.

Best regards!
