### ISSUE TITLE
The MMMU evaluation in the  InternVL2.5 

### ISSUE THREAD

**Issue by darkpromise98** [OpenGVLab/InternVL#739]
I have some confusion about the evaluation in the InternVL2.5 technical report.

How to understand "We report the **maximum accuracy** achieved across both direct-answer and CoT reasoning approaches on the MMMU validation and test sets" ？

Does it mean that we evaluate multiple times, and then choose the best result (in direct-answer and CoT setting) ?

![image](https://github.com/user-attachments/assets/4b997030-1b46-4147-80d9-f930ddc087b6)

**Comment by czczup** [comment]
Yes, we test twice for each model, with or without the CoT prompt, and then report the highest value. This evaluation method was inspired by the MMMU-Pro paper.

**Comment by czczup** [comment]
I will update our CoT evaluation code to VLMEvalKit soon.
