### ISSUE TITLE
WARNING: tokenization mismatch: 1 vs. 329. #turn = 6. (ignored). This dataset is product_entity.

### ISSUE THREAD

**Issue by THU-Kingmin** [OpenGVLab/InternVL#742]
SFT InternVL2.5 时一直出现警告：WARNING: tokenization mismatch: 1 vs. 329. #turn = 6. (ignored). This dataset is product_entity.

**Comment by czczup** [comment]
您好，感谢使用。只要把对话模板改成`internvl2_5`就好了。

**Comment by THU-Kingmin** [comment]
感谢，已解决，拉取最新的代码就没问题了
