### ISSUE TITLE
[Docs] Question about the contribution of large vision encoder and progressive scaling strategy to reducing training tokens

### ISSUE THREAD

**Issue by gudo7208** [OpenGVLab/InternVL#743]
### 📚 The doc issue

In the new paper, there are two places mentioning that InternVL2.5-78B uses only 1/10 of the training tokens compared to Qwen2-VL-72B:

1. When introducing the finding about large vision encoders:

> Large vision encoders significantly reduce the dependency on training data when scaling up MLLMs. As shown in Table 3, compared to Qwen2-VL-72B equipped with a 600M vision encoder, our InternVL2.5-78B with a 6B vision encoder can achieve better performance using only 1/10 of the training tokens.

2. When discussing the progressive scaling strategy:

> By employing this progressive scaling strategy, we achieve scalable model updates at a fraction of the cost typically associated with large-scale MLLM training. For example, Qwen2-VL processes a cumulative total of 1.4 trillion tokens, whereas our InternVL2.5-78B is trained on only about 120 billion tokens—less than one-tenth of Qwen2-VL.

Questions:

1. Are these two mentions referring to the same reduction in training tokens?

2. If yes, is this reduction a combined effect of both the large vision encoder and progressive scaling strategy?

3. If it's a combined effect, what are the relative contributions of each approach to reducing the training tokens?

It would be helpful to have some clarification or ablation studies showing how each innovation contributes to reducing the training data requirements. This would provide better insights into the effectiveness of each approach.

**Comment by czczup** [comment]
Hi, thanks for your attention.  The large vision encoder reduces the training tokens required for Stage 2, while the progressive scaling strategy skips Stage 1.5, further reducing the total number of tokens.

Due to limited resources, we currently don't have a detailed ablation study to quantify the exact contribution of each approach, but we plan to explore this in future work.

**Comment by gudo7208** [comment]
Thank you for your detailed explanation! This helps clarify how the large vision encoder and progressive scaling strategy work together to reduce the training tokens. I appreciate you taking the time to address this question, and I look forward to seeing the future ablation studies on this topic.
