### ISSUE TITLE
[Docs] internvl2_5系列支持训练吗

### ISSUE THREAD

**Issue by Yangfan-96** [OpenGVLab/InternVL#744]
### 📚 The doc issue

internvl2_5系列支持训练吗，我看训练的shell列表中没有2.5系列的训练脚本，是不是在2的脚本上直接修改模型路径就可以训练2.5版本的模型了？

**Comment by Jintao-Huang** [comment]
会有一些system的区别，其他是一样的
😊ms-swift已经支持了internvl2.5的CPT/SFT/RLHF: https://github.com/modelscope/ms-swift/pull/2575

**Comment by Yangfan-96** [comment]
> 会有一些system的区别，其他是一样的 😊ms-swift已经支持了internvl2.5的CPT/SFT/RLHF: [modelscope/ms-swift#2575](https://github.com/modelscope/ms-swift/pull/2575)

system的区别是什么意思呢，不使用swift框架，后续能用这个git项目直接训练吗

**Comment by yimuu** [comment]
> 会有一些system的区别，其他是一样的 😊ms-swift已经支持了internvl2.5的CPT/SFT/RLHF: [modelscope/ms-swift#2575](https://github.com/modelscope/ms-swift/pull/2575)

后面会发布2.5训练脚本嘛

**Comment by zzzz123-0708** [comment]
> 会有一些system的区别，其他是一样的 😊ms-swift已经支持了internvl2.5的CPT/SFT/RLHF: [modelscope/ms-swift#2575](https://github.com/modelscope/ms-swift/pull/2575)

您好，ms-swift训练框架支持dynamic_image_size训练吗，是按照config进行训练的还是resize为448单图

**Comment by Weiyun1025** [comment]
你好，internvl2.5的训练和2.0的训练是基本一样的，只需要把对话模板改成internvl2_5就行，我们会尽快相关文档，目前可以参考[2.0的脚本](https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/shell/internvl2.0/2nd_finetune/internvl2_8b_internlm2_7b_dynamic_res_2nd_finetune_full.sh)来训练2.5，只需要修改`--conv_style`为`internvl2_5`，并把模型路径改成2.5的路径即可。（2.5的所有模型都统一使用`internvl2_5`的对话模板）
