### ISSUE TITLE
[Bug] intern2.5 VL 38B 无论是swit 还是lmdeploy H800 部署都不成功

### ISSUE THREAD

**Issue by dhhcj1** [OpenGVLab/InternVL#749]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

swift超显存
![40fd82a151afeabdc8577d9ebb4fba1b_origin(1)](https://github.com/user-attachments/assets/46348d8c-9106-4e1f-9667-34b64855a41c)
lmdeploy (用的示例代码起的单图推理)
![7975c3a5a6913e03edb70d3f958d59bd_compress](https://github.com/user-attachments/assets/ea4d2f64-d3d3-4b25-bc7b-2f628ef12005)

部署都没有问题!服务都能起起来，问题就是会超显存
显卡是H800

### Reproduction

swift 部署命令
CUDA_VISIBLE_DEVICES=1 swift deploy --ckpt dir /data/XXX/InternvL2 5-38B -max_model_len 128

lmdeploy check_env
![5281737f128bad906acaad828e0b4f3c_compress](https://github.com/user-attachments/assets/1e8c0140-0edc-4ab4-bfcf-1ddc483c54d0)

![849f38613d4256f86a3ef7bbc30c1c67_compress](https://github.com/user-attachments/assets/1cab3421-faac-4a05-adc3-b5f1da6b1994)

### Environment

```Shell
lmdeploy check_env 截图在上，不是很方便复制粘贴
```

**Comment by yuecao0119** [comment]
非常感谢你的提问。
应该是因为单张H800的显存容量不足以放下默认参数bf16版本的38B模型，你可以试着在TurbomindEngineConfig中添加cache_max_entry_count=0.5或者0.2试一下，参考2.0的[显卡预估表格](https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html#memory-usage-testing)。如果还是不可以推荐你选择更小的模型，或者使用AWQ量化后的模型。

在我的电脑上，单卡A800，默认参数也会内存溢出。但是cache_max_entry_count=0.5是可以正常运行的。希望能给你提供帮助。
```python
from lmdeploy import pipeline, TurbomindEngineConfig
from lmdeploy.vl import load_image

model = 'OpenGVLab/InternVL2_5-38B'
image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
pipe = pipeline(model, backend_config=TurbomindEngineConfig(session_len=8192, cache_max_entry_count=0.5))
response = pipe(('describe this image', image))
print(response.text)
```

**Comment by dhhcj1** [comment]
> 非常感谢你的提问。 应该是因为单张H800的显存容量不足以放下默认参数bf16版本的38B模型，你可以试着在TurbomindEngineConfig中添加cache_max_entry_count=0.5或者0.2试一下，参考2.0的[显卡预估表格](https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html#memory-usage-testing)。如果还是不可以推荐你选择更小的模型，或者使用AWQ量化后的模型。
> 
> 在我的电脑上，单卡A800，默认参数也会内存溢出。但是cache_max_entry_count=0.5是可以正常运行的。希望能给你提供帮助。
> 
> ```python
> from lmdeploy import pipeline, TurbomindEngineConfig
> from lmdeploy.vl import load_image
> 
> model = 'OpenGVLab/InternVL2_5-38B'
> image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
> pipe = pipeline(model, backend_config=TurbomindEngineConfig(session_len=8192, cache_max_entry_count=0.5))
> response = pipe(('describe this image', image))
> print(response.text)
> ```

感谢大佬回复，参照大佬的测试代码，我也试了试但是发现又有了新的报错
called after throwing an instance of 'std::runtime error'
![b79a3756e85760393795ac76ec51cd80_compress](https://github.com/user-attachments/assets/d9308364-2aa2-42d3-975c-22fb3010124f)
没在网上找到能解决的方法

**Comment by yuecao0119** [comment]
> > 非常感谢你的提问。 应该是因为单张H800的显存容量不足以放下默认参数bf16版本的38B模型，你可以试着在TurbomindEngineConfig中添加cache_max_entry_count=0.5或者0.2试一下，参考2.0的[显卡预估表格](https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html#memory-usage-testing)。如果还是不可以推荐你选择更小的模型，或者使用AWQ量化后的模型。
> > 在我的电脑上，单卡A800，默认参数也会内存溢出。但是cache_max_entry_count=0.5是可以正常运行的。希望能给你提供帮助。
> > ```python
> > from lmdeploy import pipeline, TurbomindEngineConfig
> > from lmdeploy.vl import load_image
> > 
> > model = 'OpenGVLab/InternVL2_5-38B'
> > image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
> > pipe = pipeline(model, backend_config=TurbomindEngineConfig(session_len=8192, cache_max_entry_count=0.5))
> > response = pipe(('describe this image', image))
> > print(response.text)
> > ```
> 
> 感谢大佬回复，参照大佬的测试代码，我也试了试但是发现又有了新的报错 called after throwing an instance of 'std::runtime error' ![b79a3756e85760393795ac76ec51cd80_compress](https://private-user-images.githubusercontent.com/26638809/396025613-d9308364-2aa2-42d3-975c-22fb3010124f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDg1NjIsIm5iZiI6MTczNDM0ODI2MiwicGF0aCI6Ii8yNjYzODgwOS8zOTYwMjU2MTMtZDkzMDgzNjQtMmFhMi00MmQzLTk3NWMtMjJmYjMwMTAxMjRmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDExMjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMjUwZGI4NjA2NjVkYTY4ZjdlMzlkNjNjNjYwZGMyMDAzYWE5ZDJmYjFlYWNiMDMzZDA4NmFiMWM4MGRiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UIuH6_DglrL_Za4jaWCtLxEbLXT90vrIc3gXEp_XmYE) 没在网上找到能解决的方法

我看你的执行命令是用的两张卡。你试试在TurbomindEngineConfig中再加个参数 tp=2呢？

**Comment by dhhcj1** [comment]
> > > 非常感谢你的提问。 应该是因为单张H800的显存容量不足以放下默认参数bf16版本的38B模型，你可以试着在TurbomindEngineConfig中添加cache_max_entry_count=0.5或者0.2试一下，参考2.0的[显卡预估表格](https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html#memory-usage-testing)。如果还是不可以推荐你选择更小的模型，或者使用AWQ量化后的模型。
> > > 在我的电脑上，单卡A800，默认参数也会内存溢出。但是cache_max_entry_count=0.5是可以正常运行的。希望能给你提供帮助。
> > > ```python
> > > from lmdeploy import pipeline, TurbomindEngineConfig
> > > from lmdeploy.vl import load_image
> > > 
> > > model = 'OpenGVLab/InternVL2_5-38B'
> > > image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
> > > pipe = pipeline(model, backend_config=TurbomindEngineConfig(session_len=8192, cache_max_entry_count=0.5))
> > > response = pipe(('describe this image', image))
> > > print(response.text)
> > > ```
> > 
> > 
> > 感谢大佬回复，参照大佬的测试代码，我也试了试但是发现又有了新的报错 called after throwing an instance of 'std::runtime error' ![b79a3756e85760393795ac76ec51cd80_compress](https://private-user-images.githubusercontent.com/26638809/396025613-d9308364-2aa2-42d3-975c-22fb3010124f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDg1NjIsIm5iZiI6MTczNDM0ODI2MiwicGF0aCI6Ii8yNjYzODgwOS8zOTYwMjU2MTMtZDkzMDgzNjQtMmFhMi00MmQzLTk3NWMtMjJmYjMwMTAxMjRmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDExMjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmMjUwZGI4NjA2NjVkYTY4ZjdlMzlkNjNjNjYwZGMyMDAzYWE5ZDJmYjFlYWNiMDMzZDA4NmFiMWM4MGRiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UIuH6_DglrL_Za4jaWCtLxEbLXT90vrIc3gXEp_XmYE) 没在网上找到能解决的方法
> 
> 我看你的执行命令是用的两张卡。你试试在TurbomindEngineConfig中再加个参数 tp=2呢？

感谢耐心回复，已经没有问题了
