### ISSUE TITLE
用InternVL-14B-FlickrCN-FT-364px做图像检索时的问题

### ISSUE THREAD

**Issue by lrain-CN** [OpenGVLab/InternVL#75]
如果图像库中有图像是空白或者有文字时会导致相似度很高，好像导致不管什么文本都检索到此类图像，有人遇到这种问题嘛？
![detail_pic_1](https://github.com/OpenGVLab/InternVL/assets/28183707/5b2b8728-b4b1-49a5-9895-1e37b5aad968)
![detail_pic_18](https://github.com/OpenGVLab/InternVL/assets/28183707/29e3e96f-b903-42b1-9817-2c81909ae349)

**Comment by czczup** [comment]
您好，能看看您的检索代码吗
