### ISSUE TITLE
[Docs] 关于InternViT-300M-448px-V2.5的疑问

### ISSUE THREAD

**Issue by davidlight2018** [OpenGVLab/InternVL#753]
### 📚 The doc issue

请问 InternViT-300M-448px-V2.5 是在 InternVL2.5-8B 上的 stage1.5 阶段训练出来，然后再应用到 1B~4B 的版本上的吗？

**Comment by lll2343** [comment]
是的

**Comment by davidlight2018** [comment]
好的感谢回复
