### ISSUE TITLE
internVL 2.5 技术报告中提到的Loss Reweighting策略什么时候合入代码

### ISSUE THREAD

**Issue by yanzaaaasa** [OpenGVLab/InternVL#756]
### Motivation

To enhance the model’s adaptability to real-world scenarios and overall performance, two key techniques are
introduced. These optimizations are essential in improving the user experience and the model’s benchmark
performance.    

Random JPEG Compression. 
Loss Reweighting.

**Comment by KaiWU5** [comment]
Checking #746  for my implemented version of  loss function

**Comment by czczup** [comment]
您好，这个策略已经在代码里了，见这里：
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/internvl/train/internvl_chat_pretrain.py#L830

**Comment by yanz2024** [comment]
好的，感谢~
