### ISSUE TITLE
does InternVL-Chat support batch inference?

### ISSUE THREAD

**Issue by shineleex** [OpenGVLab/InternVL#76]

**Comment by czczup** [comment]
最新的V1.5模型已经支持了batch inference，具体可以看这里的代码样例：
https://huggingface.co/OpenGVLab/InternVL-Chat-V1-5#model-usage

其中的# batch inference (single image per sample)这部分

**Comment by joeyz0z** [comment]
我需要做图像变换检测，我想知道 InternVL支持 batch inference (multi-image per sample)吗？
