### ISSUE TITLE
The repeat time parameter in the dataset configuration file

### ISSUE THREAD

**Issue by ChenJian7578** [OpenGVLab/InternVL#763]
Is there any benefit to model fine-tuning when the repeat_time parameter in the data set configuration file is greater than 1

**Comment by yuecao0119** [comment]
Thank you very much for your question.
Regarding the `repeat_time` parameter, my understanding is that on the one hand, the amount of high-quality data is relatively small, and on the other hand, the amount of data in different fields is different. By setting `repeat_time`, the number of active data samples and the data mixing ratio can be adjusted to make better use of high-quality data. In addition, increasing the `repeat_time` of a small amount of data to increase its proportion in the entire data can allow the model to quickly adapt to this specific data.
I hope this can help you.

**Comment by czczup** [comment]
> Can it be understood that when I have only one custom dataset, the repeat time argument is equivalent to the nummber_reain_epoch argument?

Yes, you are right.
