### ISSUE TITLE
[Feature]InternVL2/2.5 is supported in PaddleMIX by Paddle Team!

### ISSUE THREAD

**Issue by luyao-cv** [OpenGVLab/InternVL#765]
### Motivation

Thanks to all the authors for their great work!
🚀🚀🚀 [InternVL2/2.5](https://github.com/PaddlePaddle/PaddleMIX/tree/develop/paddlemix/examples/internvl2)  is supported in  [PaddleMIX](https://github.com/PaddlePaddle/PaddleMIX) by Paddle Team. Welcome everyone to try it out! 

Please star the repository if you find it helpful!

**Comment by czczup** [comment]
Thank you for your support!
