### ISSUE TITLE
[Bug] Issue when loading finetuned InternVL2.5-8B model

### ISSUE THREAD

**Issue by zilunzhang** [OpenGVLab/InternVL#768]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Hi, I full-finetuned an 8B InternVL2.5 for the domain-specific task, but when I loaded the checkpoint, a bug popped up:

```Shell

Traceback (most recent call last):
  File "/media/zilun/InternVL/inference.py", line 86, in <module>
    model = AutoModel.from_pretrained(
  File "/home/zilun/anaconda3/envs/imagerag/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/zilun/anaconda3/envs/imagerag/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1109, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "/home/zilun/anaconda3/envs/imagerag/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "/home/zilun/anaconda3/envs/imagerag/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
  File "/home/zilun/anaconda3/envs/imagerag/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.internvl2'
```

Any suggestion?

The transformer version is 4.37.2, as required by requirements.txt.

Thanks

### Reproduction

    model = AutoModel.from_pretrained(
        "/media/zilun/fanxiang4t/ImageRAG_git/checkpoint/internvl2.5_8b_finetune_full_8param_single",
        torch_dtype=torch.bfloat16,
        # low_cpu_mem_usage=True,
        trust_remote_code=True
    ).eval().cuda()
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True, use_fast=False)

### Environment

```Shell
Finetuned OpenGVLab/InternVL2_5-8B

pip install torch
```

**Comment by RiverGao** [comment]
Same issue. I didn't finetune the model, but just using huggingface transformers to load it by:
```
import torch
from transformers import AutoTokenizer, AutoModel

path = "OpenGVLab/InternVL2_5-8B"
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    use_flash_attn=True,
    trust_remote_code=True).eval().cuda()
```
And I got `ModuleNotFoundError: No module named 'transformers_modules.internvl2'`

**Comment by zilunzhang** [comment]
> Same issue. I didn't finetune the model, but just using huggingface transformers (4.45.2) to load it by:
> 
> ```
> import torch
> from transformers import AutoTokenizer, AutoModel
> 
> path = "OpenGVLab/InternVL2_5-8B"
> model = AutoModel.from_pretrained(
>     path,
>     torch_dtype=torch.bfloat16,
>     low_cpu_mem_usage=True,
>     use_flash_attn=True,
>     trust_remote_code=True).eval().cuda()
> ```
> 
> And I got `ModuleNotFoundError: No module named 'transformers_modules.internvl2'`
> 
> detailed error message:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".../lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
>     config, kwargs = AutoConfig.from_pretrained(
>   File ".../lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1015, in from_pretrained
>     config_class = get_class_from_dynamic_module(
>   File ".../lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 552, in get_class_from_dynamic_module
>     return get_class_in_module(class_name, final_module, force_reload=force_download)
>   File ".../lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 249, in get_class_in_module
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File ".../.cache/huggingface/modules/transformers_modules/internvl2.5-8b/configuration_internvl_chat.py", line 13, in <module>
>     from .configuration_intern_vit import InternVisionConfig
> ModuleNotFoundError: No module named 'transformers_modules.internvl2'
> ```

Not sure if this help: https://github.com/OpenGVLab/InternVL/issues/720#issuecomment-2492802266

**Comment by Weiyun1025** [comment]
Please copy the code of model architecture (e.g., `configuration_intern_vit.py`,`configuration_internlm2.py`,`configuration_internvl_chat.py`,`conversation.py`,`modeling_intern_vit.py`,`modeling_internlm2.py`,`modeling_internvl_chat.py`) so that this checkpoint can be loaded using `AutoModel.from_pretrained`.

**Comment by zilunzhang** [comment]
> Please copy the code of model architecture (e.g., `configuration_intern_vit.py`,`configuration_internlm2.py`,`configuration_internvl_chat.py`,`conversation.py`,`modeling_intern_vit.py`,`modeling_internlm2.py`,`modeling_internvl_chat.py`) so that this checkpoint can be loaded using `AutoModel.from_pretrained`.

Hi, I tried using my local machine (4090), but it does not work (all 7 files are pasted). The bug information remains  (ModuleNotFoundError: No module named 'transformers_modules.internvl2').

In my server (A800), the inference script will remind me "modeling_internvl_chat.py is missing"  etc., and the model works smoothly after I paste them.

Both of them are linux, with python3.9 and transformer 4.37.2
