### ISSUE TITLE
issues on mmseg version

### ISSUE THREAD

**Issue by sxu1997** [OpenGVLab/InternVL#77]
Hi~
I follow [INSTALLATION](https://github.com/OpenGVLab/InternVL/blob/main/INSTALLATION.md) to prepare env and install mmcv-full==1.6.2. 
When I test the [linear_intern_vit_6b_504_80k_ade20k_bs16_lr4e-5_frozen.pth] model I met this issue:
"ModuleNotFoundError: No module named 'mmseg'"
I try way 1:  pip install mmsegmentation
or way 2: clone the [mmseg repo](https://github.com/open-mmlab/mmsegmentation/tree/v0.30.0/mmseg) and export PYTHONPATH
all the ways met that: "AssertionError: MMCV==1.6.2 is used but incompatible. Please install mmcv>=2.0.0rc4."

**Comment by mj129** [comment]
@sxu1997 
I have the same error , is there any way to resolve it ? Thanks

**Comment by TybaltGong** [comment]
@mj129 I had the same problem. Did you solve it?
