### ISSUE TITLE
[Feature] 请问有计划开源2.5的训练数据吗？

### ISSUE THREAD

**Issue by zxc351200** [OpenGVLab/InternVL#770]
### Motivation

请问有计划开源2.5的训练数据吗？

**Comment by yuecao0119** [comment]
感谢你的提问。
可以关注我们[InternVL 2.5的技术报告](https://huggingface.co/papers/2412.05271)，2.5使用的数据集是在2.0基础上进一步丰富。其中，4.3章节详细罗列了使用的数据集有哪些，3.2和3.3章节有不同大小模型的对应训练策略和每阶段使用的数据规模。

**Comment by czczup** [comment]
您好，感谢您的关注，我们在InternVL 2.5中使用的所有开源数据集均已经列在2.5的技术报告中了；

由于一些原因，我们目前没有计划去二次分发这些数据集。

**Comment by zxc351200** [comment]
好的，感谢回复
