### ISSUE TITLE
[Docs] 发布的2.5模型权重训练时用的Maximum Tile Number是多少？

### ISSUE THREAD

**Issue by marvin521** [OpenGVLab/InternVL#773]
### 📚 The doc issue

方便告知2.5版本8B模型训练时的Tile Number？ 方便我们对齐，不同的Tile Number效果还不太一样

**Comment by czczup** [comment]
您好，对于单个数据集，我们设置的Maximum Tile Number在[6, 36]的范围内，具体的数值根据数据集的特性进行设置；对于一个Packed Sample，我们设置的Maximum Tile Number是48，即技术报告中的Image Tile Threshold。具体的技术细节您可以阅读我们InternVL 2.5的技术报告。

<img width="937" alt="image" src="https://github.com/user-attachments/assets/19af917e-5397-4ac2-922a-8339ca77328d" />
