### ISSUE TITLE
OCR推理时，若将图片内容的间隔进行调整，效果有提升；但不是越大间隔越好？怎样才能找到最好的间隔？

### ISSUE THREAD

**Issue by evanlin88** [OpenGVLab/InternVL#775]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

OCR推理时，若将图片内容的间隔进行调整，效果有提升；但不是越大间隔越好？怎样才能找到最好的间隔？
![6_revised](https://github.com/user-attachments/assets/0dd6f905-9f40-4f0e-bb4f-472a1aad561d)
上图识别结果【**存在不准，而且漏行**】：
解: (1) ∵ a = b = 3  ∴ c + d m = 1

解得：m = - \frac{2}{7}

(2) \( C < A.\ )即\( C-A >0 )

所以, \( B-D=-\frac{c-a} {d-m}<0 \)

因此, \( B<D \)

![7_revised](https://github.com/user-attachments/assets/b0690ba2-0e7e-408d-9191-f55c5850b26c)
上图识别结果【**调整图中内容间距，但调大了未必最好的效果？**】：
解: (1) ∵ a = b = 3  ∴. 3 + 3 m = 1

解得：m = - \frac{2}{3}

∴ c和d的关系为 d > C

(2 ) a < c, 即c-a>0

所以b-d=-\frac{7}{8}(c-a)<0

∴, b<d

### Reproduction

使用提示词：OCR识别图像，进行推理

### Environment

```Shell
模型：InternVL2_5-8B
transformers： 4.37.2
torch： 2.3.1
运行服务：CUDA_VISIBLE_DEVICES=0 lmdeploy serve api_server /data/models/InternVL2_5-8B  --server-port 23333 --cache-max-entry-count 0.1
```

**Comment by Weiyun1025** [comment]
看起来是因为不同的图像长宽比导致切出来的patch数量不同导致的，可以试试参考[这个代码](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/multi_modal/internvl.md?plain=1#L69)把max_dynamic_patch调大到18或者24效果会不会变好

**Comment by evanlin88** [comment]
> 看起来是因为不同的图像长宽比导致切出来的patch数量不同导致的，可以试试参考[这个代码](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/multi_modal/internvl.md?plain=1#L69)把max_dynamic_patch调大到18或者24效果会不会变好

ok，感谢，我试试
