### ISSUE TITLE
Retrieval fine-tuning resources requirement

### ISSUE THREAD

**Issue by yfb-xieyu** [OpenGVLab/InternVL#79]
I'm very interested in your work. The chapter on retrieval fine-tuning provides the corresponding script at https://github.com/OpenGVLab/InternVL/tree/main/internvl_g, which uses 32 A100 GPUs. May I ask how long it would take to train on Flickr30K with 32 A100 GPUs, and whether it's possible to replicate this training if I only have 4 A100 GPUs?

**Comment by lexilii** [comment]
Do you have the answer yet?

How many GPUs do you need for fine-tuning in your tests?

**Comment by czczup** [comment]
Hi, you can see this document for retrieval fine-tuning: https://internvl.readthedocs.io/en/latest/internvl1.0/internvl_g.html#retrieval-fine-tuning-head

The GPU memory requirement is shown here:

<img width="824" alt="image" src="https://github.com/user-attachments/assets/0fa58789-72ae-4964-9faa-3ba6b6539435">
