### ISSUE TITLE
InternVL CLIP Compatibility

### ISSUE THREAD

**Issue by puffy310** [OpenGVLab/InternVL#89]
Hello, hope the authors are doing well. 
I am wondering if there is a way to get an InternVL model to function as a standard CLIP Vision tower. I am currently working on a project using the LLaVA codebase and I have been unsuccessful in retrofitting it for InternVLz

**Comment by puffy310** [comment]
Seems I have found a similar discussion in issue #83, will close issue and continue dissent there.

**Comment by puffy310** [comment]
This is extremely helpful, I applaud your effort greatly. I will test it and let you know if there's any issue. Thank you so much 😀

**Comment by puffy310** [comment]
Update: It seems like an error consistently pops up repeatedly.
I'm leaving this issue as a personal note to submit an error request, TL;DR of it is that it claims LlavaLlamaForCasualLM has not been imported, and that llava.model doesn't have it.

**Comment by czczup** [comment]
May I ask if this issue has been resolved?
