### ISSUE TITLE
InternVL-Chat-V1.5 Gradio Demo file to run locally

### ISSUE THREAD

**Issue by swz30** [OpenGVLab/InternVL#93]
Hi @whai362 @czczup 

Congrats on the excellent work.  

Could you please share the InternVL-Chat-V1.5 (https://internvl.opengvlab.com/) demo files to run locally? Thank you.

**Comment by swz30** [comment]
Hi @douyh 
I am aware of this link. But I am looking for the huggingface Spaces demo files (i.e, files used in this [demo](https://internvl.opengvlab.com/) )so that I can run the demo locally with a GPU.

**Comment by thr3a** [comment]
I would also like to run InternVL-Chat-V1.5 locally.
I believe the base source code is at https://huggingface.co/spaces/liuhaotian/LLaVA-1.6/tree/main, but simply changing the model_id resulted in errors and it did not work.

**Comment by czczup** [comment]
Thanks for your attention, I have now open-source all the code needed to deploy the local demo, which can be performed by following the steps below:

Note: the following command requires an 80G A100. There are still some issues with the deployment of 4bit quantitative models and multi-gpu deployment, we will resolve them soon.


## Launch a controller

```
# run the command in the `internvl_chat_llava` folder
python -m llava.serve.controller --host 0.0.0.0 --port 10000
```

## Launch a gradio web server

```
# run the command in the `internvl_chat_llava` folder
python -m llava.serve.gradio_web_server --controller http://localhost:10000 --model-list-mode reload
```

## Launch a model worker

```
# OpenGVLab/InternVL-Chat-V1-5
# run the command in the `internvl_chat` folder
python -m internvl.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40003 --worker http://localhost:40003 --model-path ./path/to/InternVL-Chat-V1-5
```

**Comment by swz30** [comment]
Thank you very much Zhe Chen!

**Comment by dragronstranding** [comment]
I have an error，when I run “Launch a gradio web server” . The error: requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=10000): Max retries exceeded with url: /refresh_all_workers (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1bd02efd60>: Failed to establish a new connection: [Errno 111] Connection refused'))
