### ISSUE TITLE
如何复现在mathvista上59.9%的效果

### ISSUE THREAD

**Issue by DexterGuo** [OpenGVLab/InternVL#97]
感谢做了这么好的工作。
我们用1.2 plus复现mathvista的效果，最好只有37%，跟公开的59.9%相差太远，辛苦指导下，是哪里没用对吗？

**Comment by czczup** [comment]
请问您使用的transformers版本是什么

**Comment by czczup** [comment]
需要使用OpenAI的key，用GPT4辅助抽取答案，37%的点数是因为没有使用GPT4

**Comment by czczup** [comment]
参考这部分的文档：https://internvl.readthedocs.io/en/latest/internvl1.2/evaluation.html#mathvista
